//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo26OpenInApolloViewController_h
#define _TtC6Apollo26OpenInApolloViewController_h
@import Foundation;

@class UIViewController, _$s12CoreGraphics7CGFloatVMn, _$sSa -> Apollo.EnableInstructionView, _$sSd, _$sSo10UITextViewC, _$sSo12UIScrollViewC, _$sSo7UILabelC, pollo.VideoExplainerView;

@interface _TtC6Apollo26OpenInApolloViewController : UIViewController { // (Swift)
    /* instance variables */
    _$sSo12UIScrollViewC scrollView;
    _$sSo7UILabelC newLabel;
    _$sSo7UILabelC mainTitleLabel;
    _$sSa -> Apollo.EnableInstructionView instructionViews;
    _Atomic pollo.VideoExplainerView videoExplainerView;
    _$sSo10UITextViewC extraTextView;
    _$sSd videoSideSpacing;
    _$sSd sideSpacing;
    _$sSd videoBottomSpacing;
    _$sSd instructionIntraSpacing;
    _$s12CoreGraphics7CGFloatVMn titleTopSpacing;
    _$s12CoreGraphics7CGFloatVMn titleBottomSpacing;
    _$s12CoreGraphics7CGFloatVMn extraTextViewTopSpacing;
    _$s12CoreGraphics7CGFloatVMn funFactBottomSpacing;
}

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)doneBarButtonItemTappedWithSender:(id)sender;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)gotItButtonTappedWithSender:(id)sender;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo26OpenInApolloViewController_h */
