//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo14PollResultNode_h
#define _TtC6Apollo14PollResultNode_h
@import Foundation;

@class ASDisplayNode, Swift.Bool, _$sSi, _$sSo10ASTextNodeC, _$sSo11ASImageNodeCSg, _$sSo13ASDisplayNodeC, _$sSo13RDKPollOptionC;

@interface _TtC6Apollo14PollResultNode : ASDisplayNode { // (Swift)
    /* instance variables */
    _$sSo13RDKPollOptionC option;
    Swift.Bool userDidSelect;
    _$sSi totalVotesInPoll;
    Swift.Bool hasMostVotes;
    _$sSo13ASDisplayNodeC backgroundNode;
    _$sSo10ASTextNodeC textNode;
    _$sSo10ASTextNodeC percentageNode;
    _$sSo11ASImageNodeCSg checkmarkNode;
    Swift.Bool showPercentages;
}

/* instance methods */
- (void)layout;
- (void)layoutDidFinish;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)init;

@end

#endif /* _TtC6Apollo14PollResultNode_h */
