//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo16ViewFullPostNode_h
#define _TtC6Apollo16ViewFullPostNode_h
@import Foundation;

@class ASControlNode, _$sSo10ASTextNodeC, _$sSo11ASImageNodeC;

@interface _TtC6Apollo16ViewFullPostNode : ASControlNode { // (Swift)
    /* instance variables */
    _$sSo10ASTextNodeC titleNode;
    _$sSo10ASTextNodeC subtitleNode;
    _$sSo11ASImageNodeC disclosureIndicator;
}

/* class methods */
+ (void)drawRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect withParameters:(id)parameters isCancelled:(id /* block */)cancelled isRasterizing:(_Bool)rasterizing;

/* instance methods */
- (id)init;
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)drawParametersForAsyncLayer:(id)layer;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;

@end

#endif /* _TtC6Apollo16ViewFullPostNode_h */
