//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo25MuteUnmuteVideoButtonNode_h
#define _TtC6Apollo25MuteUnmuteVideoButtonNode_h
@import Foundation;

#include "_TtC6Apollo16ApolloButtonNode.h"

@class Swift.Bool, _$s12CoreGraphics7CGFloatVMn, _$sSo11ASImageNodeC, _$sSo13ASDisplayNodeC, _$sSo7NSTimerCSg;

@interface _TtC6Apollo25MuteUnmuteVideoButtonNode : _TtC6Apollo16ApolloButtonNode { // (Swift)
    /* instance variables */
    Swift.Bool isMuted;
    _$s12CoreGraphics7CGFloatVMn size;
    _$sSo11ASImageNodeC icon;
    _$sSo13ASDisplayNodeC audioSimulatingNode;
    _$sSo7NSTimerCSg audioSimulatorTimer;
}

/* instance methods */
- (void)didEnterVisibleState;
- (void)didExitVisibleState;
- (void)layout;

@end

#endif /* _TtC6Apollo25MuteUnmuteVideoButtonNode_h */
