//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo18FlairSelectionNode_h
#define _TtC6Apollo18FlairSelectionNode_h
@import Foundation;

#include "_TtC6Apollo18SelectableCellNode.h"

@class Swift.Bool, _$sSS, _$sSaySo13ASDisplayNodeCG, _$sSaySo8RDKFlairCG, _$sSo11ASImageNodeCSg, __C.CGSize;

@interface _TtC6Apollo18FlairSelectionNode : _TtC6Apollo18SelectableCellNode { // (Swift)
    /* instance variables */
    _$sSaySo8RDKFlairCG flairs;
    _$sSS textRepresentation;
    Swift.Bool hasCheckmark;
    _$sSaySo13ASDisplayNodeCG contentNodes;
    _$sSo11ASImageNodeCSg checkmarkNode;
    __C.CGSize imageSize;
}

/* instance methods */
- (void)didEnterPreloadState;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo18FlairSelectionNode_h */
