//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo41SettingsMarkReadHidingPostsViewController_h
#define _TtC6Apollo41SettingsMarkReadHidingPostsViewController_h
@import Foundation;

@class _$s6Eureka18FormViewControllerCN;

@interface _TtC6Apollo41SettingsMarkReadHidingPostsViewController : _$s6Eureka18FormViewControllerCN // (Swift)

/* instance methods */
- (void)viewDidLoad;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo41SettingsMarkReadHidingPostsViewController_h */
