//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo32PostsSearchResultsViewController_h
#define _TtC6Apollo32PostsSearchResultsViewController_h
@import Foundation;

@class ASDKViewController, _$sSS, _$sSSSg, _$sSaySo7RDKLinkCGSg, _$sSo11ASTableNodeC, _$sSo13RDKPaginationCSg, _$sSo15UIBarButtonItemC, __C.RDKSearchSortingMethod, __C.RDKTimeSortingMethod ?, pollo.ListAdapter;

@interface _TtC6Apollo32PostsSearchResultsViewController : ASDKViewController { // (Swift)
    /* instance variables */
    _$sSS searchQuery;
    _$sSSSg subredditName;
    _$sSaySo7RDKLinkCGSg links;
    __C.RDKSearchSortingMethod currentSort;
    __C.RDKTimeSortingMethod ? currentTimeSort;
    _$sSo13RDKPaginationCSg currentPagination;
    _$sSo11ASTableNodeC tableNode;
    _Atomic pollo.ListAdapter listAdapter;
    _$sSo15UIBarButtonItemC sortBarButtonItem;
}

/* instance methods */
- (void)refreshControlActivatedWithSender:(id)sender;
- (void)sortBarButtonItemTappedWithSender:(id)sender;
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (id)initWithNode:(id)node;
- (id)init;

@end

#endif /* _TtC6Apollo32PostsSearchResultsViewController_h */
