//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo10InsetLabel_h
#define _TtC6Apollo10InsetLabel_h
@import Foundation;

@class UILabel, __C.UIEdgeInsets;

@interface _TtC6Apollo10InsetLabel : UILabel { // (Swift)
    /* instance variables */
    __C.UIEdgeInsets textInsets;
}

/* instance methods */
- (void)drawTextInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo10InsetLabel_h */
