//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC14SwiftyStoreKit26InAppReceiptRefreshRequest_h
#define _TtC14SwiftyStoreKit26InAppReceiptRefreshRequest_h
@import Foundation;

#include "SKRequestDelegate-Protocol.h"

@class NSObject, _$sSo23SKReceiptRefreshRequestC;

@interface _TtC14SwiftyStoreKit26InAppReceiptRefreshRequest : NSObject <SKRequestDelegate> { // (Swift)
    /* instance variables */
    _$sSo23SKReceiptRefreshRequestC refreshReceiptRequest;
    SwiftyStoreKit.InAppReceiptRefreshRequest.ResultType function type (escaping) callback;
}

/* instance methods */
- (void)dealloc;
- (void)requestDidFinish:(id)finish;
- (void)request:(id)request didFailWithError:(id)error;
- (id)init;

@end

#endif /* _TtC14SwiftyStoreKit26InAppReceiptRefreshRequest_h */
