//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo11ListAdapter_Apollo_h
#define _TtC6Apollo11ListAdapter_Apollo_h
@import Foundation;

@interface _TtC6Apollo11ListAdapter (Apollo) <ASTableDataSource, ASTableDelegate> // (Swift)

/* instance methods */
- (void)tableNode:(id)node didSelectRowAtIndexPath:(id)path;
- (_Bool)shouldBatchFetchForTableNode:(id)node;
- (void)tableNode:(id)node willBeginBatchFetchWithContext:(id)context;
- (void)scrollViewWillBeginDragging:(id)dragging;
- (void)scrollViewDidScroll:(id)scroll;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(_Bool)decelerate;
- (long long)numberOfSectionsInTableNode:(id)node;
- (long long)tableNode:(id)node numberOfRowsInSection:(long long)section;
- (id /* block */)tableNode:(id)node nodeBlockForRowAtIndexPath:(id)path;

@end

#endif /* _TtC6Apollo11ListAdapter_Apollo_h */
