//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo29ModmailInboxSectionController_h
#define _TtC6Apollo29ModmailInboxSectionController_h
@import Foundation;

#include "_TtC6Apollo17SectionController.h"

@class _$sSo17RDKModmailMessageC, _$sSo26RDKModmailConversationInfoC;

@interface _TtC6Apollo29ModmailInboxSectionController : _TtC6Apollo17SectionController { // (Swift)
    /* instance variables */
    _$sSo26RDKModmailConversationInfoC modmailMessageConversationInfo;
    _$sSo17RDKModmailMessageC modmailMessage;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo29ModmailInboxSectionController_h */
