//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21BanUserViewController_h
#define _TtC6Apollo21BanUserViewController_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "UITextFieldDelegate-Protocol.h"
#include "UITextViewDelegate-Protocol.h"
#include "_TtC6Apollo25ApolloTableViewController.h"

@class Swift.Bool, _$s12CoreGraphics7CGFloatVMn, _$sSDySSyXlGSg, _$sSS, _$sSSSg, _$sSiSg, _$sSo10UITextViewCSgXw, _$sSo15UIBarButtonItemCSg, _$sSo7UILabelCSg, pollo.BanUserViewController.BanType _$s_So7NSErrorCSgtcSg;

@interface _TtC6Apollo21BanUserViewController : _TtC6Apollo25ApolloTableViewController <UITableViewDataSource, UITextViewDelegate, UITextFieldDelegate> { // (Swift)
    /* instance variables */
    _$sSS user;
    _$sSS subreddit;
    _$sSSSg fullNameContext;
    Swift.Bool isEditingBan;
    _$sSSSg existingMessage;
    _$sSSSg existingReason;
    _$sSSSg existingModNote;
    _$sSiSg existingDuration;
    _$sSo15UIBarButtonItemCSg cancelBarButtonItem;
    _$sSo15UIBarButtonItemCSg banBarButtonItem;
    _$sSDySSyXlGSg rules;
    _$sSiSg selectedRuleIndex;
    Swift.Bool permanentBan;
    _$sSiSg banDuration;
    _$sSo7UILabelCSg banFooterLabel;
    _$sSSSg banMessage;
    _$sSSSg banReason;
    Swift.Bool selectedOtherReason;
    _$sSSSg modNote;
    _$sSSSg userFullname;
    _Atomic pollo.BanUserViewController.BanType _$s_So7NSErrorCSgtcSg banCompletion;
    _$sSo10UITextViewCSgXw activeTextView;
    Swift.Bool haveChangesBeenMade;
    Swift.Bool ignoreScrollResignFirstResponder;
    _$s12CoreGraphics7CGFloatVMn messageTextViewHeight;
    _$s12CoreGraphics7CGFloatVMn modNoteTextViewHeight;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)keyboardWillShowWithNotification:(id)notification;
- (void)keyboardDidShowWithNotification:(id)notification;
- (void)keyboardWillHideWithNotification:(id)notification;
- (void)keyboardDidHideWithNotification:(id)notification;
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (id)tableView:(id)view viewForHeaderInSection:(long long)section;
- (id)tableView:(id)view viewForFooterInSection:(long long)section;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (void)tableView:(id)view willDisplayFooterView:(id)view forSection:(long long)section;
- (void)scrollViewDidScroll:(id)scroll;
- (void)tableViewTapped:(id)tapped;
- (void)cancelBarButtonItemTapped:(id)tapped;
- (void)banBarButtonItemTapped:(id)tapped;
- (void)permanentSwitchToggled:(id)toggled;
- (void)banDurationStepperValueChanged:(id)changed;
- (void)banDurationTextFieldChanged:(id)changed;
- (_Bool)textField:(id)field shouldChangeCharactersInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range replacementString:(id)string;
- (void)textViewDidBeginEditing:(id)editing;
- (void)textViewDidEndEditing:(id)editing;
- (void)textViewDidChange:(id)change;

@end

#endif /* _TtC6Apollo21BanUserViewController_h */
