//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo25ApolloUltraViewController_h
#define _TtC6Apollo25ApolloUltraViewController_h
@import Foundation;

@class Swift.Bool, UIViewController, _$sSaySo9SKProductCGSg, _$sSo16UIViewControllerCSg, _$syycSg, pollo.ApolloUltraSummonLocation, pollo.UltraScreenPaymentStatusModel;

@interface _TtC6Apollo25ApolloUltraViewController : UIViewController { // (Swift)
    /* instance variables */
    _Atomic pollo.ApolloUltraSummonLocation summonLocation;
    _$syycSg cancelHandler;
    _$syycSg unlockHandler;
    _$sSaySo9SKProductCGSg freshProducts;
    _Atomic pollo.UltraScreenPaymentStatusModel paymentStatusModel;
    Swift.Bool transactionInProgress;
    _$sSo16UIViewControllerCSg paymentScreenChildViewController;
    _$sSo16UIViewControllerCSg congratulationsScreenChildViewController;
}

@property (nonatomic, readonly) _Bool prefersStatusBarHidden;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)appear;
- (void)dismissViewControllerAnimated:(_Bool)animated completion:(id /* block */)completion;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo25ApolloUltraViewController_h */
