//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21FlairActionController_h
#define _TtC6Apollo21FlairActionController_h
@import Foundation;

#include "_TtC6Apollo16ActionController.h"

@class Swift.Bool, _$sSaySDySSypGG, _$sySS_S2StcSg, _$syycSg;

@interface _TtC6Apollo21FlairActionController : _TtC6Apollo16ActionController { // (Swift)
    /* instance variables */
    _$sSaySDySSypGG flairOptions;
    Swift.Bool isModerator;
    _$syycSg removedFlairHandler;
    _$sySS_S2StcSg selectedFlairHandler;
}

/* instance methods */
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo21FlairActionController_h */
