//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo32MessagesCollectionViewFlowLayout_h
#define _TtC6Apollo32MessagesCollectionViewFlowLayout_h
@import Foundation;

@class UICollectionViewFlowLayout, pollo.LocationMessageSizeCalculator ?, pollo.MediaMessageSizeCalculator ?, pollo.TextMessageSizeCalculator ?;

@interface _TtC6Apollo32MessagesCollectionViewFlowLayout : UICollectionViewFlowLayout { // (Swift)
    /* instance variables */
    _Atomic pollo.TextMessageSizeCalculator ? $__lazy_storage_$_textMessageSizeCalculator;
    _Atomic pollo.TextMessageSizeCalculator ? $__lazy_storage_$_attributedTextMessageSizeCalculator;
    _Atomic pollo.TextMessageSizeCalculator ? $__lazy_storage_$_emojiMessageSizeCalculator;
    _Atomic pollo.MediaMessageSizeCalculator ? $__lazy_storage_$_photoMessageSizeCalculator;
    _Atomic pollo.MediaMessageSizeCalculator ? $__lazy_storage_$_videoMessageSizeCalculator;
    _Atomic pollo.LocationMessageSizeCalculator ? $__lazy_storage_$_locationMessageSizeCalculator;
}

/* class methods */
+ (Class)layoutAttributesClass;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (id)layoutAttributesForElementsInRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)layoutAttributesForItemAtIndexPath:(id)path;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change;
- (id)invalidationContextForBoundsChange:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })change;
- (void)handleOrientationChange:(id)change;

@end

#endif /* _TtC6Apollo32MessagesCollectionViewFlowLayout_h */
