//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo36ModeratorReportsControllerDataSource_h
#define _TtC6Apollo36ModeratorReportsControllerDataSource_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "UITableViewDelegate-Protocol.h"

@class NSObject, _$sSaySayypGG, pollo.ModeratorReportableState ?;

@interface _TtC6Apollo36ModeratorReportsControllerDataSource : NSObject <UITableViewDataSource, UITableViewDelegate> { // (Swift)
    /* instance variables */
    _$sSaySayypGG userReports;
    _$sSaySayypGG moderatorReports;
    _Atomic pollo.ModeratorReportableState ? state;
}

/* instance methods */
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (id)tableView:(id)view viewForHeaderInSection:(long long)section;
- (void)tableView:(id)view willDisplayHeaderView:(id)view forSection:(long long)section;
- (id)init;

@end

#endif /* _TtC6Apollo36ModeratorReportsControllerDataSource_h */
