//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo9FlairNode_h
#define _TtC6Apollo9FlairNode_h
@import Foundation;

#include "_TtC6Apollo16ApolloButtonNode.h"

@class Swift.Bool, _$sSaySo13ASDisplayNodeCG, _$sSaySo8RDKFlairCG;

@interface _TtC6Apollo9FlairNode : _TtC6Apollo16ApolloButtonNode { // (Swift)
    /* instance variables */
    _$sSaySo8RDKFlairCG flairs;
    Swift.Bool isForAlert;
    _$sSaySo13ASDisplayNodeCG contentNodes;
    Swift.Bool isInTitle;
    Swift.Bool isInCollapsedComment;
}

/* instance methods */
- (_Bool)pointInside:(struct CGPoint { double x0; double x1; })inside withEvent:(id)event;
- (void)didEnterPreloadState;
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;

@end

#endif /* _TtC6Apollo9FlairNode_h */
