//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC14SwiftyStoreKit14SwiftyStoreKit_h
#define _TtC14SwiftyStoreKit14SwiftyStoreKit_h
@import Foundation;

@class SwiftyStoreKit.InAppReceiptVerificator, SwiftyStoreKit.PaymentQueueController, SwiftyStoreKit.ProductsInfoController, _TtCs12_SwiftObject;

@interface _TtC14SwiftyStoreKit14SwiftyStoreKit : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    SwiftyStoreKit.ProductsInfoController productsInfoController;
    SwiftyStoreKit.PaymentQueueController paymentQueueController;
    SwiftyStoreKit.InAppReceiptVerificator receiptVerificator;
}

@end

#endif /* _TtC14SwiftyStoreKit14SwiftyStoreKit_h */
