//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC7Statsig5Event_h
#define _TtC7Statsig5Event_h
@import Foundation;

@class Statsig.StatsigUser, Swift.Bool, _$sSDyS2SGSg, _$sSS, _$sSSSg, _$sSaySDyS2SGGSg, _$sSd, _$sypSg, _TtCs12_SwiftObject;

@interface _TtC7Statsig5Event : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSS name;
    _$sypSg value;
    _$sSDyS2SGSg metadata;
    _$sSd time;
    Statsig.StatsigUser user;
    _$sSaySDyS2SGGSg secondaryExposures;
    _$sSDyS2SGSg statsigMetadata;
    _$sSSSg allocatedExperimentHash;
    Swift.Bool isManualExposure;
}

@end

#endif /* _TtC7Statsig5Event_h */
