//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23CopyCommentTextActivity_h
#define _TtC6Apollo23CopyCommentTextActivity_h
@import Foundation;

@class NSString, UIActivity, UIImage, _$sSS;

@interface _TtC6Apollo23CopyCommentTextActivity : UIActivity { // (Swift)
    /* instance variables */
    _$sSS bodyMarkdown;
}

@property (nonatomic, readonly) NSString *activityType;
@property (nonatomic, readonly) NSString *activityTitle;
@property (nonatomic, readonly) UIImage *activityImage;

/* instance methods */
- (_Bool)canPerformWithActivityItems:(id)items;
- (void)performActivity;
- (id)init;

@end

#endif /* _TtC6Apollo23CopyCommentTextActivity_h */
