//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23RedditListTableViewCell_h
#define _TtC6Apollo23RedditListTableViewCell_h
@import Foundation;

@class UITableViewCell, _$sSSSg, _$sSo11UIImageViewCSg, _$sSo11UIStackViewC, _$sSo7UIImageCSg, _$sSo7UILabelCSg, _$sSo8UIButtonCSg;

@interface _TtC6Apollo23RedditListTableViewCell : UITableViewCell { // (Swift)
    /* instance variables */
    _$sSSSg redditTitle;
    _$sSSSg subtitle;
    _$sSo7UIImageCSg subredditIcon;
    _$sSo11UIImageViewCSg subredditIconImageView;
    _$sSo7UILabelCSg redditTitleLabel;
    _$sSo7UILabelCSg subtitleLabel;
    _$sSo11UIStackViewC textStackView;
    _$sSo11UIStackViewC mainStackView;
    _$sSo8UIButtonCSg accessoryButton;
}

/* instance methods */
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo23RedditListTableViewCell_h */
