//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo26ImgurDeletionTableViewCell_h
#define _TtC6Apollo26ImgurDeletionTableViewCell_h
@import Foundation;

@class UITableViewCell, _$s12CoreGraphics7CGFloatVMn, _$sSo11UIImageViewC, _$sSo7UILabelC, _$sSo8UIButtonC, pollo.ImgurUpload ?;

@interface _TtC6Apollo26ImgurDeletionTableViewCell : UITableViewCell { // (Swift)
    /* instance variables */
    _$sSo11UIImageViewC thumbnailImageView;
    _$sSo8UIButtonC deleteButton;
    _$sSo7UILabelC infoLabel;
    _$s12CoreGraphics7CGFloatVMn thumbnailVerticalPadding;
    _Atomic pollo.ImgurUpload ? imgurUpload;
}

/* instance methods */
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier;
- (id)initWithCoder:(id)coder;
- (void)setHighlighted:(_Bool)highlighted animated:(_Bool)animated;
- (void)setSelected:(_Bool)selected animated:(_Bool)animated;

@end

#endif /* _TtC6Apollo26ImgurDeletionTableViewCell_h */
