//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo11AppDelegate_h
#define _TtC6Apollo11AppDelegate_h
@import Foundation;

#include "SKProductsRequestDelegate-Protocol.h"
#include "UIApplicationDelegate-Protocol.h"
#include "UNUserNotificationCenterDelegate-Protocol.h"

@class Swift.Bool, UIResponder, _$sSS, _$sSSSg, _$sSaySSG, _$sSaySo9SKProductCGSg, _$sSayySSSg_ _$ss5ErrorMp _$sSgtc, _$sSo9SKProductCSg, pollo.ApolloTabBarController ?, pollo.Padlock ?, pollo.ThemeableWindow ?;

@interface _TtC6Apollo11AppDelegate : UIResponder <UNUserNotificationCenterDelegate, SKProductsRequestDelegate, UIApplicationDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.ThemeableWindow ? window;
    _Atomic pollo.ApolloTabBarController ? tabBarController;
    _$sSaySo9SKProductCGSg apolloProProducts;
    _$sSaySo9SKProductCGSg tipProducts;
    _$sSaySo9SKProductCGSg notificationProducts;
    _$sSo9SKProductCSg communityIconPackProduct;
    _$sSo9SKProductCSg spcaIconProduct;
    _$sSaySSG proAndTipProductIDs;
    _$sSS communityIconPackProductID;
    _$sSS spcaIconProductID;
    _$sSaySSG ultraProductIDs;
    Swift.Bool justUpdatedAppVersion;
    Swift.Bool hasShownTestFlightAlert;
    Swift.Bool justUpdatedAppBuildNumber;
    _$sSSSg apnsToken;
    _$sSayySSSg_ _$ss5ErrorMp _$sSgtc apnsFetchCompletions;
    Swift.Bool didEnterBackground;
    _Atomic pollo.Padlock ? padlock;
    Swift.Bool isOrientationLockedToPortrait;
}

/* instance methods */
- (void)productsRequest:(id)request didReceiveResponse:(id)response;
- (void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)token;
- (void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
- (void)userNotificationCenter:(id)center willPresentNotification:(id)notification withCompletionHandler:(id /* block */)handler;
- (void)userNotificationCenter:(id)center didReceiveNotificationResponse:(id)response withCompletionHandler:(id /* block */)handler;
- (void)userNotificationCenter:(id)center openSettingsForNotification:(id)notification;
- (unsigned long long)application:(id)application supportedInterfaceOrientationsForWindow:(id)window;
- (_Bool)application:(id)application didFinishLaunchingWithOptions:(id)options;
- (void)ubiquitousKeyValueStoreDidChangeExternallyWithNotification:(id)notification;
- (void)applicationDidEnterBackground:(id)background;
- (void)applicationProtectedDataDidBecomeAvailable:(id)available;
- (void)applicationProtectedDataWillBecomeUnavailable:(id)unavailable;
- (void)applicationWillEnterForeground:(id)foreground;
- (void)applicationWillTerminate:(id)terminate;
- (_Bool)application:(id)application openURL:(id)url options:(id)options;
- (id)init;

@end

#endif /* _TtC6Apollo11AppDelegate_h */
