//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo37WallpapersActionControllerPreviewView_h
#define _TtC6Apollo37WallpapersActionControllerPreviewView_h
@import Foundation;

@class UIVisualEffectView, _$s12CoreGraphics7CGFloatVMn, _$sSo11UIImageViewC, _$sSo7UILabelC;

@interface _TtC6Apollo37WallpapersActionControllerPreviewView : UIVisualEffectView { // (Swift)
    /* instance variables */
    _$sSo11UIImageViewC wallpaper1ImageView;
    _$sSo11UIImageViewC wallpaper2ImageView;
    _$sSo7UILabelC wallpaper1TitleLabel;
    _$sSo7UILabelC wallpaper2TitleLabel;
    _$s12CoreGraphics7CGFloatVMn imageTopSpacing;
    _$s12CoreGraphics7CGFloatVMn imageBottomSpacing;
    _$s12CoreGraphics7CGFloatVMn titleBottomSpacing;
    _$s12CoreGraphics7CGFloatVMn thumbnailHorizontalSpacing;
}

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)initWithEffect:(id)effect;

@end

#endif /* _TtC6Apollo37WallpapersActionControllerPreviewView_h */
