//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13BalloonMarker_h
#define _TtC6Apollo13BalloonMarker_h
@import Foundation;

@class _$s6Charts11MarkerImageCN, _$sSo18NSAttributedStringCSg, __C.CGSize, __C.UIEdgeInsets;

@interface _TtC6Apollo13BalloonMarker : _$s6Charts11MarkerImageCN { // (Swift)
    /* instance variables */
    __C.CGSize arrowSize;
    __C.UIEdgeInsets insets;
    __C.CGSize minimumSize;
    _$sSo18NSAttributedStringCSg labelAttributedString;
    __C.CGSize _labelSize;
}

/* instance methods */
- (struct CGPoint { double x0; double x1; })offsetForDrawingAtPoint:(struct CGPoint { double x0; double x1; })point;
- (void)drawWithContext:(struct CGContext *)context point:(struct CGPoint { double x0; double x1; })point;
- (void)refreshContentWithEntry:(id)entry highlight:(id)highlight;
- (id)init;

@end

#endif /* _TtC6Apollo13BalloonMarker_h */
