//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22ModQueueViewController_h
#define _TtC6Apollo22ModQueueViewController_h
@import Foundation;

#include "_TtC6Apollo21ASTableViewController.h"

@class _$sSSSg, _$sSaySo10RDKVotableCGSg, _$sSo13RDKPaginationCSg, _$sSo15UIBarButtonItemCSg, _$sSo16UIRefreshControlC, _$sSo8UIButtonC, pollo.ListAdapter, pollo.ModQueueContentType, pollo.ModQueueFilterNode ?, pollo.ModQueueType;

@interface _TtC6Apollo22ModQueueViewController : _TtC6Apollo21ASTableViewController { // (Swift)
    /* instance variables */
    _Atomic pollo.ModQueueType type;
    _$sSSSg subreddit;
    _Atomic pollo.ListAdapter listAdapter;
    _$sSo16UIRefreshControlC refreshControl;
    _$sSo8UIButtonC titleViewButton;
    _$sSo15UIBarButtonItemCSg filterBarButtonItem;
    _Atomic pollo.ModQueueFilterNode ? modQueueFilterNode;
    _Atomic pollo.ModQueueContentType contentType;
    _$sSo13RDKPaginationCSg currentPagination;
    _$sSaySo10RDKVotableCGSg queueItems;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)modQueueFilterNodeTapped;
- (void)titleViewButtonTappedWithSender:(id)sender;
- (void)refreshControlActivatedWithSender:(id)sender;

@end

#endif /* _TtC6Apollo22ModQueueViewController_h */
