//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22MessagesViewController_h
#define _TtC6Apollo22MessagesViewController_h
@import Foundation;

#include "UICollectionViewDataSource-Protocol.h"
#include "UICollectionViewDelegateFlowLayout-Protocol.h"

@class Swift.Bool, UIView, UIViewController, _$s10Foundation9IndexPathVMn ?, _$s12CoreGraphics7CGFloatVMn, pollo.MessageInputBar, pollo.MessagesCollectionView;

@interface _TtC6Apollo22MessagesViewController : UIViewController <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource> { // (Swift)
    /* instance variables */
    _Atomic pollo.MessagesCollectionView messagesCollectionView;
    _Atomic pollo.MessageInputBar messageInputBar;
    Swift.Bool scrollsToBottomOnKeyboardBeginsEditing;
    Swift.Bool maintainPositionOnKeyboardFrameChanged;
    _$s12CoreGraphics7CGFloatVMn additionalBottomInset;
    Swift.Bool isFirstLayout;
    Swift.Bool isMessagesControllerBeingDismissed;
    _$s10Foundation9IndexPathVMn ? selectedIndexPathForMenu;
    _$s12CoreGraphics7CGFloatVMn messageCollectionViewBottomInset;
}

@property (nonatomic, readonly) _Bool canBecomeFirstResponder;
@property (nonatomic, readonly) UIView *inputAccessoryView;
@property (nonatomic, readonly) _Bool shouldAutorotate;

/* instance methods */
- (void)menuControllerWillShow:(id)show;
- (void)handleTextViewDidBeginEditing:(id)editing;
- (void)handleKeyboardDidChangeState:(id)state;
- (void)adjustScrollViewTopInset;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (long long)numberOfSectionsInCollectionView:(id)view;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (id)collectionView:(id)view viewForSupplementaryElementOfKind:(id)kind atIndexPath:(id)path;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout sizeForItemAtIndexPath:(id)path;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout referenceSizeForHeaderInSection:(long long)section;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout referenceSizeForFooterInSection:(long long)section;
- (_Bool)collectionView:(id)view shouldShowMenuForItemAtIndexPath:(id)path;
- (_Bool)collectionView:(id)view canPerformAction:(SEL)action forItemAtIndexPath:(id)path withSender:(id)sender;
- (void)collectionView:(id)view performAction:(SEL)action forItemAtIndexPath:(id)path withSender:(id)sender;
- (void)clearMemoryCache;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo22MessagesViewController_h */
