//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo26LargePostOptionButtonsNode_h
#define _TtC6Apollo26LargePostOptionButtonsNode_h
@import Foundation;

@class ASDisplayNode, pollo.ApolloButtonNode, pollo.ApolloButtonNode ?, pollo.DualStateButtonNode;

@interface _TtC6Apollo26LargePostOptionButtonsNode : ASDisplayNode { // (Swift)
    /* instance variables */
    _Atomic pollo.DualStateButtonNode upvoteButton;
    _Atomic pollo.DualStateButtonNode downvoteButton;
    _Atomic pollo.ApolloButtonNode ? moderatorButton;
    _Atomic pollo.ApolloButtonNode moreOptionsButton;
}

/* instance methods */
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)init;

@end

#endif /* _TtC6Apollo26LargePostOptionButtonsNode_h */
