//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo12LogBuddyObjC_h
#define _TtC6Apollo12LogBuddyObjC_h
@import Foundation;

@class NSObject;

@interface _TtC6Apollo12LogBuddyObjC : NSObject // (Swift)

/* class methods */
+ (void)logWithString:(id)string;

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo12LogBuddyObjC_h */
