//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo27AutoModeratorViewController_h
#define _TtC6Apollo27AutoModeratorViewController_h
@import Foundation;

@class Swift.Bool, UIViewController, _$s12CoreGraphics7CGFloatVMn, _$sSS, _$sSo10UITextViewC, _$sSo15UIBarButtonItemC, _$sSo23UIActivityIndicatorViewC, _$sSo8UIButtonC;

@interface _TtC6Apollo27AutoModeratorViewController : UIViewController { // (Swift)
    /* instance variables */
    _$sSS subreddit;
    _$sSo8UIButtonC titleViewButton;
    _$sSo15UIBarButtonItemC cancelBarButtonItem;
    _$sSo15UIBarButtonItemC helpBarButtonItem;
    _$sSo15UIBarButtonItemC saveBarButtonItem;
    _$sSo23UIActivityIndicatorViewC spinner;
    _$sSo10UITextViewC textView;
    Swift.Bool changesHaveOccurred;
    _$s12CoreGraphics7CGFloatVMn keyboardHeight;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)cancelBarButtonItemTappedWithSender:(id)sender;
- (void)helpBarButtonItemTappedWithSender:(id)sender;
- (void)saveBarButtonItemTappedWithSender:(id)sender;
- (void)keyboardWillChangeFrameWithNotification:(id)notification;
- (void)styleTextView;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo27AutoModeratorViewController_h */
