//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21TipJar2ViewController_h
#define _TtC6Apollo21TipJar2ViewController_h
@import Foundation;

@class Swift.Bool, UIViewController, _$s12CoreGraphics7CGFloatVMn, _$sSS, _$sSaySo9SKProductCGSg, _$sSo11UIImageViewC, _$sSo23UIActivityIndicatorViewC, _$sSo6UIViewC, _$sSo7UILabelC, _$sSo7UILabelCSg, _$sSo8UIButtonC, _$sSo8UIButtonCSg, pollo.TipJar2ViewController.TipJarSummonLocation;

@interface _TtC6Apollo21TipJar2ViewController : UIViewController { // (Swift)
    /* instance variables */
    _$sSo6UIViewC interiorWrapperView;
    _$sSo11UIImageViewC iconImageView;
    _$sSo8UIButtonC closeButton;
    _$sSo7UILabelC titleLabel;
    _$sSo7UILabelC descriptionLabel;
    _$sSo7UILabelCSg footerLabel;
    _$s12CoreGraphics7CGFloatVMn iconImageViewOutset;
    _$s12CoreGraphics7CGFloatVMn iconSize;
    _$s12CoreGraphics7CGFloatVMn closeButtonDiameter;
    _$s12CoreGraphics7CGFloatVMn titleLabelTopSpacing;
    _$s12CoreGraphics7CGFloatVMn descriptionLabelTopSpacing;
    _$s12CoreGraphics7CGFloatVMn descriptionLabelSideSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonRowsSideSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsRowTopSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsRowVerticalSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsRowBottomSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsRowInnerTextSideSpacing;
    _$s12CoreGraphics7CGFloatVMn footerLabelRowsVerticalSpacing;
    _$s12CoreGraphics7CGFloatVMn footerLabelColumnsVerticalSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsColumnTopSpacing;
    _$s12CoreGraphics7CGFloatVMn buttonsColumnBottomSpacing;
    _$sSo7UILabelCSg tier1RowTipLabel;
    _$sSo7UILabelCSg tier2RowTipLabel;
    _$sSo7UILabelCSg tier3RowTipLabel;
    _$sSo8UIButtonCSg tier1TipRowButton;
    _$sSo8UIButtonCSg tier2TipRowButton;
    _$sSo8UIButtonCSg tier3TipRowButton;
    _$s12CoreGraphics7CGFloatVMn tipRowButtonHeight;
    _$sSS tier1ProductID;
    _$sSS tier3ProductID;
    _$sSS tier5ProductID;
    _$sSS tier10ProductID;
    _$sSS tier20ProductID;
    _$sSaySo9SKProductCGSg products;
    Swift.Bool transactionInProgress;
    _$sSo23UIActivityIndicatorViewC activityIndicator;
    _Atomic pollo.TipJar2ViewController.TipJarSummonLocation summonLocation;
}

@property (nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
@property (nonatomic, readonly) long long preferredInterfaceOrientationForPresentation;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)appear;
- (void)closeButtonTappedWithSender:(id)sender;
- (void)tier1TipLabelTappedWithTapGestureRecognizer:(id)recognizer;
- (void)tier2TipLabelTappedWithTapGestureRecognizer:(id)recognizer;
- (void)tier3TipLabelTappedWithTapGestureRecognizer:(id)recognizer;
- (void)footerLabelTappedWithTapGestureRecognizer:(id)recognizer;
- (void)tier1TipTappedWithSender:(id)sender;
- (void)tier2TipTappedWithSender:(id)sender;
- (void)tier3TipTappedWithSender:(id)sender;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo21TipJar2ViewController_h */
