//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo10ColorTheme_h
#define _TtC6Apollo10ColorTheme_h
@import Foundation;

#include "NSCoding-Protocol.h"

@class NSObject, _$sSS, _$sSaySo7UIColorCG, _$sSi;

@interface _TtC6Apollo10ColorTheme : NSObject <NSCoding> { // (Swift)
    /* instance variables */
    _$sSS name;
    _$sSi index;
    _$sSaySo7UIColorCG colors;
}

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)init;

@end

#endif /* _TtC6Apollo10ColorTheme_h */
