//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo39SettingsCommunityIconPackViewController_h
#define _TtC6Apollo39SettingsCommunityIconPackViewController_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "_TtC6Apollo25ApolloTableViewController.h"

@class pollo.AppIcon;

@interface _TtC6Apollo39SettingsCommunityIconPackViewController : _TtC6Apollo25ApolloTableViewController <UITableViewDataSource> { // (Swift)
    /* instance variables */
    _Atomic pollo.AppIcon currentAppIcon;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (double)tableView:(id)view heightForRowAtIndexPath:(id)path;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (id)tableView:(id)view titleForFooterInSection:(long long)section;

@end

#endif /* _TtC6Apollo39SettingsCommunityIconPackViewController_h */
