//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo24RemindMeInViewController_h
#define _TtC6Apollo24RemindMeInViewController_h
@import Foundation;

@class UIViewController, _$s12CoreGraphics7CGFloatVMn, _$sSS, _$sSo12UIDatePickerC, _$sSo7UILabelC, _$sSo8UIButtonC, pollo.RemindMeReminderType;

@interface _TtC6Apollo24RemindMeInViewController : UIViewController { // (Swift)
    /* instance variables */
    _Atomic pollo.RemindMeReminderType reminderType;
    _$sSS postTitle;
    _$sSo7UILabelC explanationLabel;
    _$s12CoreGraphics7CGFloatVMn explanationSideSpacing;
    _$sSo8UIButtonC chooseDateButton;
    _$sSo12UIDatePickerC datePicker;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)cancelBarButtonItemTappedWithSender:(id)sender;
- (void)addBarButtonItemTappedWithSender:(id)sender;
- (void)chooseDateButtonTappedWithSender:(id)sender;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo24RemindMeInViewController_h */
