//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21MediaViewerController_h
#define _TtC6Apollo21MediaViewerController_h
@import Foundation;

#include "UICollisionBehaviorDelegate-Protocol.h"
#include "UIGestureRecognizerDelegate-Protocol.h"
#include "UIScrollViewDelegate-Protocol.h"

@class Swift.Bool, UIViewController, _$s10Foundation3URLVMn ?, _$s10Foundation4DateVMn ?, _$s12CoreGraphics7CGFloatVMn, _$s12CoreGraphics7CGFloatVMn ?, _$sSSSg, _$sSa -> Apollo.DatedRotationData, _$sSd, _$sSdSg, _$sSf, _$sSfSg, _$sSi, _$sSo10ASTextNodeCSg, _$sSo12AVPlayerItemCSg, _$sSo12GradientViewCSg, _$sSo12SMScrollViewCSg, _$sSo12UIScrollViewCSg, _$sSo15CMMotionManagerCSg, _$sSo19FLAnimatedImageViewCSg, _$sSo22UIPanGestureRecognizerCSg, _$sSo22UITapGestureRecognizerCSg, _$sSo23UIActivityIndicatorViewCSg, _$sSo27PINRemoteImageManagerResultCSg, _$sSo28AVPictureInPictureControllerCSg, _$sSo28UILongPressGestureRecognizerCSg, _$sSo6UIViewC, _$sSo7UIImageCSg, _$sSo7UILabelCSg, _$sSo8AVPlayerCSg, _$sSo8UIButtonCSg, _$sypSg, _$syycSg, __C.CGPoint ?, __C.CGSize ?, __C.CGVector ?, __C.UIInterfaceOrientation ?, pollo.DatedRotationData ?, pollo.MediaPageViewController ?, pollo.MediaViewerController.MediaViewerVideoInfoLoadingStatus, pollo.PlayerLayerContainerView ?, pollo.RotationOfferingButton ?, pollo.VideoControlsView ?, pollo.VideoGIFProgressView ?, pollo.VideoResourceLoader ?;

@interface _TtC6Apollo21MediaViewerController : UIViewController <UIScrollViewDelegate, UIGestureRecognizerDelegate, UICollisionBehaviorDelegate> { // (Swift)
    /* instance variables */
    _$sypSg _imageAnalysisInteraction;
    _$sSi index;
    _$s10Foundation3URLVMn ? url;
    _$sSSSg contentTypeHint;
    _$sSdSg gifTimeOffset;
    Swift.Bool doNotUnpauseFromNextNotification;
    _$sSSSg albumTitle;
    _$sSSSg albumCaption;
    _$s10Foundation3URLVMn ? albumOutboundURL;
    _$sSo7UIImageCSg thumbnailImage;
    _Atomic pollo.MediaPageViewController ? parentMediaPageViewController;
    _$sSd hideControlsAfter;
    _$s10Foundation4DateVMn ? lastPlayerInteraction;
    _$sSo6UIViewC wrapperView;
    _$sSo12SMScrollViewCSg scrollView;
    _$sSo19FLAnimatedImageViewCSg imageView;
    _$sSo12GradientViewCSg lowerGradientView;
    _$sSo22UITapGestureRecognizerCSg darkGradientTapGestureRecognizer;
    _$sSo22UITapGestureRecognizerCSg twoFingerTapGestureRecognizer;
    _$sSo22UITapGestureRecognizerCSg threeFingerTapGestureRecognizer;
    _$sSo12UIScrollViewCSg titleCaptionWrapperScrollView;
    _$sSo7UILabelCSg titleLabel;
    _$sSo10ASTextNodeCSg captionTextNode;
    _$sSo28UILongPressGestureRecognizerCSg longPressGestureRecognizer;
    _$sSo22UIPanGestureRecognizerCSg panGestureRecognizer;
    _$sSo22UIPanGestureRecognizerCSg scrubPanGestureRecognizer;
    Swift.Bool isUsingPlaybackAudioSession;
    _$sSo8AVPlayerCSg player;
    _Atomic pollo.PlayerLayerContainerView ? playerLayerContainerView;
    _$s12CoreGraphics7CGFloatVMn gifPlausePlayButtonWidth;
    _$sSo8UIButtonCSg gifPlayPauseButton;
    _$sSfSg videoPlaybackSpeed;
    _Atomic pollo.VideoGIFProgressView ? videoGIFProgressView;
    _$sypSg timeObserverToken;
    _Atomic pollo.VideoControlsView ? videoControlsView;
    Swift.Bool doNotUpdateVideoPositionSlider;
    _$sSo15CMMotionManagerCSg motionManager;
    _$sSo23UIActivityIndicatorViewCSg activityIndicator;
    _Atomic pollo.RotationOfferingButton ? $__lazy_storage_$_rotationOfferingButton;
    Swift.Bool laidOut;
    _$sSo27PINRemoteImageManagerResultCSg downloadedImageResult;
    Swift.Bool dismissingFromFlick;
    _$s12CoreGraphics7CGFloatVMn extraGradientHeight;
    _Atomic pollo.VideoResourceLoader ? loader;
    _$sSo28AVPictureInPictureControllerCSg pictureInPictureController;
    _$sSo8UIButtonCSg goodbyeButton;
    Swift.Bool keepRotationOfferingButtonHiddenUntilNextRotation;
    __C.UIInterfaceOrientation ? concludedCoreMotionOrientation;
    __C.CGPoint ? startingRotationOfferingButtonPoint;
    _$sSa -> Apollo.DatedRotationData trackedRotationData;
    _Atomic pollo.DatedRotationData ? $__lazy_storage_$_mostRecentSystemRotationData;
    Swift.Bool videoWasPlayingWhenEnteringBackground;
    _$s12CoreGraphics7CGFloatVMn ? imageDownloadingProgress;
    Swift.Bool temporaryThumbnailImageBeingDownloaded;
    __C.CGSize ? laidOutForSize;
    Swift.Bool fullImageAnalysisStarted;
    Swift.Bool hasDeterminedTracks;
    Swift.Bool captionExpanded;
    Swift.Bool captionExpanding;
    _Atomic pollo.MediaViewerController.MediaViewerVideoInfoLoadingStatus videoInfoLoadingStatus;
    _$s12CoreGraphics7CGFloatVMn ? distanceToTraverse;
    __C.CGSize ? initialZoomViewSize;
    __C.CGPoint ? initialZoomViewOrigin;
    __C.CGVector ? touchOffsetFromCenter;
    _$sSd initialSeconds;
    _$sSf initialRate;
    Swift.Bool seekInProgress;
    _$sSdSg mediaStartPlayingTime;
    Swift.Bool beganPlaying;
    _$sSo12AVPlayerItemCSg currentItemWithTracksObserver;
    _$syycSg imageDownloadCompletionHandler;
}

@property (nonatomic, readonly) _Bool prefersStatusBarHidden;
@property (nonatomic, readonly) _Bool shouldAutorotate;
@property (nonatomic, readonly) unsigned long long supportedInterfaceOrientations;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (void)viewDidLoad;
- (void)goodbyeWallpaperButtonTappedWithSender:(id)sender;
- (void)rotationOfferingButtonPannedWithPanGestureRecognizer:(id)recognizer;
- (void)rotationOfferingButtonTappedWithSender:(id)sender;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewWillTransitionToSize:(struct CGSize { double x0; double x1; })size withTransitionCoordinator:(id)coordinator;
- (void)sceneDidEnterBackgroundWithNotification:(id)notification;
- (void)sceneWillEnterForegroundWithNotification:(id)notification;
- (void)applicationDidEnterBackgroundWithNotification:(id)notification;
- (void)applicationWillEnterForegroundWithNotification:(id)notification;
- (void)videoGIFTimeIntervalUpdatedWithNotification:(id)notification;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (_Bool)gestureRecognizerShouldBegin:(id)begin;
- (_Bool)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)recognizer;
- (void)scrollViewLongPressed:(id)pressed;
- (void)scrollViewTapped:(id)tapped;
- (void)scrollViewTwoFingerTapped:(id)tapped;
- (void)scrollViewThreeFingerTapped:(id)tapped;
- (void)captionTextNodeTappedWithSender:(id)sender;
- (void)darkGradientTappedWithGestureRecognizer:(id)recognizer;
- (void)scrollViewPanned:(id)panned;
- (void)scrollViewScrubbed:(id)scrubbed;
- (id)viewForZoomingInScrollView:(id)view;
- (void)scrollViewDidZoom:(id)zoom;
- (void)scrollViewDidEndZooming:(id)zooming withView:(id)view atScale:(double)scale;
- (void)pauseAllAVPlayersNotificationReceivedWithNotification:(id)notification;
- (void)unpauseAllAVPlayersNotificationReceivedWithNotification:(id)notification;
- (void)didPlayToEndOfVideoNotificationReceivedWithNotification:(id)notification;
- (void)gifPlayPauseButtonTappedWithSender:(id)sender;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo21MediaViewerController_h */
