//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo15WikipediaClient_h
#define _TtC6Apollo15WikipediaClient_h
@import Foundation;

@class DispatchQueue, _$sSD -> Apollo.WikipediaMetadata Apollo.WikipediaPreview, _TtCs12_SwiftObject;

@interface _TtC6Apollo15WikipediaClient : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    DispatchQueue dispatchQueue;
    _$sSD -> Apollo.WikipediaMetadata Apollo.WikipediaPreview cache;
}

@end

#endif /* _TtC6Apollo15WikipediaClient_h */
