//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22SettingsViewController_h
#define _TtC6Apollo22SettingsViewController_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "_TtC6Apollo25ApolloTableViewController.h"

@class _$sSa -> Apollo.SettingsViewController.MainSetting, _$sSbSg, _$sSiSg, _$sSo7RDKLinkCSg, pollo.ApolloWallpaperSetInfo ?, pollo.SettingsAnnouncement ?;

@interface _TtC6Apollo22SettingsViewController : _TtC6Apollo25ApolloTableViewController <UITableViewDataSource> { // (Swift)
    /* instance variables */
    _$sSiSg numberOfReviewsForCurrentVersion;
    _$sSa -> Apollo.SettingsViewController.MainSetting mainSettings;
    _$sSbSg $__lazy_storage_$_biometricsCapable;
    _$sSo7RDKLinkCSg betaStickyLink;
    _Atomic pollo.SettingsAnnouncement ? announcement;
    _Atomic pollo.ApolloWallpaperSetInfo ? wallpaperSetInfo;
}

@property (nonatomic, readonly) long long preferredStatusBarStyle;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)wallpapersBarButtonItemTappedWithSender:(id)sender;
- (void)exportBarButtonItemTappedWithSender:(id)sender;
- (void)footerButtonTappedWithSender:(id)sender;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewDidAppear:(_Bool)appear;
- (void)announcementHeaderTappedWithSender:(id)sender;
- (void)sharePlayEligibleStateUpdated:(id)updated;
- (void)didReceiveMemoryWarning;
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view viewForFooterInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (double)tableView:(id)view heightForFooterInSection:(long long)section;
- (void)tableView:(id)view willDisplayFooterView:(id)view forSection:(long long)section;

@end

#endif /* _TtC6Apollo22SettingsViewController_h */
