//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo17ShareMediaManager_h
#define _TtC6Apollo17ShareMediaManager_h
@import Foundation;

#include "NSURLSessionDownloadDelegate-Protocol.h"

@class NSObject, Swift.Bool, _$s10Foundation3URLVMn ?, _$s12CoreGraphics7CGFloatVMn ?, _$sSSSg, _$sSi, _$sSo12NSURLSessionCSg, _$sSo16UIViewControllerCSgXw, _$sSo24NSURLSessionDownloadTaskCSg, pollo.PreparingShareProgressView ?, pollo.ShareMediaManagerShareType ?;

@interface _TtC6Apollo17ShareMediaManager : NSObject <NSURLSessionDownloadDelegate> { // (Swift)
    /* instance variables */
    _$sSo12NSURLSessionCSg videoDownloadSession;
    Swift.Bool isDownloadingAudioSeparately;
    Swift.Bool isDownloadingGIF;
    _$s10Foundation3URLVMn ? downloadedAudioLocation;
    _$s10Foundation3URLVMn ? downloadedVideoLocation;
    _$sSo24NSURLSessionDownloadTaskCSg audioDownloadTask;
    _$sSo24NSURLSessionDownloadTaskCSg videoDownloadTask;
    _$s12CoreGraphics7CGFloatVMn ? currentAudioDownloadProgress;
    _$s12CoreGraphics7CGFloatVMn ? currentVideoDownloadProgress;
    _$sSi bytesThresholdForVideo;
    _$sSi upperLimitByteThresholdForGIF;
    _Atomic pollo.ShareMediaManagerShareType ? shareType;
    _$s10Foundation3URLVMn ? alternativeRemoteURL;
    _$sSSSg shareTitle;
    _$s10Foundation3URLVMn ? albumURL;
    _$sSo16UIViewControllerCSgXw viewController;
    _Atomic pollo.PreparingShareProgressView ? progressView;
    _$sSo16UIViewControllerCSgXw wallpaperSavingViewController;
    Swift.Bool audioDownloadFailed;
    Swift.Bool videoDownloadFailed;
}

/* instance methods */
- (id)init;
- (void)image:(id)image didFinishSavingWithError:(id)error contextInfo:(void *)info;
- (void)video:(id)video didFinishSavingWithError:(id)error contextInfo:(void *)info;
- (void)URLSession:(id)urlsession downloadTask:(id)task didFinishDownloadingToURL:(id)url;
- (void)URLSession:(id)urlsession downloadTask:(id)task didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
- (void)URLSession:(id)urlsession task:(id)task didCompleteWithError:(id)error;

@end

#endif /* _TtC6Apollo17ShareMediaManager_h */
