//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo16ReadPostsTracker_h
#define _TtC6Apollo16ReadPostsTracker_h
@import Foundation;

@class DispatchQueue, _$sSi, _$sSo12NSMutableSetC, _$sSo19NSMutableOrderedSetC, _TtCs12_SwiftObject, __C.UIBackgroundTaskIdentifier;

@interface _TtC6Apollo16ReadPostsTracker : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSi maximumTotal;
    _$sSo19NSMutableOrderedSetC readPostIDs;
    _$sSo12NSMutableSetC postIDsSavedSinceLastSync;
    DispatchQueue dispatchQueue;
    _$sSo19NSMutableOrderedSetC readItemsToBatchToRedditToHide;
    __C.UIBackgroundTaskIdentifier backgroundTaskID;
}

@end

#endif /* _TtC6Apollo16ReadPostsTracker_h */
