//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo11ListAdapter_h
#define _TtC6Apollo11ListAdapter_h
@import Foundation;

@class NSObject, _$s12CoreGraphics7CGFloatVMn ?, _$sSD -> _$s10Foundation9IndexPathVMn Apollo.SectionController, _$sSD -> _$ss11AnyHashableVMn _$s10Foundation9IndexPathVMn, _$sSa -> _$ss11AnyHashableVMn, _$sSo11ASTableNodeCSgXw, _$sSo16UIViewControllerCSgXw, _$sSo6UIViewCSg, pollo.ListAdapterDataSource ?, pollo.ListAdapterDelegate ?, pollo.ListAdapterScrollingDelegate ?;

@interface _TtC6Apollo11ListAdapter : NSObject { // (Swift)
    /* instance variables */
    _$sSo16UIViewControllerCSgXw viewController;
    _Atomic pollo.ListAdapterDataSource ? dataSource;
    _Atomic pollo.ListAdapterDelegate ? delegate;
    _Atomic pollo.ListAdapterScrollingDelegate ? scrollingDelegate;
    _$sSa -> _$ss11AnyHashableVMn objects;
    _$sSD -> _$ss11AnyHashableVMn _$s10Foundation9IndexPathVMn objectToIndexPathMapping;
    _$sSD -> _$s10Foundation9IndexPathVMn Apollo.SectionController indexPathToSectionControllerMapping;
    _$sSo6UIViewCSg emptyView;
    _$sSo11ASTableNodeCSgXw tableNode;
    _$s12CoreGraphics7CGFloatVMn ? scrollOffsetAtStartOfDrag;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo11ListAdapter_h */
