//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo29MoreCommentsSectionController_h
#define _TtC6Apollo29MoreCommentsSectionController_h
@import Foundation;

#include "_TtC6Apollo17SectionController.h"

@class NSString, Swift.Bool, _$sSS, _$sSiSg, _$sSo15RDKMoreCommentsC, pollo.MoreCommentsSectionControllerDelegate ?;

@interface _TtC6Apollo29MoreCommentsSectionController : _TtC6Apollo17SectionController { // (Swift)
    /* instance variables */
    _$sSo15RDKMoreCommentsC moreComments;
    _Atomic pollo.MoreCommentsSectionControllerDelegate ? delegate;
    _$sSS postID;
    Swift.Bool isLast;
    _$sSiSg numberOfRepliesDeleted;
}

@property (nonatomic, readonly) NSString *debugDescription;
@property (nonatomic, readonly) NSString *description;

/* instance methods */
- (void)modelObjectUpdatedNotificationReceived:(id)received;
- (id)init;

@end

#endif /* _TtC6Apollo29MoreCommentsSectionController_h */
