//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21EnableInstructionView_h
#define _TtC6Apollo21EnableInstructionView_h
@import Foundation;

@class UIView, _$s12CoreGraphics7CGFloatVMn, _$sSo11UIImageViewC, _$sSo7UILabelC, pollo.EnableInstruction;

@interface _TtC6Apollo21EnableInstructionView : UIView { // (Swift)
    /* instance variables */
    _Atomic pollo.EnableInstruction instruction;
    _$sSo11UIImageViewC icon;
    _$sSo7UILabelC label;
    _$s12CoreGraphics7CGFloatVMn iconToLabelSpacing;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;

@end

#endif /* _TtC6Apollo21EnableInstructionView_h */
