//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23ChangelogViewController_h
#define _TtC6Apollo23ChangelogViewController_h
@import Foundation;

@class UIViewController, _$sSaySo9SKProductCGSg, _$sSo16UIViewControllerCSg, pollo.ChangelogSummonLocation, pollo.ChangelogTipJarStatusModel;

@interface _TtC6Apollo23ChangelogViewController : UIViewController { // (Swift)
    /* instance variables */
    _$sSo16UIViewControllerCSg $__lazy_storage_$_hostingController;
    _Atomic pollo.ChangelogSummonLocation summonLocation;
    _Atomic pollo.ChangelogTipJarStatusModel tipJarStatusModel;
    _$sSaySo9SKProductCGSg tipProducts;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo23ChangelogViewController_h */
