//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo32SavedPostsCommentsViewController_h
#define _TtC6Apollo32SavedPostsCommentsViewController_h
@import Foundation;

#include "_TtC6Apollo21ASTableViewController.h"

@class _$sSSSg, _$sSaySo8RDKThingCGSg, _$sSo13RDKPaginationCSg, _$sSo15UIBarButtonItemC, pollo.ApolloRefreshControl, pollo.DualLabelTitleButton, pollo.ListAdapter;

@interface _TtC6Apollo32SavedPostsCommentsViewController : _TtC6Apollo21ASTableViewController { // (Swift)
    /* instance variables */
    _$sSSSg filteredSaveCategory;
    _Atomic pollo.ListAdapter listAdapter;
    _Atomic pollo.ApolloRefreshControl refreshControl;
    _$sSo15UIBarButtonItemC savedCategoriesBarButtonItem;
    _$sSaySo8RDKThingCGSg savedPostsComments;
    _$sSo13RDKPaginationCSg currentPagination;
    _$sSaySo8RDKThingCGSg savedDatabaseItems;
    _Atomic pollo.DualLabelTitleButton dualTitleButton;
    _$sSSSg searchQuery;
    _$sSaySo8RDKThingCGSg filteredResults;
}

/* instance methods */
- (void)scrollViewWillBeginDragging:(id)dragging;
- (void)scrollViewDidScroll:(id)scroll;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(_Bool)decelerate;
- (id)initWithCoder:(id)coder;
- (void)titleViewTappedWithSender:(id)sender;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewDidAppear:(_Bool)appear;
- (void)refreshControlActivatedWithSender:(id)sender;
- (void)savedCategoriesButtonTappedWithSender:(id)sender;
- (_Bool)textFieldShouldBeginEditing:(id)editing;

@end

#endif /* _TtC6Apollo32SavedPostsCommentsViewController_h */
