//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13IntentHandler_h
#define _TtC6Apollo13IntentHandler_h
@import Foundation;

#include "JumbopolloIntentHandling-Protocol.h"

@class INExtension;

@interface _TtC6Apollo13IntentHandler : INExtension <JumbopolloIntentHandling> // (Swift)

/* instance methods */
- (void)provideIconOptionsCollectionForJumbopollo:(id)jumbopollo withCompletion:(id /* block */)completion;
- (id)defaultIconForJumbopollo:(id)jumbopollo;
- (id)init;

@end

#endif /* _TtC6Apollo13IntentHandler_h */
