//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo15MessageInputBar_h
#define _TtC6Apollo15MessageInputBar_h
@import Foundation;

@class Swift.Bool, UIView, _$s12CoreGraphics7CGFloatVMn, _$sSa -> Apollo.InputItem, _$sSa -> Apollo.InputPlugin, _$sSo18NSLayoutConstraintCSg, _$sSo18UIVisualEffectViewC, _$sSo6UIViewC, __C.CGSize ?, __C.UIEdgeInsets, pollo.InputBarButtonItem, pollo.InputStackView, pollo.InputTextView ?, pollo.MessageInputBarDelegate ?, pollo.NSLayoutConstraintSet ?, pollo.SeparatorLine;

@interface _TtC6Apollo15MessageInputBar : UIView { // (Swift)
    /* instance variables */
    _Atomic pollo.MessageInputBarDelegate ? delegate;
    _$sSo6UIViewC backgroundView;
    _$sSo6UIViewC contentView;
    _$sSo18UIVisualEffectViewC blurView;
    Swift.Bool isTranslucent;
    _Atomic pollo.SeparatorLine separatorLine;
    _Atomic pollo.InputStackView topStackView;
    _Atomic pollo.InputStackView leftStackView;
    _Atomic pollo.InputStackView rightStackView;
    _Atomic pollo.InputStackView bottomStackView;
    _Atomic pollo.InputTextView ? $__lazy_storage_$_inputTextView;
    _Atomic pollo.InputBarButtonItem sendButton;
    __C.UIEdgeInsets padding;
    __C.UIEdgeInsets topStackViewPadding;
    __C.UIEdgeInsets textViewPadding;
    __C.CGSize ? previousIntrinsicContentSize;
    __C.CGSize ? $__lazy_storage_$_cachedIntrinsicContentSize;
    Swift.Bool isOverMaxTextViewHeight;
    Swift.Bool shouldForceTextViewMaxHeight;
    Swift.Bool shouldAutoUpdateMaxTextViewHeight;
    _$s12CoreGraphics7CGFloatVMn maxTextViewHeight;
    Swift.Bool shouldManageSendButtonEnabledState;
    _$s12CoreGraphics7CGFloatVMn leftStackViewWidthConstant;
    _$s12CoreGraphics7CGFloatVMn rightStackViewWidthConstant;
    _$sSa -> Apollo.InputPlugin plugins;
    _$sSa -> Apollo.InputItem leftStackViewItems;
    _$sSa -> Apollo.InputItem rightStackViewItems;
    _$sSa -> Apollo.InputItem bottomStackViewItems;
    _$sSa -> Apollo.InputItem topStackViewItems;
    _$sSa -> Apollo.InputItem nonStackViewItems;
    _Atomic pollo.NSLayoutConstraintSet ? textViewLayoutSet;
    _$sSo18NSLayoutConstraintCSg textViewHeightAnchor;
    _Atomic pollo.NSLayoutConstraintSet ? topStackViewLayoutSet;
    _Atomic pollo.NSLayoutConstraintSet ? leftStackViewLayoutSet;
    _Atomic pollo.NSLayoutConstraintSet ? rightStackViewLayoutSet;
    _Atomic pollo.NSLayoutConstraintSet ? bottomStackViewLayoutSet;
    _Atomic pollo.NSLayoutConstraintSet ? contentViewLayoutSet;
    _$sSo18NSLayoutConstraintCSg windowAnchor;
    _$sSo18NSLayoutConstraintCSg backgroundViewBottomAnchor;
}

@property (nonatomic, readonly) struct CGSize { double x0; double x1; } intrinsicContentSize;
@property (nonatomic, readonly) _Bool canBecomeFirstResponder;

/* instance methods */
- (id)init;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)invalidateIntrinsicContentSize;
- (void)traitCollectionDidChange:(id)change;
- (void)orientationDidChange;
- (void)inputTextViewDidChange;
- (void)inputTextViewDidBeginEditing;
- (void)inputTextViewDidEndEditing;

@end

#endif /* _TtC6Apollo15MessageInputBar_h */
