//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22CommentPostContextNode_Apollo_h
#define _TtC6Apollo22CommentPostContextNode_Apollo_h
@import Foundation;

@interface _TtC6Apollo22CommentPostContextNode (Apollo) // (Swift)

/* instance methods */
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;

@end

#endif /* _TtC6Apollo22CommentPostContextNode_Apollo_h */
