//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo29SettingsFiltersViewController_h
#define _TtC6Apollo29SettingsFiltersViewController_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "_TtC6Apollo25ApolloTableViewController.h"

@class _$sSa -> Apollo.SettingsFiltersViewController.FilterType, _$sSo16UIRefreshControlCSg, _$sSo9RDKClientCSg;

@interface _TtC6Apollo29SettingsFiltersViewController : _TtC6Apollo25ApolloTableViewController <UITableViewDataSource> { // (Swift)
    /* instance variables */
    _$sSa -> Apollo.SettingsFiltersViewController.FilterType filterTypes;
    _$sSo9RDKClientCSg temporaryPostingAccount;
    _$sSo16UIRefreshControlCSg refreshControl;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)redditAccountChangedWithNotification:(id)notification;
- (void)keywordFiltersChangedWithNotification:(id)notification;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidLayoutSubviews;
- (void)setEditing:(_Bool)editing animated:(_Bool)animated;
- (long long)numberOfSectionsInTableView:(id)view;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (id)tableView:(id)view viewForHeaderInSection:(long long)section;
- (id)tableView:(id)view viewForFooterInSection:(long long)section;
- (_Bool)tableView:(id)view canEditRowAtIndexPath:(id)path;
- (_Bool)tableView:(id)view canMoveRowAtIndexPath:(id)path;
- (void)tableView:(id)view commitEditingStyle:(long long)style forRowAtIndexPath:(id)path;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)path;
- (void)refreshControlActivated:(id)activated;
- (void)accountSwitcherTitleButtonTapped:(id)tapped;
- (void)longPressedTableViewWithGestureRecognizer:(id)recognizer;

@end

#endif /* _TtC6Apollo29SettingsFiltersViewController_h */
