//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo33ModeratorMutedUsersViewController_h
#define _TtC6Apollo33ModeratorMutedUsersViewController_h
@import Foundation;

#include "ASTableDataSource-Protocol.h"
#include "ASTableDelegate-Protocol.h"

@class ASDKViewController, _$sSDySSSDySSypGGSg, _$sSS, _$sSaySDySSypGGSg, _$sSiSg, _$sSo11ASTableNodeC, _$sSo23UIActivityIndicatorViewC, _$sSo7UILabelC, _$sSo8UIButtonC;

@interface _TtC6Apollo33ModeratorMutedUsersViewController : ASDKViewController <ASTableDataSource, ASTableDelegate> { // (Swift)
    /* instance variables */
    _$sSS subreddit;
    _$sSo11ASTableNodeC tableNode;
    _$sSaySDySSypGGSg mutedUsers;
    _$sSiSg after;
    _$sSDySSSDySSypGGSg posts;
    _$sSDySSSDySSypGGSg comments;
    _$sSo8UIButtonC userButton;
    _$sSo8UIButtonC addButton;
    _$sSo23UIActivityIndicatorViewC spinner;
    _$sSo7UILabelC emptyLabel;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (id /* block */)tableNode:(id)node nodeBlockForRowAtIndexPath:(id)path;
- (long long)numberOfSectionsInTableNode:(id)node;
- (long long)tableNode:(id)node numberOfRowsInSection:(long long)section;
- (void)tableNode:(id)node didSelectRowAtIndexPath:(id)path;
- (_Bool)shouldBatchFetchForTableNode:(id)node;
- (void)tableNode:(id)node willBeginBatchFetchWithContext:(id)context;
- (void)userButtonTappedWithSender:(id)sender;
- (void)addButtonTappedWithSender:(id)sender;
- (id)initWithNode:(id)node;
- (id)init;

@end

#endif /* _TtC6Apollo33ModeratorMutedUsersViewController_h */
