//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo15CommentCellNode_h
#define _TtC6Apollo15CommentCellNode_h
@import Foundation;

@class ASCellNode, NSString, Swift.Bool, UIView, _$sSSSg, _$sSa -> Apollo.LinkButtonNode, _$sSo10ASTextNodeC, _$sSo10RDKCommentC, _$sSo11ASImageNodeC, _$sSo11ASImageNodeCSg, _$sSo13ASDisplayNodeC, pollo.ApolloButtonNode, pollo.ApolloButtonNode ?, pollo.AwardsNode ?, pollo.CommentCellActionDelegate ?, pollo.CommentPostContextNode ?, pollo.CompactModOptionsNode ?, pollo.FlairNode ?, pollo.InlineModeratorBannerNode ?, pollo.MarkdownNode, pollo.ShowingInPreviewType ?;

@interface _TtC6Apollo15CommentCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _$sSo10RDKCommentC comment;
    Swift.Bool showPostContext;
    _$sSSSg postAuthor;
    Swift.Bool isLinkedToComment;
    Swift.Bool isInModQueue;
    Swift.Bool censorUsername;
    _Atomic pollo.ShowingInPreviewType ? commentPreviewType;
    Swift.Bool limitLength;
    _$sSo13ASDisplayNodeC depthIndicatorNode;
    _$sSo11ASImageNodeCSg stickyIndicatorNode;
    _Atomic pollo.ApolloButtonNode authorNode;
    _$sSo11ASImageNodeCSg cakedayNode;
    _Atomic pollo.ApolloButtonNode ? sharePlayNode;
    _Atomic pollo.ApolloButtonNode pointsNode;
    _Atomic pollo.ApolloButtonNode ? editedIndicatorNode;
    _Atomic pollo.AwardsNode ? awardsNode;
    _$sSo11ASImageNodeCSg lockedNode;
    _Atomic pollo.ApolloButtonNode ? moreOptionsNode;
    _$sSo10ASTextNodeC ageNode;
    _$sSo11ASImageNodeC collapseDisclosureIndicator;
    _$sSo10ASTextNodeC totalCollapsedChildrenIndicator;
    _Atomic pollo.MarkdownNode bodyNode;
    _$sSa -> Apollo.LinkButtonNode linkButtonNodes;
    _Atomic pollo.CommentPostContextNode ? postContextNode;
    _$sSo11ASImageNodeC savedIndicatorNode;
    _Atomic pollo.InlineModeratorBannerNode ? moderatorBannerNode;
    _Atomic pollo.FlairNode ? flairNode;
    _Atomic pollo.CompactModOptionsNode ? modOptionsNode;
    _Atomic pollo.ApolloButtonNode ? moderatorButton;
    _Atomic pollo.CommentCellActionDelegate ? actionDelegate;
}

@property (nonatomic) _Bool highlighted;
@property (nonatomic) _Bool selected;
@property (nonatomic, retain) UIView *selectedBackgroundView;
@property (nonatomic, copy) NSString *accessibilityLabel;

/* instance methods */
- (_Bool)isHighlighted;
- (_Bool)isSelected;
- (void)didLoad;
- (void)didEnterPreloadState;
- (void)calculatedLayoutDidChange;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo15CommentCellNode_h */
