//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23VideoGifProgressShouter_h
#define _TtC6Apollo23VideoGifProgressShouter_h
@import Foundation;

@class _$sSD -> _$s10Foundation3URLVMn _$sSd, _$sSS, _$sSd, _$sSo20NSNotificationCenterC, _TtCs12_SwiftObject;

@interface _TtC6Apollo23VideoGifProgressShouter : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo20NSNotificationCenterC notificationCenter;
    _$sSS notificationNamePrefix;
    _$sSD -> _$s10Foundation3URLVMn _$sSd mostRecentPostTimestampForURL;
    _$sSd minimumTimeDifferentBetweenNotifications;
}

@end

#endif /* _TtC6Apollo23VideoGifProgressShouter_h */
