//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo30LiveActivityTestViewController_h
#define _TtC6Apollo30LiveActivityTestViewController_h
@import Foundation;

@class UIViewController, _$sSo8UIButtonC;

@interface _TtC6Apollo30LiveActivityTestViewController : UIViewController { // (Swift)
    /* instance variables */
    _$sSo8UIButtonC ebutton;
}

/* instance methods */
- (void)viewDidLoad;
- (void)buttonTappedWithSender:(id)sender;
- (void)endButtonTappedWithSender:(id)sender;
- (void)notifeeWithNotification:(id)notification;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo30LiveActivityTestViewController_h */
