//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo34AllSubredditCommentsViewController_h
#define _TtC6Apollo34AllSubredditCommentsViewController_h
@import Foundation;

@class ASDKViewController, _$sSS, _$sSaySo10RDKCommentCG, _$sSo11ASTableNodeC, _$sSo13RDKPaginationC, _$sSo16UIRefreshControlC, pollo.ListAdapter;

@interface _TtC6Apollo34AllSubredditCommentsViewController : ASDKViewController { // (Swift)
    /* instance variables */
    _$sSS subreddit;
    _$sSaySo10RDKCommentCG comments;
    _$sSo13RDKPaginationC currentPagination;
    _$sSo11ASTableNodeC tableNode;
    _Atomic pollo.ListAdapter listAdapter;
    _$sSo16UIRefreshControlC refreshControl;
}

@property (nonatomic, readonly) long long preferredStatusBarStyle;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)refreshControlActivatedWithSender:(id)sender;
- (id)initWithNode:(id)node;
- (id)init;

@end

#endif /* _TtC6Apollo34AllSubredditCommentsViewController_h */
