//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo27ModeratorLogsViewController_h
#define _TtC6Apollo27ModeratorLogsViewController_h
@import Foundation;

#include "_TtC6Apollo21ASTableViewController.h"

@class _$sSSSg, _$sSaySSGSg, _$sSaySo18RDKModeratorActionCGSg, _$sSo13RDKPaginationCSg, _$sSo15UIBarButtonItemC, _$sSo16UIRefreshControlC, _$sSo8UIButtonC, pollo.ListAdapter, pollo.ModLogsFilterNode, pollo.ModeratorLogAction ?;

@interface _TtC6Apollo27ModeratorLogsViewController : _TtC6Apollo21ASTableViewController { // (Swift)
    /* instance variables */
    _$sSSSg subreddit;
    _Atomic pollo.ListAdapter listAdapter;
    _$sSo16UIRefreshControlC refreshControl;
    _$sSo8UIButtonC titleViewButton;
    _$sSo15UIBarButtonItemC filterBarButtonItem;
    _Atomic pollo.ModLogsFilterNode modLogsFilterNode;
    _Atomic pollo.ModeratorLogAction ? activeModeratorAction;
    _$sSSSg activeModerator;
    _$sSaySo18RDKModeratorActionCGSg logs;
    _$sSo13RDKPaginationCSg currentPagination;
    _$sSaySSGSg subredditModerators;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)titleViewButtonTappedWithSender:(id)sender;
- (void)modLogsFilterNodeTapped;
- (void)refreshControlActivatedWithSender:(id)sender;

@end

#endif /* _TtC6Apollo27ModeratorLogsViewController_h */
