//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo26ModmailInboxViewController_h
#define _TtC6Apollo26ModmailInboxViewController_h
@import Foundation;

#include "_TtC6Apollo21ASTableViewController.h"

@class Swift.Bool, _$sSS, _$sSo10RDKModmailCSg, _$sSo8UIButtonC, __C.RDKModmailSort, pollo.ApolloRefreshControl, pollo.ListAdapter, pollo.ModeratorAreaButton, pollo.ModeratorInboxArea, pollo.ModeratorInboxSubreddits, pollo.SubredditSelectorNode;

@interface _TtC6Apollo26ModmailInboxViewController : _TtC6Apollo21ASTableViewController { // (Swift)
    /* instance variables */
    _Atomic pollo.ModeratorInboxArea area;
    _Atomic pollo.ModeratorInboxSubreddits subreddits;
    __C.RDKModmailSort sort;
    _Atomic pollo.ListAdapter listAdapter;
    _Atomic pollo.ApolloRefreshControl refreshControl;
    _$sSo10RDKModmailCSg modmail;
    Swift.Bool hasReachedEnd;
    _Atomic pollo.ModeratorAreaButton moderatorAreaTitleViewButton;
    _$sSo8UIButtonC sortButton;
    _$sSo8UIButtonC moreOptionsButton;
    _Atomic pollo.SubredditSelectorNode subredditSelectorNode;
    _$sSS searchAllToken;
}

/* instance methods */
- (void)scrollViewWillBeginDragging:(id)dragging;
- (void)scrollViewDidScroll:(id)scroll;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(_Bool)decelerate;
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)redditAccountChangedWithNotification:(id)notification;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)moderatorAreaTitleViewButtonTappedWithSender:(id)sender;
- (void)sortButtonTappedWithSender:(id)sender;
- (void)moreOptionsButtonTappedWithSender:(id)sender;
- (void)subredditSelectorNodeTappedWithSender:(id)sender;
- (void)refreshControlActivatedWithSender:(id)sender;

@end

#endif /* _TtC6Apollo26ModmailInboxViewController_h */
