//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo19VideoResourceLoader_h
#define _TtC6Apollo19VideoResourceLoader_h
@import Foundation;

#include "AVAssetResourceLoaderDelegate-Protocol.h"

@class NSObject, pollo.VideoResourceLoaderEnvironment, pollo.VideoResourceLoaderState;

@interface _TtC6Apollo19VideoResourceLoader : NSObject <AVAssetResourceLoaderDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.VideoResourceLoaderState state;
    _Atomic pollo.VideoResourceLoaderEnvironment environment;
}

/* instance methods */
- (void)dealloc;
- (void)resourceLoader:(id)loader didCancelLoadingRequest:(id)request;
- (_Bool)resourceLoader:(id)loader shouldWaitForLoadingOfRequestedResource:(id)resource;
- (id)init;

@end

#endif /* _TtC6Apollo19VideoResourceLoader_h */
