//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo24TranslatorViewController_h
#define _TtC6Apollo24TranslatorViewController_h
@import Foundation;

#include "UIViewControllerTransitioningDelegate-Protocol.h"

@class UIViewController, _$sSS, _$sSo15UIBarButtonItemC, _$sSo18UIVisualEffectViewC, _$sSo23UIActivityIndicatorViewC, _$sSo8UIButtonC, _$sSo9WKWebViewC;

@interface _TtC6Apollo24TranslatorViewController : UIViewController <UIViewControllerTransitioningDelegate> { // (Swift)
    /* instance variables */
    _$sSS textToTranslate;
    _$sSo9WKWebViewC webView;
    _$sSo15UIBarButtonItemC doneBarButtonItem;
    _$sSo18UIVisualEffectViewC closeButtonBackground;
    _$sSo8UIButtonC closeButton;
    _$sSo23UIActivityIndicatorViewC activityIndicatorView;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (id)presentationControllerForPresentedViewController:(id)controller presentingViewController:(id)controller sourceViewController:(id)controller;
- (id)animationControllerForPresentedController:(id)controller presentingController:(id)controller sourceController:(id)controller;
- (id)animationControllerForDismissedController:(id)controller;
- (void)closeButtonTappedWithSender:(id)sender;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo24TranslatorViewController_h */
