//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo7Padlock_h
#define _TtC6Apollo7Padlock_h
@import Foundation;

@class NSObject, _$sSdSg, _$sSo11UIImageViewC, _$sSo7UILabelC, _$sSo8UIButtonC, pollo.PadlockBlurView, pollo.SceneDelegate ?;

@interface _TtC6Apollo7Padlock : NSObject { // (Swift)
    /* instance variables */
    _Atomic pollo.PadlockBlurView blurOverlayView;
    _$sSo8UIButtonC unlockButton;
    _$sSo7UILabelC descriptionLabel;
    _$sSo11UIImageViewC padlockImageView;
    _$sSdSg mostRecentEnterBackgroundTimeWhileAppUnlocked;
    _Atomic pollo.SceneDelegate ? sceneDelegate;
}

/* instance methods */
- (id)init;
- (void)appUnlockSucceededNotification;
- (void)appUnlockFailedNotificationWithNotification:(id)notification;
- (void)unlockButtonTappedWithSender:(id)sender;

@end

#endif /* _TtC6Apollo7Padlock_h */
