//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22ThickSeparatorCellNode_h
#define _TtC6Apollo22ThickSeparatorCellNode_h
@import Foundation;

@class ASCellNode, _$sSo13ASDisplayNodeC;

@interface _TtC6Apollo22ThickSeparatorCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _$sSo13ASDisplayNodeC topHairlineNode;
    _$sSo13ASDisplayNodeC bottomHairlineNode;
}

/* instance methods */
- (id)init;
- (void)didLoad;
- (void)didEnterHierarchy;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;

@end

#endif /* _TtC6Apollo22ThickSeparatorCellNode_h */
