//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC8Mixpanel5Group_h
#define _TtC8Mixpanel5Group_h
@import Foundation;

@class DispatchQueue, Mixpanel.FlushDelegate ?, Mixpanel.MixpanelInstance ?, Mixpanel.MixpanelPersistence, Mixpanel.MixpanelType, Mixpanel.ReadWriteLock, Mixpanel.SessionMetadata, _$sSS, _TtCs12_SwiftObject;

@interface _TtC8Mixpanel5Group : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSS apiToken;
    DispatchQueue serialQueue;
    Mixpanel.ReadWriteLock lock;
    _$sSS groupKey;
    Mixpanel.MixpanelType groupID;
    Mixpanel.FlushDelegate ? delegate;
    Mixpanel.SessionMetadata metadata;
    Mixpanel.MixpanelPersistence mixpanelPersistence;
    Mixpanel.MixpanelInstance ? mixpanelInstance;
}

@end

#endif /* _TtC8Mixpanel5Group_h */
