//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13SPCAIconBuddy_h
#define _TtC6Apollo13SPCAIconBuddy_h
@import Foundation;

@class _$s10Foundation3URLVMn ?, _$sSbSg, _TtCs12_SwiftObject;

@interface _TtC6Apollo13SPCAIconBuddy : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSbSg isActive;
    _$s10Foundation3URLVMn ? photoAlbumURL;
    _$s10Foundation3URLVMn ? wallpaper1PhoneURL;
    _$s10Foundation3URLVMn ? wallpaper1TabletURL;
    _$s10Foundation3URLVMn ? wallpaper1DesktopRegularURL;
    _$s10Foundation3URLVMn ? wallpaper1DesktopVerticalURL;
    _$s10Foundation3URLVMn ? wallpaper1DesktopUltrawideURL;
    _$s10Foundation3URLVMn ? wallpaper2PhoneURL;
    _$s10Foundation3URLVMn ? wallpaper2TabletURL;
    _$s10Foundation3URLVMn ? wallpaper2DesktopRegularURL;
    _$s10Foundation3URLVMn ? wallpaper2DesktopVerticalURL;
    _$s10Foundation3URLVMn ? wallpaper2DesktopUltrawideURL;
}

@end

#endif /* _TtC6Apollo13SPCAIconBuddy_h */
