//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo30OptionalTextActivityItemSource_h
#define _TtC6Apollo30OptionalTextActivityItemSource_h
@import Foundation;

#include "UIActivityItemSource-Protocol.h"

@class NSObject, _$sSS, _$sSo16UIViewControllerCSgXw;

@interface _TtC6Apollo30OptionalTextActivityItemSource : NSObject <UIActivityItemSource> { // (Swift)
    /* instance variables */
    _$sSS text;
    _$sSo16UIViewControllerCSgXw viewController;
}

/* instance methods */
- (id)activityViewControllerPlaceholderItem:(id)item;
- (id)activityViewController:(id)controller itemForActivityType:(id)type;
- (id)activityViewController:(id)controller subjectForActivityType:(id)type;
- (id)init;

@end

#endif /* _TtC6Apollo30OptionalTextActivityItemSource_h */
