//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo20MarkdownTableRowNode_h
#define _TtC6Apollo20MarkdownTableRowNode_h
@import Foundation;

@class ASDisplayNode, _$sSa -> Apollo.MarkdownTableCellNode, _$sSaySo13ASDisplayNodeCG, _$sSo13ASDisplayNodeCSg;

@interface _TtC6Apollo20MarkdownTableRowNode : ASDisplayNode { // (Swift)
    /* instance variables */
    _$sSa -> Apollo.MarkdownTableCellNode cellNodes;
    _$sSaySo13ASDisplayNodeCG verticalSeparatorNodes;
    _$sSo13ASDisplayNodeCSg bottomSeparatorNode;
}

/* instance methods */
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)init;

@end

#endif /* _TtC6Apollo20MarkdownTableRowNode_h */
