//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22ProfileFeatureCellNode_h
#define _TtC6Apollo22ProfileFeatureCellNode_h
@import Foundation;

@class ASCellNode, NSString, _$sSo10ASTextNodeC, _$sSo11ASImageNodeC, _$sSo13ASDisplayNodeC, pollo.ProfileFeature, pollo.ProfileFeaturePosition;

@interface _TtC6Apollo22ProfileFeatureCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _Atomic pollo.ProfileFeature feature;
    _Atomic pollo.ProfileFeaturePosition featurePosition;
    _$sSo11ASImageNodeC iconNode;
    _$sSo10ASTextNodeC titleNode;
    _$sSo11ASImageNodeC disclosureIndicator;
    _$sSo13ASDisplayNodeC insideNode;
    _$sSo13ASDisplayNodeC backgroundNode;
}

@property (nonatomic) _Bool highlighted;
@property (nonatomic) _Bool selected;
@property (nonatomic, copy) NSString *accessibilityLabel;

/* instance methods */
- (_Bool)isHighlighted;
- (_Bool)isSelected;
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo22ProfileFeatureCellNode_h */
