//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22TrophiesViewController_h
#define _TtC6Apollo22TrophiesViewController_h
@import Foundation;

#include "ASTableDataSource-Protocol.h"
#include "ASTableDelegate-Protocol.h"

@class ASDKViewController, _$sSS, _$sSaySo9RDKTrophyCGSg, _$sSo11ASTableNodeC, _$sSo13ASDisplayNodeC;

@interface _TtC6Apollo22TrophiesViewController : ASDKViewController <ASTableDataSource, ASTableDelegate> { // (Swift)
    /* instance variables */
    _$sSaySo9RDKTrophyCGSg trophies;
    _$sSS user;
    _$sSo13ASDisplayNodeC rootNode;
    _$sSo11ASTableNodeC tableNode;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (long long)numberOfSectionsInTableNode:(id)node;
- (long long)tableNode:(id)node numberOfRowsInSection:(long long)section;
- (id /* block */)tableNode:(id)node nodeBlockForRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didSelectRowAtIndexPath:(id)path;
- (void)aboutBarButtonItemTapped:(id)tapped;
- (id)initWithNode:(id)node;
- (id)init;

@end

#endif /* _TtC6Apollo22TrophiesViewController_h */
