//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo15HollaStatusView_h
#define _TtC6Apollo15HollaStatusView_h
@import Foundation;

#include "_TtC6Apollo9HollaView.h"

@class _$s12CoreGraphics7CGFloatVMn, _$sSo11UIImageViewCSg, _$sSo7UILabelCSg;

@interface _TtC6Apollo15HollaStatusView : _TtC6Apollo9HollaView { // (Swift)
    /* instance variables */
    _$s12CoreGraphics7CGFloatVMn labelsHorizontalEdgePadding;
    _$s12CoreGraphics7CGFloatVMn labelsOutterVerticalPadding;
    _$s12CoreGraphics7CGFloatVMn labelsIntraVerticalPadding;
    _$sSo11UIImageViewCSg iconImageView;
    _$sSo7UILabelCSg textLabel;
    _$s12CoreGraphics7CGFloatVMn minimumHeight;
    _$s12CoreGraphics7CGFloatVMn iconTextLabelSpacing;
}

/* instance methods */
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;

@end

#endif /* _TtC6Apollo15HollaStatusView_h */
