//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22TextFieldTableViewCell_h
#define _TtC6Apollo22TextFieldTableViewCell_h
@import Foundation;

@class UIButton, UITableViewCell, UITextField, _$sSo11UITextFieldCSgXw, _$sSo8UIButtonCSgXw;

@interface _TtC6Apollo22TextFieldTableViewCell : UITableViewCell // (Swift)

@property (nonatomic, weak) UITextField *textField;
@property (nonatomic, weak) UIButton *pasteButton;

/* instance methods */
- (void)awakeFromNib;
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo22TextFieldTableViewCell_h */
