//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo20QuickBarKeyboardView_h
#define _TtC6Apollo20QuickBarKeyboardView_h
@import Foundation;

#include "UICollectionViewDataSource-Protocol.h"
#include "UICollectionViewDelegate-Protocol.h"
#include "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSLayoutConstraint, Swift.Bool, UIButton, UIView, _$sSS, _$sSaySSG, _$sSo16UICollectionViewCSg, _$sSo18NSLayoutConstraintCSgXw, _$sSo26UICollectionViewFlowLayoutCSg, _$sSo6UIViewCSgXw, _$sSo8UIButtonCSgXw, pollo.QuickBarKeyboardView.SearchType, pollo.QuickBarKeyboardView.ViewType, pollo.QuickBarKeyboardViewDelegate ?;

@interface _TtC6Apollo20QuickBarKeyboardView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout> { // (Swift)
    /* instance variables */
    _$sSo16UICollectionViewCSg autocompleteCollectionView;
    _$sSo26UICollectionViewFlowLayoutCSg autocompleteCollectionViewLayout;
    _Atomic pollo.QuickBarKeyboardViewDelegate ? delegate;
    _Atomic pollo.QuickBarKeyboardView.ViewType currentlyVisibleView;
    _Atomic pollo.QuickBarKeyboardView.SearchType typeToSearch;
    Swift.Bool alwaysFullWidthSeparator;
    _$sSaySSG suggestions;
    _$sSaySSG usersToSearch;
    _$sSaySSG additionalSubredditsToSearch;
    _$sSS typedTextToFilter;
}

@property (nonatomic, weak) UIView *topSeparator;
@property (nonatomic, weak) UIView *mainActionButtonsView;
@property (nonatomic, weak) UIView *addLinkTitleView;
@property (nonatomic, weak) NSLayoutConstraint *mainViewDistanceFromLeftConstraint;
@property (nonatomic, weak) NSLayoutConstraint *topSeparatorLeftDistanceConstraint;
@property (nonatomic, weak) NSLayoutConstraint *topSeparatorRightDistanceConstraint;
@property (nonatomic, weak) NSLayoutConstraint *topSeparatorHeightConstraint;
@property (nonatomic, weak) UIButton *cameraButton;
@property (nonatomic, weak) UIButton *linkButton;
@property (nonatomic, weak) UIButton *boldButton;
@property (nonatomic, weak) UIButton *italicsButton;
@property (nonatomic, weak) UIButton *subredditButton;
@property (nonatomic, weak) UIButton *userButton;
@property (nonatomic, weak) UIButton *moreButton;

/* instance methods */
- (void)layoutSubviews;
- (void)awakeFromNib;
- (long long)numberOfSectionsInCollectionView:(id)view;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout sizeForItemAtIndexPath:(id)path;
- (void)collectionView:(id)view didSelectItemAtIndexPath:(id)path;
- (void)cameraButtonTapped:(id)tapped;
- (void)linkButtonTapped:(id)tapped;
- (void)boldButtonTapped:(id)tapped;
- (void)italicsButtonTapped:(id)tapped;
- (void)subredditButtonTapped:(id)tapped;
- (void)userButtonTapped:(id)tapped;
- (void)moreButtonTapped:(id)tapped;
- (void)addTitleToLinkButtonTapped:(id)tapped;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo20QuickBarKeyboardView_h */
