//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo31CommentsViewControllerSeparator_h
#define _TtC6Apollo31CommentsViewControllerSeparator_h
@import Foundation;

#include "IGListDiffable-Protocol.h"

@class NSObject, _$sSS, _$sSi;

@interface _TtC6Apollo31CommentsViewControllerSeparator : NSObject <IGListDiffable> { // (Swift)
    /* instance variables */
    _$sSS identifier;
    _$sSi depth;
}

@property (nonatomic, readonly) long long hash;

/* instance methods */
- (id)diffIdentifier;
- (_Bool)isEqualToDiffableObject:(id)object;
- (id)init;

@end

#endif /* _TtC6Apollo31CommentsViewControllerSeparator_h */
