//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13RichMediaNode_Apollo_h
#define _TtC6Apollo13RichMediaNode_Apollo_h
@import Foundation;

@interface _TtC6Apollo13RichMediaNode (Apollo) <ASNetworkImageNodeDelegate, ASVideoNodeDelegate, ASTextNodeDelegate> // (Swift)

/* instance methods */
- (_Bool)textNode:(id)node shouldHighlightLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)textNode:(id)node shouldLongPressLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;
- (void)textNode:(id)node tappedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)textNode:(id)node longPressedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)muteUnmuteButtonTappedWithSender:(id)sender;
- (void)intermediaryNodeTappedWithSender:(id)sender;
- (void)thumbnailTappedWithSender:(id)sender;
- (void)subredditTappedWithSender:(id)sender;
- (void)authorTappedWithSender:(id)sender;
- (void)longPressedWithGestureRecognizer:(id)recognizer;
- (void)pointsButtonTappedWithSender:(id)sender;
- (void)pointsButtonLongPressedWithGestureRecognizer:(id)recognizer;
- (void)upvoteButtonTappedWithSender:(id)sender;
- (void)downvoteButtonTappedWithSender:(id)sender;
- (void)moreOptionsButtonTappedWithSender:(id)sender;
- (void)linkButtonTappedWithSender:(id)sender;
- (void)moderatorBannerNodeTappedWithSender:(id)sender;
- (void)albumThumbnailButtonTappedWithSender:(id)sender;
- (void)layout;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (void)imageNode:(id)node didLoadImage:(id)image;
- (void)imageNode:(id)node didFailWithError:(id)error;
- (void)videoNode:(id)node didFailToLoadValueForKey:(id)key asset:(id)asset error:(id)error;
- (void)didTapVideoNode:(id)node;
- (void)videoNode:(id)node willChangePlayerState:(long long)state toState:(long long)state;
- (void)videoNode:(id)node didPlayToTimeInterval:(double)interval;

@end

#endif /* _TtC6Apollo13RichMediaNode_Apollo_h */
