//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo16IconTextCellNode_h
#define _TtC6Apollo16IconTextCellNode_h
@import Foundation;

@class ASCellNode, Swift.Bool, _$s12CoreGraphics7CGFloatVMn, _$sSS, _$sSo10ASTextNodeC, _$sSo11ASImageNodeC, _$sSo11ASImageNodeCSg, _$sSo7UIImageC, pollo.IconTextCellNode.IconColor;

@interface _TtC6Apollo16IconTextCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _Atomic pollo.IconTextCellNode.IconColor iconColor;
    _$sSo7UIImageC iconImage;
    _$sSS text;
    _$s12CoreGraphics7CGFloatVMn textInset;
    Swift.Bool showDisclosureIndicator;
    _$sSo11ASImageNodeC iconNode;
    _$sSo10ASTextNodeC textNode;
    _$sSo11ASImageNodeCSg disclosureIndicator;
}

/* instance methods */
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo16IconTextCellNode_h */
