//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo28AccountManagerViewController_h
#define _TtC6Apollo28AccountManagerViewController_h
@import Foundation;

#include "UINavigationBarDelegate-Protocol.h"
#include "UITableViewDataSource-Protocol.h"
#include "UITableViewDelegate-Protocol.h"
#include "UIViewControllerTransitioningDelegate-Protocol.h"

@class UIViewController, _$sSo11UITableViewCSg, _$sSo15UIBarButtonItemCSg, _$sSo15UINavigationBarCSg, _$sSo9RDKClientCSg, _$sySo9RDKClientCcSg, pollo.AccountManagerViewController.AccountSwitchType;

@interface _TtC6Apollo28AccountManagerViewController : UIViewController <UIViewControllerTransitioningDelegate, UINavigationBarDelegate, UITableViewDataSource, UITableViewDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.AccountManagerViewController.AccountSwitchType accountSwitchType;
    _$sSo9RDKClientCSg temporaryAccount;
    _$sySo9RDKClientCcSg temporaryAccountSwitch;
    _$sSo11UITableViewCSg tableView;
    _$sSo15UIBarButtonItemCSg cancelBarButtonItem;
    _$sSo15UIBarButtonItemCSg addBarButtonItem;
    _$sSo15UINavigationBarCSg navigationBar;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)setEditing:(_Bool)editing animated:(_Bool)animated;
- (long long)positionForBar:(id)bar;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (void)tableView:(id)view commitEditingStyle:(long long)style forRowAtIndexPath:(id)path;
- (_Bool)tableView:(id)view canEditRowAtIndexPath:(id)path;
- (_Bool)tableView:(id)view canMoveRowAtIndexPath:(id)path;
- (void)tableView:(id)view moveRowAtIndexPath:(id)path toIndexPath:(id)path;
- (double)tableView:(id)view heightForHeaderInSection:(long long)section;
- (double)tableView:(id)view heightForFooterInSection:(long long)section;
- (id)tableView:(id)view viewForHeaderInSection:(long long)section;
- (id)tableView:(id)view viewForFooterInSection:(long long)section;
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)path;
- (id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)path;
- (void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)path;
- (void)tableView:(id)view didEndEditingRowAtIndexPath:(id)path;
- (id)animationControllerForPresentedController:(id)controller presentingController:(id)controller sourceController:(id)controller;
- (id)animationControllerForDismissedController:(id)controller;
- (id)presentationControllerForPresentedViewController:(id)controller presentingViewController:(id)controller sourceViewController:(id)controller;
- (void)cancelBarButtonItemTapped:(id)tapped;
- (void)addBarButtonItemTapped:(id)tapped;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo28AccountManagerViewController_h */
