//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo12ThemeManager_h
#define _TtC6Apollo12ThemeManager_h
@import Foundation;

@class DispatchQueue, NSObject, _$s7Combine9PublishedVMn Apollo.Theme, _$s7Combine9PublishedVMn Apollo.Theme ?, _$sSa -> Apollo.Theme, _$sSo11NSHashTableCyyXlG, _$sSo8UIWindowCSg, pollo.AppColorTheme;

@interface _TtC6Apollo12ThemeManager : NSObject { // (Swift)
    /* instance variables */
    _$s7Combine9PublishedVMn Apollo.Theme _apolloSpecificTheme;
    _$s7Combine9PublishedVMn Apollo.Theme ? _systemTheme;
    _Atomic pollo.AppColorTheme appColorTheme;
    _$sSo11NSHashTableCyyXlG listeners;
    DispatchQueue dispatchQueue;
    _$sSo8UIWindowCSg themeChangeWindow;
    _$sSa -> Apollo.Theme themes;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo12ThemeManager_h */
