//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo26ModeratorReportsController_h
#define _TtC6Apollo26ModeratorReportsController_h
@import Foundation;

#include "_TtC6Apollo16ActionController.h"

@class Swift.Bool, _$sSaySayypGG, _$sSi, _$sySbcSg, _$syycSg, pollo.HeightResizingTableView, pollo.ModeratorReportableState ?, pollo.ModeratorReportsControllerDataSource;

@interface _TtC6Apollo26ModeratorReportsController : _TtC6Apollo16ActionController { // (Swift)
    /* instance variables */
    _$sSaySayypGG userReports;
    _$sSaySayypGG moderatorReports;
    _$sSi numberReports;
    Swift.Bool ignoringReports;
    _Atomic pollo.ModeratorReportableState ? state;
    _Atomic pollo.ModeratorReportsControllerDataSource dataSource;
    _Atomic pollo.HeightResizingTableView headerTableView;
    _$sySbcSg approveTappedHandler;
    _$syycSg removeTappedHandler;
    _$syycSg markSpamTappedHandler;
    _$sySbcSg ignoreReportsTappedHandler;
}

/* instance methods */
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo26ModeratorReportsController_h */
