//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo5Holla_h
#define _TtC6Apollo5Holla_h
@import Foundation;

#include "UIGestureRecognizerDelegate-Protocol.h"

@class NSObject, Swift.Bool, _$s12CoreGraphics7CGFloatVMn, _$sSo16UIViewControllerCSgXw, pollo.HollaView ?;

@interface _TtC6Apollo5Holla : NSObject <UIGestureRecognizerDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.HollaView ? activeStatusView;
    _$s12CoreGraphics7CGFloatVMn maximumViewWidth;
    _$s12CoreGraphics7CGFloatVMn viewEdgePadding;
    Swift.Bool panningNotification;
    Swift.Bool panningStatus;
    Swift.Bool isShowingStatusIndefinitely;
    _$sSo16UIViewControllerCSgXw recentlyPresentedViewController;
}

/* instance methods */
- (_Bool)gestureRecognizerShouldBegin:(id)begin;
- (void)statusTapped:(id)tapped;
- (void)statusPanned:(id)panned;
- (id)init;

@end

#endif /* _TtC6Apollo5Holla_h */
