//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo7JumpBar_h
#define _TtC6Apollo7JumpBar_h
@import Foundation;

#include "UITextFieldDelegate-Protocol.h"

@class Swift.Bool, UIControl, _$s12CoreGraphics7CGFloatVMn, _$sSS, _$sSo11UIImageViewCSg, _$sSo11UITextFieldCSg, _$sSo18NSLayoutConstraintCSg, _$sSo7UILabelCSg, pollo.JumpBar.JumpBarState, pollo.JumpBarDelegate ?;

@interface _TtC6Apollo7JumpBar : UIControl <UITextFieldDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.JumpBarDelegate ? delegate;
    _$sSo7UILabelCSg nameLabel;
    _$sSo11UIImageViewCSg arrowImageView;
    _$sSo7UILabelCSg secondaryLabel;
    _$sSo11UITextFieldCSg searchTextField;
    _$sSo7UILabelCSg suggestionLabel;
    _$sSo18NSLayoutConstraintCSg nameLabelCenterYConstraint;
    _$s12CoreGraphics7CGFloatVMn spacing;
    Swift.Bool showSuggestions;
    Swift.Bool displayingMultireddit;
    _Atomic pollo.JumpBar.JumpBarState jumpBarState;
    _$sSS dropDownTitle;
}

@property (nonatomic, readonly) struct CGSize { double x0; double x1; } intrinsicContentSize;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (_Bool)beginTrackingWithTouch:(id)touch withEvent:(id)event;
- (_Bool)continueTrackingWithTouch:(id)touch withEvent:(id)event;
- (void)endTrackingWithTouch:(id)touch withEvent:(id)event;
- (void)cancelTrackingWithEvent:(id)event;
- (void)searchTextFieldChanged:(id)changed;
- (_Bool)textFieldShouldReturn:(id)_return;
- (_Bool)textField:(id)field shouldChangeCharactersInRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range replacementString:(id)string;

@end

#endif /* _TtC6Apollo7JumpBar_h */
