//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo25AwardsGivenViewController_h
#define _TtC6Apollo25AwardsGivenViewController_h
@import Foundation;

#include "UITableViewDataSource-Protocol.h"
#include "UITableViewDelegate-Protocol.h"
#include "_TtC6Apollo23SourdoughViewController.h"

@class _$s12CoreGraphics7CGFloatVMn, _$sSSSg, _$sSaySo8RDKAwardCG, _$sSo11UITableViewC, _$sSo6UIViewC, _$sSo7UILabelC, _$sSo8RDKThingC, pollo.GiveAwardButton;

@interface _TtC6Apollo25AwardsGivenViewController : _TtC6Apollo23SourdoughViewController <UITableViewDataSource, UITableViewDelegate> { // (Swift)
    /* instance variables */
    _$sSaySo8RDKAwardCG awards;
    _$sSSSg subreddit;
    _$sSo8RDKThingC thingToAward;
    _$sSo7UILabelC titleLabel;
    _$sSo6UIViewC titleSeparator;
    _$sSo11UITableViewC tableView;
    _Atomic pollo.GiveAwardButton giveAwardButton;
    _$s12CoreGraphics7CGFloatVMn titleAreaHeight;
    _$s12CoreGraphics7CGFloatVMn giveAwardButtonTopSpacing;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (long long)tableView:(id)view numberOfRowsInSection:(long long)section;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)path;
- (void)giveAwardButtonTappedWithSender:(id)sender;
- (id)init;

@end

#endif /* _TtC6Apollo25AwardsGivenViewController_h */
