//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo11CommentTree_h
#define _TtC6Apollo11CommentTree_h
@import Foundation;

@class NSObject, _$sSDySSSaySo8RDKThingCGG, _$sSDySSSiG, _$sSDySSSo10RDKCommentCG, _$sSDySSSo15RDKMoreCommentsCG, _$sSaySo8RDKThingCG, _$sSi, _$sSiSg, _$sSo10RDKCommentCSg;

@interface _TtC6Apollo11CommentTree : NSObject { // (Swift)
    /* instance variables */
    _$sSaySo8RDKThingCG topLevelComments;
    _$sSaySo8RDKThingCG flatCommentsCache;
    _$sSDySSSo10RDKCommentCG commentWithIdentifierCache;
    _$sSDySSSo15RDKMoreCommentsCG moreCommentsWithIdentifierCache;
    _$sSiSg cachedTotalComments;
    _$sSi recursionCounter;
    _$sSo10RDKCommentCSg stickiedComment;
    _$sSDySSSiG moreCommentsIdentifierNumberOfRepliesDeleted;
    _$sSDySSSaySo8RDKThingCGG topCommentIDToReplies;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo11CommentTree_h */
