//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13PostTitleNode_h
#define _TtC6Apollo13PostTitleNode_h
@import Foundation;

@class ASDisplayNode, Swift.Bool, _$s10Foundation3URLVMn ?, _$sSd, _$sSo10ASTextNodeC, _$sSo7RDKLinkC, pollo.FlairNode ?, pollo.PostContentAdvisoryNode ?, pollo.PostTitleNodeDelegate ?, pollo.PostTitleURLNode ?;

@interface _TtC6Apollo13PostTitleNode : ASDisplayNode { // (Swift)
    /* instance variables */
    _$sSo7RDKLinkC link;
    Swift.Bool isCompact;
    _$s10Foundation3URLVMn ? url;
    Swift.Bool isBolder;
    Swift.Bool disableFlairTap;
    _$sSo10ASTextNodeC titleNode;
    _Atomic pollo.FlairNode ? flairNode;
    _Atomic pollo.PostContentAdvisoryNode ? nsfwNode;
    _Atomic pollo.PostContentAdvisoryNode ? spoilerNode;
    _Atomic pollo.PostTitleURLNode ? urlNode;
    _$sSd horizontalSpacing;
    _$sSd verticalSpacing;
    _Atomic pollo.PostTitleNodeDelegate ? delegate;
    Swift.Bool isRead;
}

/* instance methods */
- (void)didLoad;
- (void)calculatedLayoutDidChange;
- (void)layout;
- (struct CGSize { double x0; double x1; })calculateSizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)flairNodeTappedWithSender:(id)sender;
- (id)init;

@end

#endif /* _TtC6Apollo13PostTitleNode_h */
