//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo18ReachedEndCellNode_h
#define _TtC6Apollo18ReachedEndCellNode_h
@import Foundation;

@class ASCellNode, Swift.Bool, _$sSo10ASTextNodeC, _$sSo11ASImageNodeC;

@interface _TtC6Apollo18ReachedEndCellNode : ASCellNode { // (Swift)
    /* instance variables */
    Swift.Bool likelyReachedEndOfLoadablePosts;
    _$sSo10ASTextNodeC titleNode;
    _$sSo10ASTextNodeC descriptionNode;
    _$sSo11ASImageNodeC backgroundDinosaurNode1;
    _$sSo11ASImageNodeC backgroundDinosaurNode2;
    _$sSo11ASImageNodeC backgroundDinosaurNode3;
}

/* instance methods */
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo18ReachedEndCellNode_h */
