//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo15ThemeableWindow_h
#define _TtC6Apollo15ThemeableWindow_h
@import Foundation;

@class UIWindow, pollo.FauxCutOutView ?, pollo.PixelPalScene ?, pollo.PixelPalView ?;

@interface _TtC6Apollo15ThemeableWindow : UIWindow { // (Swift)
    /* instance variables */
    _Atomic pollo.PixelPalView ? pixelPalView;
    _Atomic pollo.PixelPalScene ? pixelPalScene;
    _Atomic pollo.FauxCutOutView ? fauxCutOutView;
}

/* instance methods */
- (id)initWithWindowScene:(id)scene;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;
- (void)pixelPalTappedWithTapGestureRecognizer:(id)recognizer;
- (void)addSubview:(id)subview;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)change;
- (void)pixelPalSettingChangedWithNotification:(id)notification;
- (void)dogBarkedWithNotification:(id)notification;
- (void)applicationWillResignActiveNotificationWithNotification:(id)notification;
- (void)applicationDidBecomeActiveNotificationWithNotification:(id)notification;

@end

#endif /* _TtC6Apollo15ThemeableWindow_h */
