//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC8Mixpanel5Flush_h
#define _TtC8Mixpanel5Flush_h
@import Foundation;

@class DispatchQueue, Mixpanel.FlushDelegate ?, Mixpanel.FlushRequest, Swift.Bool, _$sSd, _$sSo7NSTimerCSg, _TtCs12_SwiftObject;

@interface _TtC8Mixpanel5Flush : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo7NSTimerCSg timer;
    Mixpanel.FlushDelegate ? delegate;
    Swift.Bool useIPAddressForGeoLocation;
    Mixpanel.FlushRequest flushRequest;
    Swift.Bool flushOnBackground;
    _$sSd _flushInterval;
    DispatchQueue flushIntervalReadWriteLock;
}

/* instance methods */
- (void)flushSelector;

@end

#endif /* _TtC8Mixpanel5Flush_h */
