//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo28WallpaperAlertViewController_h
#define _TtC6Apollo28WallpaperAlertViewController_h
@import Foundation;

#include "SKProductsRequestDelegate-Protocol.h"

@class UIViewController, _$sSS, _$sSaySo9SKProductCGSg, _$sSo16UIViewControllerCSg, pollo.ApolloWallpaperSetInfo, pollo.WallpaperMessenger;

@interface _TtC6Apollo28WallpaperAlertViewController : UIViewController <SKProductsRequestDelegate> { // (Swift)
    /* instance variables */
    _Atomic pollo.ApolloWallpaperSetInfo wallpaperSetInfo;
    _$sSS location;
    _$sSo16UIViewControllerCSg $__lazy_storage_$_hostingController;
    _Atomic pollo.WallpaperMessenger messenger;
    _$sSS tier1ProductID;
    _$sSS tier3ProductID;
    _$sSS tier5ProductID;
    _$sSS tier10ProductID;
    _$sSS tier20ProductID;
    _$sSaySo9SKProductCGSg products;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)productsRequest:(id)request didReceiveResponse:(id)response;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo28WallpaperAlertViewController_h */
