//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo39SettingsNotificationsWarningBannerView2_h
#define _TtC6Apollo39SettingsNotificationsWarningBannerView2_h
@import Foundation;

@class UIView, _$s12CoreGraphics7CGFloatVMn, _$sSo6UIViewC, _$sSo7UILabelC, _$sSo8UIButtonCSg, pollo.UltraStatusIssue, pollo.UltraWarningBannerViewDelegate ?;

@interface _TtC6Apollo39SettingsNotificationsWarningBannerView2 : UIView { // (Swift)
    /* instance variables */
    _$s12CoreGraphics7CGFloatVMn backgroundInset;
    _$s12CoreGraphics7CGFloatVMn titleTopInset;
    _$s12CoreGraphics7CGFloatVMn labelVerticalInset;
    _Atomic pollo.UltraStatusIssue issue;
    _$sSo6UIViewC warningBackgroundView;
    _$sSo7UILabelC warningTitleLabel;
    _$sSo7UILabelC warningLabel;
    _$sSo8UIButtonCSg callToActionButton;
    _$sSo8UIButtonCSg hideButton;
    _Atomic pollo.UltraWarningBannerViewDelegate ? delegate;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)callToActionButtonTappedWithSender:(id)sender;
- (void)hideButtonTappedWithSender:(id)sender;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;

@end

#endif /* _TtC6Apollo39SettingsNotificationsWarningBannerView2_h */
