//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13PixelPalScene_h
#define _TtC6Apollo13PixelPalScene_h
@import Foundation;

@class SKScene, _$sSo17UIDynamicAnimatorCSg, _$sSo17UIGravityBehaviorCSg, _$sSo19UICollisionBehaviorCSg, _$sSo21UIDynamicItemBehaviorCSg, __C.CGSize ?, __C.UIInterfaceOrientation ?, pollo.PixelPal, pollo.PixelPalScene.WandGameDirectionChangeDetails ?, pollo.PixelPalScene.WandGameLocation ?, pollo.PixelPalSceneState ?, pollo.PixelPalSpriteNode;

@interface _TtC6Apollo13PixelPalScene : SKScene { // (Swift)
    /* instance variables */
    _Atomic pollo.PixelPal pixelPal;
    _Atomic pollo.PixelPalSceneState ? state;
    _Atomic pollo.PixelPalSpriteNode node;
    _$sSo17UIDynamicAnimatorCSg animator;
    _$sSo21UIDynamicItemBehaviorCSg bounce;
    _$sSo19UICollisionBehaviorCSg collision;
    _$sSo17UIGravityBehaviorCSg gravity;
    _Atomic pollo.PixelPalScene.WandGameLocation ? wandGameWandLocation;
    _Atomic pollo.PixelPalScene.WandGameDirectionChangeDetails ? wandGameDirectionChangeDetails;
    __C.CGSize ? previousSize;
    __C.UIInterfaceOrientation ? previousOrientation;
}

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)didMoveToView:(id)view;
- (void)didChangeSize:(struct CGSize { double x0; double x1; })size;
- (void)rolledPixelPalFoodNotificationWithNotification:(id)notification;
- (id)initWithSize:(struct CGSize { double x0; double x1; })size;
- (id)init;

@end

#endif /* _TtC6Apollo13PixelPalScene_h */
