//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22GroupActivitiesManager_h
#define _TtC6Apollo22GroupActivitiesManager_h
@import Foundation;

@class NSObject, Swift.Bool, _$s15GroupActivities0A13StateObserverCMn, _$s15GroupActivities0A16SessionMessengerCMn ??, _$sSh -> _$ss11AnyHashableVMn, _$sShyScTyyt _$ss5NeverOMn _$sGGSg, _$sypSg;

@interface _TtC6Apollo22GroupActivitiesManager : NSObject { // (Swift)
    /* instance variables */
    _$s15GroupActivities0A16SessionMessengerCMn ?? $__lazy_storage_$_groupMessenger;
    _$sShyScTyyt _$ss5NeverOMn _$sGGSg $__lazy_storage_$_tasks;
    _$sypSg _groupSession;
    _$s15GroupActivities0A13StateObserverCMn groupStateObserver;
    Swift.Bool isEligibleForSharePlay;
    _$sSh -> _$ss11AnyHashableVMn _subscriptions;
    _$sSh -> _$ss11AnyHashableVMn _eligibilitySubscriptions;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo22GroupActivitiesManager_h */
