//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo29SharePlayEnableViewController_h
#define _TtC6Apollo29SharePlayEnableViewController_h
@import Foundation;

@class Swift.Bool, UIViewController, _$syycSg, pollo.SpookyAlertView;

@interface _TtC6Apollo29SharePlayEnableViewController : UIViewController { // (Swift)
    /* instance variables */
    _Atomic pollo.SpookyAlertView enableScreen;
    _Atomic pollo.SpookyAlertView settingsScreen;
    Swift.Bool isViewingSettingsScreen;
    _$syycSg onCompletion;
}

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (id)initWithNibName:(id)name bundle:(id)bundle;

@end

#endif /* _TtC6Apollo29SharePlayEnableViewController_h */
