//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC7Statsig11EventLogger_h
#define _TtC7Statsig11EventLogger_h
@import Foundation;

@class DispatchQueue, Statsig.DefaultsLike, Statsig.NetworkService, Statsig.StatsigUser, _$sSa -> Statsig.Event, _$sSa -> _$s10Foundation4DataVMn, _$sShySSG, _$sSi, _$sSo7NSTimerCSg, _TtCs12_SwiftObject;

@interface _TtC7Statsig11EventLogger : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSi flushBatchSize;
    _$sSi maxEventQueueSize;
    _$sSa -> Statsig.Event events;
    _$sSa -> _$s10Foundation4DataVMn failedRequestQueue;
    _$sShySSG loggedErrorMessage;
    _$sSo7NSTimerCSg flushTimer;
    Statsig.StatsigUser user;
    Statsig.NetworkService networkService;
    Statsig.DefaultsLike userDefaults;
    DispatchQueue logQueue;
    _$sSi MAX_SAVED_LOG_REQUEST_SIZE;
}

@end

#endif /* _TtC7Statsig11EventLogger_h */
