//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC7Statsig18StatsigEnvironment_h
#define _TtC7Statsig18StatsigEnvironment_h
@import Foundation;

@class NSObject, _$sSDyS2SG;

@interface _TtC7Statsig18StatsigEnvironment : NSObject { // (Swift)
    /* instance variables */
    _$sSDyS2SG params;
}

/* instance methods */
- (id)initWithTier:(id)tier;
- (id)init;

@end

#endif /* _TtC7Statsig18StatsigEnvironment_h */
