//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo22ApolloTabBarController_h
#define _TtC6Apollo22ApolloTabBarController_h
@import Foundation;

#include "UIGestureRecognizerDelegate-Protocol.h"

@class ASTabBarController, NSArray, Swift.Bool, _$sSo22UIPanGestureRecognizerCSg, _$sSo25UIImpactFeedbackGeneratorC, pollo.ApolloLongPressGestureRecognizer ?;

@interface _TtC6Apollo22ApolloTabBarController : ASTabBarController <UIGestureRecognizerDelegate> { // (Swift)
    /* instance variables */
    _$sSo22UIPanGestureRecognizerCSg tabBarPanGestureRecognizer;
    _Atomic pollo.ApolloLongPressGestureRecognizer ? tabBarLongPressGestureRecognizer;
    _$sSo25UIImpactFeedbackGeneratorC impactGenerator;
    Swift.Bool themeAsModerator;
}

@property (nonatomic, readonly) NSArray *keyCommands;
@property (nonatomic, readonly) long long preferredStatusBarStyle;
@property (nonatomic, readonly) _Bool shouldAutorotate;
@property (nonatomic, readonly) unsigned long long supportedInterfaceOrientations;

/* instance methods */
- (void)goToHomeTab;
- (void)goToInboxTab;
- (void)goToProfileTab;
- (void)goToSearchTab;
- (void)goToSettingsTab;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)tabBarPanned:(id)panned;
- (_Bool)gestureRecognizerShouldBegin:(id)begin;
- (void)tabBarLongPressedWithLongPressGestureRecognizer:(id)recognizer;
- (_Bool)gestureRecognizer:(id)recognizer shouldBeRequiredToFailByGestureRecognizer:(id)recognizer;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo22ApolloTabBarController_h */
