//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo19DualStateButtonNode_h
#define _TtC6Apollo19DualStateButtonNode_h
@import Foundation;

@class ASControlNode, Swift.Bool, _$sSo11ASImageNodeC, _$sSo13ASDisplayNodeC, _$sSo28UISelectionFeedbackGeneratorC, __C.CGSize ?, pollo.DualStateButtonNode.ColorType, pollo.DualStateButtonNode.DualStateButtonType;

@interface _TtC6Apollo19DualStateButtonNode : ASControlNode { // (Swift)
    /* instance variables */
    Swift.Bool isArchived;
    _Atomic pollo.DualStateButtonNode.DualStateButtonType type;
    _Atomic pollo.DualStateButtonNode.ColorType colorType;
    Swift.Bool interactionFailed;
    Swift.Bool themeable;
    _$sSo13ASDisplayNodeC backgroundNode;
    _$sSo11ASImageNodeC iconNode;
    _$sSo28UISelectionFeedbackGeneratorC selectionGenerator;
    Swift.Bool isActive;
    __C.CGSize ? maximumBackgroundSize;
}

/* instance methods */
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)init;

@end

#endif /* _TtC6Apollo19DualStateButtonNode_h */
