//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23HeightResizingTableView_h
#define _TtC6Apollo23HeightResizingTableView_h
@import Foundation;

@class UITableView;

@interface _TtC6Apollo23HeightResizingTableView : UITableView // (Swift)

@property (nonatomic, readonly) struct CGSize { double x0; double x1; } intrinsicContentSize;

/* instance methods */
- (void)reloadData;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)reloadSections:(id)sections withRowAnimation:(long long)animation;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame style:(long long)style;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo23HeightResizingTableView_h */
