//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo13RedGIFsClient_h
#define _TtC6Apollo13RedGIFsClient_h
@import Foundation;

@class DispatchQueue, Swift.Bool, _$s10Foundation3URLVMn, _$s10Foundation4DateVMn ?, _$sSDySS Apollo.RedGIFsVideo, _$sSSSg, _$sSa -> Apollo.RedGIFsClient.RedGIFsFetch, _$sSo12NSURLSessionC, _TtCs12_SwiftObject;

@interface _TtC6Apollo13RedGIFsClient : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSo12NSURLSessionC session;
    _$sSDySS Apollo.RedGIFsVideo redGIFsCache;
    DispatchQueue dispatchQueue;
    _$s10Foundation4DateVMn ? oauthExpiresAt;
    _$sSSSg accessToken;
    Swift.Bool isTokenBeingFetched;
    _$sSa -> Apollo.RedGIFsClient.RedGIFsFetch queuedFetches;
    _$s10Foundation3URLVMn oauthURL;
}

@end

#endif /* _TtC6Apollo13RedGIFsClient_h */
