//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo19WKScriptLeakAvoider_h
#define _TtC6Apollo19WKScriptLeakAvoider_h
@import Foundation;

#include "WKScriptMessageHandler-Protocol.h"

@class NSObject, _$sSo22WKScriptMessageHandler_pSgXw;

@interface _TtC6Apollo19WKScriptLeakAvoider : NSObject <WKScriptMessageHandler> { // (Swift)
    /* instance variables */
    _$sSo22WKScriptMessageHandler_pSgXw delegate;
}

/* instance methods */
- (void)userContentController:(id)controller didReceiveScriptMessage:(id)message;
- (id)init;

@end

#endif /* _TtC6Apollo19WKScriptLeakAvoider_h */
