//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo18SubtleIconTextNode_h
#define _TtC6Apollo18SubtleIconTextNode_h
@import Foundation;

#include "_TtC6Apollo17ApolloControlNode.h"

@class _$sSo10ASTextNodeC, _$sSo11ASImageNodeC;

@interface _TtC6Apollo18SubtleIconTextNode : _TtC6Apollo17ApolloControlNode { // (Swift)
    /* instance variables */
    _$sSo11ASImageNodeC imageNode;
    _$sSo10ASTextNodeC textNode;
}

/* instance methods */
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)init;

@end

#endif /* _TtC6Apollo18SubtleIconTextNode_h */
