//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo21ProfileHeaderCellNode_h
#define _TtC6Apollo21ProfileHeaderCellNode_h
@import Foundation;

@class ASCellNode, _$s10Foundation4DateVMn, _$sSi, pollo.ApolloButtonNode, pollo.ProfileHeaderActionDelegate ?;

@interface _TtC6Apollo21ProfileHeaderCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _$sSi commentKarma;
    _$sSi postKarma;
    _$s10Foundation4DateVMn age;
    _Atomic pollo.ApolloButtonNode commentKarmaButtonNode;
    _Atomic pollo.ApolloButtonNode postKarmaButtonNode;
    _Atomic pollo.ApolloButtonNode ageButtonNode;
    _Atomic pollo.ProfileHeaderActionDelegate ? actionDelegate;
}

/* instance methods */
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (void)commentKarmaButtonTappedWithSender:(id)sender;
- (void)postKarmaButtonTappedWithSender:(id)sender;
- (void)ageButtonTappedWithSender:(id)sender;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo21ProfileHeaderCellNode_h */
