//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo11ImgurClient_h
#define _TtC6Apollo11ImgurClient_h
@import Foundation;

@class DispatchQueue, _$s10Foundation19PropertyListDecoderCMn, _$s10Foundation19PropertyListEncoderCMn, _$sSDySS Apollo.ImgurAlbum, _$sSDySS Apollo.ImgurClient.GalleryType, _$sSDySS Apollo.ImgurImage, _$sSDySSSdG, _$sSDySi Apollo.ImgurImage ?, _$sSS, _$sSaySo22NSURLSessionUploadTaskCGSg, _$sSo12NSURLSessionC, _TtCs12_SwiftObject;

@interface _TtC6Apollo11ImgurClient : _TtCs12_SwiftObject { // (Swift)
    /* instance variables */
    _$sSDySS Apollo.ImgurAlbum albumCache;
    _$sSDySS Apollo.ImgurImage imageCache;
    _$sSDySS Apollo.ImgurClient.GalleryType galleryTypeCache;
    _$sSo12NSURLSessionC session;
    DispatchQueue dispatchQueue;
    _$sSaySo22NSURLSessionUploadTaskCGSg albumUploadTasks;
    _$sSDySi Apollo.ImgurImage ? uploadedImages;
    _$sSDySSSdG imgurVideoDurations;
    _$sSS savedUploadsFileName;
    _$s10Foundation19PropertyListEncoderCMn encoder;
    _$s10Foundation19PropertyListDecoderCMn decoder;
}

@end

#endif /* _TtC6Apollo11ImgurClient_h */
