//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo52CommentsTableNode3DTouchPreviewListAdapterDataSource_h
#define _TtC6Apollo52CommentsTableNode3DTouchPreviewListAdapterDataSource_h
@import Foundation;

@class NSObject, _$sSS, _$sSo7RDKLinkCSg, pollo.CommentTree ?;

@interface _TtC6Apollo52CommentsTableNode3DTouchPreviewListAdapterDataSource : NSObject { // (Swift)
    /* instance variables */
    _$sSo7RDKLinkCSg link;
    _Atomic pollo.CommentTree ? commentTree;
    _$sSS noCommentsToken;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo52CommentsTableNode3DTouchPreviewListAdapterDataSource_h */
