//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo31ProfileFeatureSectionController_h
#define _TtC6Apollo31ProfileFeatureSectionController_h
@import Foundation;

#include "_TtC6Apollo17SectionController.h"

@class Swift.Bool, _$sSS, pollo.ProfileFeature, pollo.ProfileFeaturePosition;

@interface _TtC6Apollo31ProfileFeatureSectionController : _TtC6Apollo17SectionController { // (Swift)
    /* instance variables */
    _Atomic pollo.ProfileFeature profileFeature;
    _$sSS username;
    Swift.Bool shouldUseFullWidthSeparator;
    _Atomic pollo.ProfileFeaturePosition featurePosition;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC6Apollo31ProfileFeatureSectionController_h */
