//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo19HeaderImageCellNode_h
#define _TtC6Apollo19HeaderImageCellNode_h
@import Foundation;

@class ASCellNode, pollo.HeaderImageCellActionDelegate ?, pollo.TouchHintNetworkImageNode;

@interface _TtC6Apollo19HeaderImageCellNode : ASCellNode { // (Swift)
    /* instance variables */
    _Atomic pollo.TouchHintNetworkImageNode headerImageNode;
    _Atomic pollo.HeaderImageCellActionDelegate ? actionDelegate;
}

/* instance methods */
- (void)didLoad;
- (id)layoutSpecThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (void)headerImageNodeTappedWithSender:(id)sender;
- (id)initWithViewControllerBlock:(id /* block */)block didLoadBlock:(id /* block */)block;
- (id)init;

@end

#endif /* _TtC6Apollo19HeaderImageCellNode_h */
