//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo35ApolloUltraManagementViewController_h
#define _TtC6Apollo35ApolloUltraManagementViewController_h
@import Foundation;

@class Swift.Bool, _$s6Eureka18FormViewControllerCN;

@interface _TtC6Apollo35ApolloUltraManagementViewController : _$s6Eureka18FormViewControllerCN { // (Swift)
    /* instance variables */
    Swift.Bool purchasing;
}

/* instance methods */
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)appear;
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (id)initWithCoder:(id)coder;

@end

#endif /* _TtC6Apollo35ApolloUltraManagementViewController_h */
