//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtC6Apollo23MediaPageViewController_h
#define _TtC6Apollo23MediaPageViewController_h
@import Foundation;

#include "UIPageViewControllerDataSource-Protocol.h"
#include "UIPageViewControllerDelegate-Protocol.h"

@class Swift.Bool, UIPageViewController, _$s10Foundation3URLVMn, _$sSDySi _$s10Foundation4UUIDVMn, _$sSDySiSSGSg, _$sSDySiSo7UIImageCG, _$sSa -> Apollo.GoodbyeWallpaperMetadata ?, _$sSa -> _$s10Foundation3URLVMn ?, _$sSdSg, _$sSi, _$sSiSg, _$sSo10ASCellNodeCSgXw, _$sSo10RDKGalleryCSg, _$sSo12GradientViewCSg, _$sSo18UIVisualEffectViewCSg, _$sSo22DACircularProgressViewC, _$sSo22UINavigationControllerCSgXw, _$sSo36UIPercentDrivenInteractiveTransitionCSg, _$sSo6UIViewCSg, _$sSo7RDKLinkCSg, _$sSo7UILabelCSg, _$sSo8UIButtonCSg, _$sypSg, __C.CGPoint ?, pollo.DualStateButtonNode ?, pollo.ImgurAlbum ?, pollo.MediaPageViewController.MediaViewerCloseMethod ?, pollo.MediaViewerAnimationController ?, pollo.XKCDComic ?;

@interface _TtC6Apollo23MediaPageViewController : UIPageViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate> { // (Swift)
    /* instance variables */
    _$s10Foundation3URLVMn url;
    _$sSa -> Apollo.GoodbyeWallpaperMetadata ? goodbyeWallpapers;
    _$sSDySiSo7UIImageCG thumbnails;
    _$sSiSg selectedThumbnailIndex;
    _$sSo7RDKLinkCSg link;
    _$sSdSg gifTimeOffset;
    _$sSo6UIViewCSg originView;
    _$sSo10ASCellNodeCSgXw originCellNode;
    _$sSo22UINavigationControllerCSgXw navigationControllerToPushCommentsOnto;
    _$sSa -> _$s10Foundation3URLVMn ? foundURLs;
    _$sSDySiSSGSg contentTypeHints;
    _Atomic pollo.ImgurAlbum ? foundImgurAlbum;
    _$sSo10RDKGalleryCSg foundRedditGallery;
    _Atomic pollo.XKCDComic ? foundXKCDComic;
    _$sSo22DACircularProgressViewC progressView;
    _$sSo8UIButtonCSg pageIndicatorButton;
    _$sSo8UIButtonCSg closeButton;
    _$sSo12GradientViewCSg upperGradientView;
    _Atomic pollo.MediaPageViewController.MediaViewerCloseMethod ? closeMethod;
    Swift.Bool inFocusMode;
    _$sSo36UIPercentDrivenInteractiveTransitionCSg interactionController;
    _Atomic pollo.DualStateButtonNode ? upvoteButton;
    _$sSo7UILabelCSg pointsLabel;
    _Atomic pollo.DualStateButtonNode ? downvoteButton;
    _$sSo8UIButtonCSg shareButton;
    _$sSo8UIButtonCSg commentsButton;
    _$sSo8UIButtonCSg moreButton;
    _$sSDySi _$s10Foundation4UUIDVMn galleryIndexesToTaskUUIDs;
    Swift.Bool hideStatusBar;
    _Atomic pollo.MediaViewerAnimationController ? presentationAnimationController;
    _Atomic pollo.MediaViewerAnimationController ? dismissalAnimationController;
    Swift.Bool isSPCAAlbum;
    Swift.Bool isGoodbyeWallpaperAlbum;
    _$sypSg _groupSession;
    _$sSi viewWillAppearCalls;
    _$sSo18UIVisualEffectViewCSg spcaVisualEffectView;
    _$sSo7UILabelCSg spcaTextLabel;
    _$sSo8UIButtonCSg spcaContinueButton;
    Swift.Bool hideHomeIndicator;
    Swift.Bool volumeNotificationCooldownPeriodActive;
    __C.CGPoint ? firstTouchLocation;
    _$sSiSg firstViewControllerIndex;
}

@property (nonatomic) _Bool isShowingIn3DTouchPreview;
@property (nonatomic) struct CGSize { double x0; double x1; } preferredContentSize;
@property (nonatomic, readonly) _Bool prefersStatusBarHidden;
@property (nonatomic, readonly) long long preferredStatusBarStyle;
@property (nonatomic, readonly) _Bool shouldAutorotate;
@property (nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
@property (nonatomic, readonly) _Bool prefersHomeIndicatorAutoHidden;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLayoutSubviews;
- (void)continueToSPCAAlbumButtonTappedWithSender:(id)sender;
- (void)volumeButtonPressedWithNotification:(id)notification;
- (id)pageViewController:(id)controller viewControllerBeforeViewController:(id)controller;
- (id)pageViewController:(id)controller viewControllerAfterViewController:(id)controller;
- (void)pageViewController:(id)controller willTransitionToViewControllers:(id)controllers;
- (void)pageViewController:(id)controller didFinishAnimating:(_Bool)animating previousViewControllers:(id)controllers transitionCompleted:(_Bool)completed;
- (void)closeButtonTapped:(id)tapped;
- (void)upvoteButtonTappedWithSender:(id)sender;
- (void)downvoteButtonTappedWithSender:(id)sender;
- (void)shareButtonTappedWithSender:(id)sender;
- (void)commentsButtonTapped:(id)tapped;
- (void)moreButtonTapped:(id)tapped;
- (void)viewSafeAreaInsetsDidChange;
- (id)initWithTransitionStyle:(long long)style navigationOrientation:(long long)orientation options:(id)options;

@end

#endif /* _TtC6Apollo23MediaPageViewController_h */
