//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef _TtP7Statsig16StatsigListening__Protocol_h
#define _TtP7Statsig16StatsigListening__Protocol_h
@import Foundation;

@protocol _TtP7Statsig16StatsigListening_

@required

/* required instance methods */
- (void)onInitialized:(id)initialized;
- (void)onUserUpdated:(id)updated;

@optional

@end

#endif /* _TtP7Statsig16StatsigListening__Protocol_h */
