//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASLayoutElementExtensibility_Protocol_h
#define ASLayoutElementExtensibility_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol ASLayoutElementExtensibility <NSObject>

@required

/* required instance methods */
- (void)setLayoutOptionExtensionBool:(_Bool)_bool atIndex:(int)index;
- (void)setLayoutOptionExtensionBool:(_Bool)_bool atIndex:(int)index;
- (_Bool)layoutOptionExtensionBoolAtIndex:(int)index;
- (_Bool)layoutOptionExtensionBoolAtIndex:(int)index;
- (void)setLayoutOptionExtensionInteger:(long long)integer atIndex:(int)index;
- (void)setLayoutOptionExtensionInteger:(long long)integer atIndex:(int)index;
- (long long)layoutOptionExtensionIntegerAtIndex:(int)index;
- (long long)layoutOptionExtensionIntegerAtIndex:(int)index;
- (void)setLayoutOptionExtensionEdgeInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets atIndex:(int)index;
- (void)setLayoutOptionExtensionEdgeInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets atIndex:(int)index;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })layoutOptionExtensionEdgeInsetsAtIndex:(int)index;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })layoutOptionExtensionEdgeInsetsAtIndex:(int)index;

@optional

@end

#endif /* ASLayoutElementExtensibility_Protocol_h */
