//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASLayoutElement_Protocol_h
#define ASLayoutElement_Protocol_h
@import Foundation;

#include "ASLayoutElementAsciiArtProtocol-Protocol.h"
#include "ASLayoutElementExtensibility-Protocol.h"
#include "ASTraitEnvironment-Protocol.h"

@class ASLayoutElementStyle;

@protocol ASLayoutElement <ASLayoutElementExtensibility, ASTraitEnvironment, ASLayoutElementAsciiArtProtocol>

@required

@property (nonatomic, readonly) unsigned char layoutElementType;
@property (nonatomic, readonly) ASLayoutElementStyle *style;

/* required instance methods */
- (id)sublayoutElements;
- (id)layoutThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)layoutThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits parentSize:(struct CGSize { double x0; double x1; })size;
- (id)calculateLayoutThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits;
- (id)calculateLayoutThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits restrictedToSize:(struct { struct { long long x0; double x1; } x0; struct { long long x0; double x1; } x1; struct { long long x0; double x1; } x2; struct { long long x0; double x1; } x3; struct { long long x0; double x1; } x4; struct { long long x0; double x1; } x5; })size relativeToParentSize:(struct CGSize { double x0; double x1; })size;
- (id)calculateLayoutThatFits:(struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })fits restrictedToSize:(struct { struct { long long x0; double x1; } x0; struct { long long x0; double x1; } x1; struct { long long x0; double x1; } x2; struct { long long x0; double x1; } x3; struct { long long x0; double x1; } x4; struct { long long x0; double x1; } x5; })size relativeToParentSize:(struct CGSize { double x0; double x1; })size;
- (_Bool)implementsLayoutMethod;

@optional

@end

#endif /* ASLayoutElement_Protocol_h */
