//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASTableDelegate_Protocol_h
#define ASTableDelegate_Protocol_h
@import Foundation;

#include "ASCommonTableViewDelegate-Protocol.h"
#include "NSObject-Protocol.h"

@protocol ASTableDelegate <ASCommonTableViewDelegate, NSObject>

@required

@optional

/* optional instance methods */
- (void)tableNode:(id)node willDisplayRowWithNode:(id)node;
- (void)tableNode:(id)node willDisplayRowWithNode:(id)node;
- (void)tableNode:(id)node didEndDisplayingRowWithNode:(id)node;
- (void)tableNode:(id)node didEndDisplayingRowWithNode:(id)node;
- (id)tableNode:(id)node willSelectRowAtIndexPath:(id)path;
- (id)tableNode:(id)node willSelectRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didSelectRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didSelectRowAtIndexPath:(id)path;
- (id)tableNode:(id)node willDeselectRowAtIndexPath:(id)path;
- (id)tableNode:(id)node willDeselectRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didDeselectRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didDeselectRowAtIndexPath:(id)path;
- (_Bool)tableNode:(id)node shouldHighlightRowAtIndexPath:(id)path;
- (_Bool)tableNode:(id)node shouldHighlightRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didHighlightRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didHighlightRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didUnhighlightRowAtIndexPath:(id)path;
- (void)tableNode:(id)node didUnhighlightRowAtIndexPath:(id)path;
- (_Bool)tableNode:(id)node shouldShowMenuForRowAtIndexPath:(id)path;
- (_Bool)tableNode:(id)node shouldShowMenuForRowAtIndexPath:(id)path;
- (_Bool)tableNode:(id)node canPerformAction:(SEL)action forRowAtIndexPath:(id)path withSender:(id)sender;
- (_Bool)tableNode:(id)node canPerformAction:(SEL)action forRowAtIndexPath:(id)path withSender:(id)sender;
- (void)tableNode:(id)node performAction:(SEL)action forRowAtIndexPath:(id)path withSender:(id)sender;
- (void)tableNode:(id)node performAction:(SEL)action forRowAtIndexPath:(id)path withSender:(id)sender;
- (struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tableNode:(id)node constrainedSizeForRowAtIndexPath:(id)path;
- (struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tableNode:(id)node constrainedSizeForRowAtIndexPath:(id)path;
- (void)tableNode:(id)node willBeginBatchFetchWithContext:(id)context;
- (void)tableNode:(id)node willBeginBatchFetchWithContext:(id)context;
- (_Bool)shouldBatchFetchForTableNode:(id)node;
- (_Bool)shouldBatchFetchForTableNode:(id)node;
- (void)tableView:(id)view willDisplayNode:(id)node forRowAtIndexPath:(id)path;
- (void)tableView:(id)view willDisplayNode:(id)node forRowAtIndexPath:(id)path;
- (void)tableView:(id)view didEndDisplayingNode:(id)node forRowAtIndexPath:(id)path;
- (void)tableView:(id)view didEndDisplayingNode:(id)node forRowAtIndexPath:(id)path;
- (void)tableView:(id)view willBeginBatchFetchWithContext:(id)context;
- (void)tableView:(id)view willBeginBatchFetchWithContext:(id)context;
- (_Bool)shouldBatchFetchForTableView:(id)view;
- (_Bool)shouldBatchFetchForTableView:(id)view;
- (struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tableView:(id)view constrainedSizeForRowAtIndexPath:(id)path;
- (struct { struct CGSize { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })tableView:(id)view constrainedSizeForRowAtIndexPath:(id)path;
- (void)tableView:(id)view willDisplayNodeForRowAtIndexPath:(id)path;
- (void)tableView:(id)view willDisplayNodeForRowAtIndexPath:(id)path;

@end

#endif /* ASTableDelegate_Protocol_h */
