//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef ASTextNodeDelegate_Protocol_h
#define ASTextNodeDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol ASTextNodeDelegate <NSObject>

@required

@optional

/* optional instance methods */
- (void)textNode:(id)node tappedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)textNode:(id)node tappedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)textNode:(id)node longPressedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)textNode:(id)node longPressedLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point textRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)textNodeTappedTruncationToken:(id)token;
- (_Bool)textNode:(id)node shouldHighlightLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)textNode:(id)node shouldHighlightLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)textNode:(id)node shouldLongPressLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;
- (_Bool)textNode:(id)node shouldLongPressLinkAttribute:(id)attribute value:(id)value atPoint:(struct CGPoint { double x0; double x1; })point;

@end

#endif /* ASTextNodeDelegate_Protocol_h */
