//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGAppHangDetector_h
#define BSGAppHangDetector_h
@import Foundation;

#include "BSGAppHangDetectorDelegate-Protocol.h"

@class NSObject;
@protocol OS_dispatch_semaphore;

@interface BSGAppHangDetector : NSObject {
    /* instance variables */
    _Bool _shouldStop;
    id <BSGAppHangDetectorDelegate> _delegate;
    struct __CFRunLoopObserver * _observer;
    unsigned long long _processingDeadline;
    NSObject<OS_dispatch_semaphore> *_processingStarted;
    NSObject<OS_dispatch_semaphore> *_processingFinished;
}

/* instance methods */

@end

#endif /* BSGAppHangDetector_h */
