//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGEventUploadOperationDelegate_Protocol_h
#define BSGEventUploadOperationDelegate_Protocol_h
@import Foundation;

#include "BugsnagConfiguration.h"
#include "BugsnagNotifier.h"
#include "NSObject-Protocol.h"

@protocol BSGEventUploadOperationDelegate <NSObject>

@required

@property (readonly, nonatomic) BugsnagConfiguration *configuration;
@property (readonly, nonatomic) BugsnagNotifier *notifier;

/* required instance methods */
- (void)storeEventPayload:(id)payload;

@optional

@end

#endif /* BSGEventUploadOperationDelegate_Protocol_h */
