//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGEventUploadObjectOperation_h
#define BSGEventUploadObjectOperation_h
@import Foundation;

#include "BSGEventUploadOperation.h"
#include "BugsnagEvent.h"

@interface BSGEventUploadObjectOperation : BSGEventUploadOperation {
    /* instance variables */
    BugsnagEvent *_event;
}

/* instance methods */
- (id)loadEventAndReturnError:(id *)error;
- (void)prepareForRetry:(id)retry HTTPBodySize:(unsigned long long)size;
- (id)name;

@end

#endif /* BSGEventUploadObjectOperation_h */
