//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGInternalErrorReporter_h
#define BSGInternalErrorReporter_h
@import Foundation;

@class NSObject, NSString, NSURL, NSURLSession;

@interface BSGInternalErrorReporter : NSObject {
    /* instance variables */
    NSString *_apiKey;
    NSURL *_endpoint;
    NSURLSession *_session;
}

/* instance methods */
- (void)reportErrorWithClass:(id)_class context:(id)context message:(id)message diagnostics:(id)diagnostics;

@end

#endif /* BSGInternalErrorReporter_h */
