//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGNotificationBreadcrumbs_h
#define BSGNotificationBreadcrumbs_h
@import Foundation;

#include "BSGBreadcrumbSink-Protocol.h"
#include "BugsnagConfiguration.h"

@class NSDictionary, NSNotificationCenter, NSObject;

@interface BSGNotificationBreadcrumbs : NSObject {
    /* instance variables */
    BugsnagConfiguration *_configuration;
    id <BSGBreadcrumbSink> _breadcrumbSink;
    NSNotificationCenter *_notificationCenter;
    NSNotificationCenter *_workspaceNotificationCenter;
    NSDictionary *_notificationNameMap;
}

/* instance methods */
- (void)dealloc;
- (void)addBreadcrumbForNotification:(id)notification;
- (void)addBreadcrumbForTableViewNotification:(id)notification;
- (void)addBreadcrumbForMenuItemNotification:(id)notification;
- (void)addBreadcrumbForControlNotification:(id)notification;
- (void)orientationDidChange:(id)change;
- (void)thermalStateDidChange:(id)change;

@end

#endif /* BSGNotificationBreadcrumbs_h */
