//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BSGSessionUploader_h
#define BSGSessionUploader_h
@import Foundation;

#include "BugsnagConfiguration.h"
#include "BugsnagNotifier.h"

@class NSMutableSet, NSObject;

@interface BSGSessionUploader : NSObject {
    /* instance variables */
    BugsnagNotifier *_notifier;
    NSMutableSet *_activeIds;
    BugsnagConfiguration *_config;
}

/* instance methods */

@end

#endif /* BSGSessionUploader_h */
