//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagError_h
#define BugsnagError_h
@import Foundation;

@class NSArray, NSObject, NSString;

@interface BugsnagError : NSObject {
    /* instance variables */
    NSString *_typeString;
}

@property (copy, nonatomic) NSString *errorClass;
@property (copy, nonatomic) NSString *errorMessage;
@property (copy, nonatomic) NSArray *stacktrace;
@property (nonatomic) unsigned long long type;

/* class methods */
+ (id)errorFromJson:(id)json;

/* instance methods */
- (id)initWithErrorClass:(id)_class errorMessage:(id)message errorType:(unsigned long long)type stacktrace:(id)stacktrace;

@end

#endif /* BugsnagError_h */
