//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagConfiguration_h
#define BugsnagConfiguration_h
@import Foundation;

#include "BSGFeatureFlagStore.h"
#include "BugsnagEndpointConfiguration.h"
#include "BugsnagErrorTypes.h"
#include "BugsnagFeatureFlagStore-Protocol.h"
#include "BugsnagMetadata.h"
#include "BugsnagMetadataStore-Protocol.h"
#include "BugsnagNotifier.h"
#include "BugsnagUser.h"
#include "NSCopying-Protocol.h"

@class NSMutableArray, NSMutableSet, NSObject, NSSet, NSString, NSURLSession;

@interface BugsnagConfiguration : NSObject <NSCopying, BugsnagFeatureFlagStore, BugsnagMetadataStore> {
    /* instance variables */
    BSGFeatureFlagStore *_featureFlagStore;
    BugsnagMetadata *_metadata;
    NSMutableSet *_plugins;
}

@property (retain, nonatomic) BugsnagNotifier *notifier;
@property (retain, nonatomic) NSMutableArray *onBreadcrumbBlocks;
@property (retain, nonatomic) NSMutableArray *onSendBlocks;
@property (retain, nonatomic) NSMutableArray *onSessionBlocks;
@property (copy, nonatomic) NSString *apiKey;
@property (copy, nonatomic) NSString *releaseStage;
@property (copy, nonatomic) NSSet *enabledReleaseStages;
@property (copy, nonatomic) NSSet *redactedKeys;
@property (copy, nonatomic) NSSet *discardClasses;
@property (copy) NSString *context;
@property (copy, nonatomic) NSString *appVersion;
@property (retain, nonatomic) NSURLSession *session;
@property (nonatomic) long long sendThreads;
@property (nonatomic) void * /* function */ onCrashHandler;
@property (nonatomic) _Bool autoDetectErrors;
@property (nonatomic) unsigned long long appHangThresholdMillis;
@property (nonatomic) _Bool reportBackgroundAppHangs;
@property (nonatomic) _Bool autoTrackSessions;
@property (nonatomic) unsigned long long launchDurationMillis;
@property (nonatomic) _Bool sendLaunchCrashesSynchronously;
@property (nonatomic) _Bool attemptDeliveryOnCrash;
@property (nonatomic) unsigned long long enabledBreadcrumbTypes;
@property (copy, nonatomic) NSString *bundleVersion;
@property (copy, nonatomic) NSString *appType;
@property (nonatomic) unsigned long long maxPersistedEvents;
@property (nonatomic) unsigned long long maxPersistedSessions;
@property (nonatomic) unsigned long long maxBreadcrumbs;
@property (nonatomic) unsigned long long maxStringValueLength;
@property (nonatomic) _Bool persistUser;
@property (retain, nonatomic) BugsnagErrorTypes *enabledErrorTypes;
@property (copy, nonatomic) BugsnagEndpointConfiguration *endpoints;
@property (readonly, retain, nonatomic) BugsnagUser *user;
@property (nonatomic) unsigned long long telemetry;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)loadConfig;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initWithApiKey:(id)key;
- (void)setUser:(id)user withEmail:(id)email andName:(id)name;
- (id)addOnSendErrorBlock:(id /* block */)block;
- (void)removeOnSendError:(id)error;
- (void)removeOnSendErrorBlock:(id /* block */)block;
- (id)addOnSessionBlock:(id /* block */)block;
- (void)removeOnSession:(id)session;
- (void)removeOnSessionBlock:(id /* block */)block;
- (id)addOnBreadcrumbBlock:(id /* block */)block;
- (void)removeOnBreadcrumb:(id)breadcrumb;
- (void)removeOnBreadcrumbBlock:(id /* block */)block;
- (void)addPlugin:(id)plugin;
- (void)addFeatureFlagWithName:(id)name variant:(id)variant;
- (void)addFeatureFlagWithName:(id)name;
- (void)addFeatureFlags:(id)flags;
- (void)clearFeatureFlagWithName:(id)name;
- (void)clearFeatureFlags;
- (void)addMetadata:(id)metadata toSection:(id)section;
- (void)addMetadata:(id)metadata withKey:(id)key toSection:(id)section;
- (id)getMetadataFromSection:(id)section withKey:(id)key;
- (id)getMetadataFromSection:(id)section;
- (void)clearMetadataFromSection:(id)section;
- (void)clearMetadataFromSection:(id)section withKey:(id)key;

@end

#endif /* BugsnagConfiguration_h */
