//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagEvent_h
#define BugsnagEvent_h
@import Foundation;

#include "BSGFeatureFlagStore.h"
#include "BugsnagAppWithState.h"
#include "BugsnagDeviceWithState.h"
#include "BugsnagFeatureFlagStore-Protocol.h"
#include "BugsnagHandledState.h"
#include "BugsnagMetadata.h"
#include "BugsnagMetadataStore-Protocol.h"
#include "BugsnagSession.h"
#include "BugsnagUser.h"

@class NSArray, NSDictionary, NSObject, NSString;

@interface BugsnagEvent : NSObject <BugsnagFeatureFlagStore, BugsnagMetadataStore> {
    /* instance variables */
    NSString *_codeBundleId;
    NSDictionary *_customException;
    unsigned long long _depth;
    NSString *_deviceAppHash;
    NSArray *_enabledReleaseStages;
    BugsnagHandledState *_handledState;
    BugsnagMetadata *_metadata;
    NSString *_releaseStage;
    BugsnagSession *_session;
    NSDictionary *_usage;
}

@property (retain, nonatomic) BSGFeatureFlagStore *featureFlagStore;
@property (copy, nonatomic) NSString *context;
@property (nonatomic) unsigned long long severity;
@property (copy, nonatomic) NSArray *errors;
@property (copy, nonatomic) NSString *groupingHash;
@property (copy, nonatomic) NSArray *breadcrumbs;
@property (readonly, nonatomic) NSArray *featureFlags;
@property (copy, nonatomic) NSString *apiKey;
@property (readonly, nonatomic) BugsnagDeviceWithState *device;
@property (readonly, nonatomic) BugsnagAppWithState *app;
@property (nonatomic) _Bool unhandled;
@property (copy, nonatomic) NSArray *threads;
@property (retain, nonatomic) id originalError;
@property (readonly, nonatomic) BugsnagUser *user;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithApp:(id)app device:(id)device handledState:(id)state user:(id)user metadata:(id)metadata breadcrumbs:(id)breadcrumbs errors:(id)errors threads:(id)threads session:(id)session;
- (id)initWithJson:(id)json;
- (void)attachCustomStacktrace:(id)stacktrace withType:(id)type;
- (void)setUser:(id)user withEmail:(id)email andName:(id)name;
- (id)toJsonWithRedactedKeys:(id)keys;
- (void)symbolicateIfNeeded;
- (void)addFeatureFlagWithName:(id)name variant:(id)variant;
- (void)addFeatureFlagWithName:(id)name;
- (void)addFeatureFlags:(id)flags;
- (void)clearFeatureFlagWithName:(id)name;
- (void)clearFeatureFlags;
- (void)addMetadata:(id)metadata toSection:(id)section;
- (void)addMetadata:(id)metadata withKey:(id)key toSection:(id)section;
- (id)getMetadataFromSection:(id)section withKey:(id)key;
- (id)getMetadataFromSection:(id)section;
- (void)clearMetadataFromSection:(id)section;
- (void)clearMetadataFromSection:(id)section withKey:(id)key;

@end

#endif /* BugsnagEvent_h */
