//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagDeviceWithState_h
#define BugsnagDeviceWithState_h
@import Foundation;

#include "BugsnagDevice.h"

@class NSDate, NSNumber, NSString;

@interface BugsnagDeviceWithState : BugsnagDevice

@property (retain, nonatomic) NSNumber *freeDisk;
@property (retain, nonatomic) NSNumber *freeMemory;
@property (copy, nonatomic) NSString *orientation;
@property (retain, nonatomic) NSDate *time;

/* class methods */
+ (id)deviceFromJson:(id)json;
+ (id)deviceWithKSCrashReport:(id)report;

/* instance methods */
- (id)toDictionary;

@end

#endif /* BugsnagDeviceWithState_h */
