//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagBreadcrumbs_h
#define BugsnagBreadcrumbs_h
@import Foundation;

#include "BugsnagConfiguration.h"

@class NSObject, NSString;

@interface BugsnagBreadcrumbs : NSObject

@property (readonly, nonatomic) NSString *breadcrumbsPath;
@property (retain, nonatomic) BugsnagConfiguration *config;
@property (nonatomic) unsigned int nextFileNumber;
@property (nonatomic) unsigned int maxBreadcrumbs;

/* instance methods */

@end

#endif /* BugsnagBreadcrumbs_h */
