//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagMetadata_h
#define BugsnagMetadata_h
@import Foundation;

#include "BugsnagMetadataStore-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSData, NSMutableArray, NSMutableDictionary, NSObject, NSString;

@interface BugsnagMetadata : NSObject <NSCopying, BugsnagMetadataStore> {
    /* instance variables */
    NSMutableArray *_stateEventBlocks;
    char * * _buffer;
    NSString *_file;
    NSData *_pendingWrite;
    id /* block */ _observer;
}

@property (readonly, nonatomic) NSMutableDictionary *dictionary;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithDictionary:(id)dictionary;
- (id)toDictionary;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)addMetadata:(id)metadata withKey:(id)key toSection:(id)section;
- (void)addMetadata:(id)metadata toSection:(id)section;
- (id)getMetadataFromSection:(id)section;
- (id)getMetadataFromSection:(id)section withKey:(id)key;
- (void)clearMetadataFromSection:(id)section;
- (void)clearMetadataFromSection:(id)section withKey:(id)key;
- (void)setStorageBuffer:(char * *)buffer file:(id)file;
- (void)writeData:(id)data toBuffer:(char * *)buffer;

@end

#endif /* BugsnagMetadata_h */
