//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagDevice_h
#define BugsnagDevice_h
@import Foundation;

@class NSDictionary, NSNumber, NSObject, NSString;

@interface BugsnagDevice : NSObject

@property (nonatomic) _Bool jailbroken;
@property (copy, nonatomic) NSString *id;
@property (copy, nonatomic) NSString *locale;
@property (copy, nonatomic) NSString *manufacturer;
@property (copy, nonatomic) NSString *model;
@property (copy, nonatomic) NSString *modelNumber;
@property (copy, nonatomic) NSString *osName;
@property (copy, nonatomic) NSString *osVersion;
@property (copy, nonatomic) NSDictionary *runtimeVersions;
@property (retain, nonatomic) NSNumber *totalMemory;

/* class methods */
+ (id)deserializeFromJson:(id)json;
+ (id)deviceWithKSCrashReport:(id)report;
+ (void)populateFields:(id)fields dictionary:(id)dictionary;

/* instance methods */
- (id)toDictionary;
- (void)appendRuntimeInfo:(id)info;

@end

#endif /* BugsnagDevice_h */
