//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef BugsnagAppWithState_h
#define BugsnagAppWithState_h
@import Foundation;

#include "BugsnagApp.h"

@class NSNumber;

@interface BugsnagAppWithState : BugsnagApp

@property (retain, nonatomic) NSNumber *duration;
@property (retain, nonatomic) NSNumber *durationInForeground;
@property (nonatomic) _Bool inForeground;
@property (nonatomic) _Bool isLaunching;

/* class methods */
+ (id)appFromJson:(id)json;
+ (id)appWithDictionary:(id)dictionary config:(id)config codeBundleId:(id)id;

/* instance methods */
- (id)toDict;

@end

#endif /* BugsnagAppWithState_h */
