//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef Bugsnag_h
#define Bugsnag_h
@import Foundation;

#include "BugsnagClassLevelMetadataStore-Protocol.h"

@class NSObject, NSString;

@interface Bugsnag : NSObject <BugsnagClassLevelMetadataStore>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)start;
+ (id)startWithApiKey:(id)key;
+ (id)startWithConfiguration:(id)configuration;
+ (_Bool)isStarted;
+ (id)client;
+ (_Bool)appDidCrashLastLaunch;
+ (id)lastRunInfo;
+ (void)markLaunchCompleted;
+ (void)notify:(id)notify;
+ (void)notify:(id)notify block:(id /* block */)block;
+ (void)notifyError:(id)error;
+ (void)notifyError:(id)error block:(id /* block */)block;
+ (_Bool)bugsnagReadyForInternalCalls;
+ (void)leaveBreadcrumbWithMessage:(id)message;
+ (void)leaveBreadcrumbForNotificationName:(id)name;
+ (void)leaveBreadcrumbWithMessage:(id)message metadata:(id)metadata andType:(unsigned long long)type;
+ (void)leaveNetworkRequestBreadcrumbForTask:(id)task metrics:(id)metrics;
+ (id)breadcrumbs;
+ (void)startSession;
+ (void)pauseSession;
+ (_Bool)resumeSession;
+ (void)addFeatureFlagWithName:(id)name variant:(id)variant;
+ (void)addFeatureFlagWithName:(id)name;
+ (void)addFeatureFlags:(id)flags;
+ (void)clearFeatureFlagWithName:(id)name;
+ (void)clearFeatureFlags;
+ (void)addMetadata:(id)metadata withKey:(id)key toSection:(id)section;
+ (void)addMetadata:(id)metadata toSection:(id)section;
+ (id)getMetadataFromSection:(id)section;
+ (id)getMetadataFromSection:(id)section withKey:(id)key;
+ (void)clearMetadataFromSection:(id)section;
+ (void)clearMetadataFromSection:(id)section withKey:(id)key;
+ (void)setContext:(id)context;
+ (id)context;
+ (id)user;
+ (void)setUser:(id)user withEmail:(id)email andName:(id)name;
+ (id)addOnSessionBlock:(id /* block */)block;
+ (void)removeOnSession:(id)session;
+ (void)removeOnSessionBlock:(id /* block */)block;
+ (id)addOnBreadcrumbBlock:(id /* block */)block;
+ (void)removeOnBreadcrumb:(id)breadcrumb;
+ (void)removeOnBreadcrumbBlock:(id /* block */)block;

@end

#endif /* Bugsnag_h */
