//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef DACircularProgressLayer_h
#define DACircularProgressLayer_h
@import Foundation;

@class CALayer, UIColor;

@interface DACircularProgressLayer : CALayer

@property (retain, nonatomic) UIColor *trackTintColor;
@property (retain, nonatomic) UIColor *progressTintColor;
@property (retain, nonatomic) UIColor *innerTintColor;
@property (nonatomic) long long roundedCorners;
@property (nonatomic) double thicknessRatio;
@property (nonatomic) double progress;
@property (nonatomic) long long clockwiseProgress;
@property (nonatomic) _Bool homescreenStyleBorder;

/* class methods */
+ (_Bool)needsDisplayForKey:(id)key;

/* instance methods */
- (void)drawInContext:(struct CGContext *)context;

@end

#endif /* DACircularProgressLayer_h */
