//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef FeatureGate_h
#define FeatureGate_h
@import Foundation;

@class NSArray, NSObject, NSString, pollo.SpinnerCellNode;

@interface FeatureGate : NSObject { // (Swift)
    /* instance variables */
    _Atomic pollo.SpinnerCellNode gate;
}

@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSString *ruleID;
@property (nonatomic, readonly) _Bool value;
@property (nonatomic, readonly) NSArray *secondaryExposures;

/* class methods */
+ (id)fromData:(id)data;

/* instance methods */
- (id)toData;
- (id)init;

@end

#endif /* FeatureGate_h */
