//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef JumbopolloIcon_h
#define JumbopolloIcon_h
@import Foundation;

@class INObject;

@interface JumbopolloIcon : INObject // (Swift)

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithIdentifier:(id)identifier displayString:(id)string pronunciationHint:(id)hint;
- (id)initWithCoder:(id)coder;

@end

#endif /* JumbopolloIcon_h */
