//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef JumbopolloIntent_h
#define JumbopolloIntent_h
@import Foundation;

#include "JumbopolloIcon.h"

@class INIntent;

@interface JumbopolloIntent : INIntent // (Swift)

@property (nonatomic, retain) JumbopolloIcon *icon;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;

@end

#endif /* JumbopolloIntent_h */
