//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef LockScreenSubredditIntentHandling_Protocol_h
#define LockScreenSubredditIntentHandling_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol LockScreenSubredditIntentHandling <NSObject>

@required

@optional

/* optional instance methods */
- (void)confirmLockScreenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)confirmLockScreenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)handleLockScreenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)handleLockScreenSubreddit:(id)subreddit completion:(id /* block */)completion;

@end

#endif /* LockScreenSubredditIntentHandling_Protocol_h */
