//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef NSString_StripHTML_h
#define NSString_StripHTML_h
@import Foundation;

@interface NSString (StripHTML)

/* instance methods */
- (id)subredditSortNamer;
- (id)stripHTMLToNumberOfLines:(long long)lines;
- (id)stringByReplacingHTMLEntities;

@end

#endif /* NSString_StripHTML_h */
