//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OpenMultiredditIntentHandling_Protocol_h
#define OpenMultiredditIntentHandling_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol OpenMultiredditIntentHandling <NSObject>

@required

/* required instance methods */
- (void)handleOpenMultireddit:(id)multireddit completion:(id /* block */)completion;
- (void)handleOpenMultireddit:(id)multireddit completion:(id /* block */)completion;
- (void)resolveMultiredditNameForOpenMultireddit:(id)multireddit withCompletion:(id /* block */)completion;
- (void)resolveMultiredditNameForOpenMultireddit:(id)multireddit withCompletion:(id /* block */)completion;

@optional

/* optional instance methods */
- (void)confirmOpenMultireddit:(id)multireddit completion:(id /* block */)completion;
- (void)confirmOpenMultireddit:(id)multireddit completion:(id /* block */)completion;

@end

#endif /* OpenMultiredditIntentHandling_Protocol_h */
