//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef OpenSubredditIntentHandling_Protocol_h
#define OpenSubredditIntentHandling_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol OpenSubredditIntentHandling <NSObject>

@required

/* required instance methods */
- (void)handleOpenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)handleOpenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)resolveSubredditForOpenSubreddit:(id)subreddit withCompletion:(id /* block */)completion;
- (void)resolveSubredditForOpenSubreddit:(id)subreddit withCompletion:(id /* block */)completion;

@optional

/* optional instance methods */
- (void)confirmOpenSubreddit:(id)subreddit completion:(id /* block */)completion;
- (void)confirmOpenSubreddit:(id)subreddit completion:(id /* block */)completion;

@end

#endif /* OpenSubredditIntentHandling_Protocol_h */
