//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PixelPalsHSBackgroundResolutionResult_h
#define PixelPalsHSBackgroundResolutionResult_h
@import Foundation;

@class INEnumResolutionResult;

@interface PixelPalsHSBackgroundResolutionResult : INEnumResolutionResult // (Swift)

/* class methods */
+ (id)successWithResolvedPixelPalsHSBackground:(long long)hsbackground;
+ (id)confirmationRequiredWithPixelPalsHSBackgroundToConfirm:(long long)confirm;

@end

#endif /* PixelPalsHSBackgroundResolutionResult_h */
