//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef PixelPalConfigIntent_h
#define PixelPalConfigIntent_h
@import Foundation;

@class INIntent, NSNumber;

@interface PixelPalConfigIntent : INIntent // (Swift)

@property (nonatomic) long long pixelPalType;
@property (nonatomic) long long actionType;
@property (nonatomic, retain) NSNumber *animate;
@property (nonatomic, retain) NSNumber *showBackground;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;

@end

#endif /* PixelPalConfigIntent_h */
