//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKComment_h
#define RDKComment_h
@import Foundation;

#include "RDKVotable.h"

@class NSArray, NSDate, NSDictionary, NSString;

@interface RDKComment : RDKVotable

@property (retain, nonatomic) NSArray *authorFlairRichtext;
@property (copy, nonatomic) NSString *authorFlairPlaintext;
@property (retain, nonatomic) NSDictionary *mediaMetadata;
@property (retain, nonatomic) NSString *collapsedReasonCode;
@property (copy, nonatomic) NSString *approvedBy;
@property (copy, nonatomic) NSString *author;
@property (copy, nonatomic) NSString *authorFullName;
@property (readonly, copy, nonatomic) NSString *linkAuthor;
@property (copy, nonatomic) NSString *bannedBy;
@property (retain, nonatomic) NSArray *authorFlair;
@property (retain, nonatomic) NSDate *authorCreatedUTC;
@property (copy, nonatomic) NSString *body;
@property (copy, nonatomic) NSString *bodyHTML;
@property (readonly, nonatomic) NSDictionary *snoomojiIDsToURLs;
@property (readonly, nonatomic) NSDictionary *inlineGiphyIDsToURLs;
@property (readonly, nonatomic) NSDictionary *inlineRedditImageIDsToURLs;
@property (readonly, nonatomic) NSDate *edited;
@property (nonatomic) _Bool isLocked;
@property (nonatomic) _Bool stickied;
@property (nonatomic) _Bool isAuthorCakeday;
@property (nonatomic) _Bool approved;
@property (nonatomic) _Bool removed;
@property (nonatomic) _Bool spam;
@property (nonatomic) _Bool ignoringReports;
@property (retain, nonatomic) NSArray *awards;
@property (nonatomic) unsigned long long gilded;
@property (readonly, nonatomic) _Bool archived;
@property (nonatomic) _Bool saved;
@property (readonly, copy, nonatomic) NSString *linkID;
@property (readonly, copy, nonatomic) NSString *linkTitle;
@property (nonatomic) unsigned long long totalReports;
@property (nonatomic) unsigned long long actualReports;
@property (retain, nonatomic) NSArray *userReports;
@property (retain, nonatomic) NSArray *moderatorReports;
@property (copy, nonatomic) NSString *modNote;
@property (copy, nonatomic) NSString *modReasonTitle;
@property (copy, nonatomic) NSString *modReasonBy;
@property (retain, nonatomic) NSDate *bannedAt;
@property (copy, nonatomic) NSString *parentID;
@property (nonatomic) _Bool moderatorNukedReplies;
@property (nonatomic) _Bool scoreHidden;
@property (readonly, nonatomic) unsigned long long controversiality;
@property (copy, nonatomic) NSString *subreddit;
@property (nonatomic) _Bool sendReplies;
@property (readonly, copy, nonatomic) NSString *subredditID;
@property (nonatomic) unsigned long long distinguishedStatus;
@property (nonatomic) unsigned long long distinguished;
@property (retain, nonatomic) NSArray *replies;
@property (nonatomic) _Bool collapsed;
@property (nonatomic) _Bool isFromBlockedUser;
@property (nonatomic) _Bool isBlockedUser;
@property (nonatomic) long long parentIndex;
@property (nonatomic) long long depth;
@property (nonatomic) long long displayedDepth;
@property (nonatomic) _Bool allowIndentation;
@property (nonatomic) long long index;
@property (readonly, copy, nonatomic) NSString *submissionContentText;
@property (readonly, copy, nonatomic) NSString *submissionContentHTML;
@property (readonly, copy, nonatomic) NSString *submissionLink;
@property (readonly, copy, nonatomic) NSString *submissionParent;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)repliesJSONTransformer;
+ (id)bannedByJSONTransformer;
+ (id)editedJSONTransformer;
+ (id)bannedAtJSONTransformer;
+ (id)distinguishedJSONTransformer;
+ (id)awardsJSONTransformer;
+ (id)authorFlairRichtextJSONTransformer;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (id)description;
- (_Bool)isDeleted;
- (_Bool)isModeratorRemoved;
- (id)thumbnailURLForInlineRedditImageWithURL:(id)url;
- (id)imageURLForInlineRedditImageWithID:(id)id;
- (id)thumbnailURLForInlineGiphyWithRedditURL:(id)url;
- (id)mp4OrGIFURLForInlineGiphyWithID:(id)id;
- (id)urlWithContext:(long long)context;
- (id)linkIDWithoutTypePrefix;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (_Bool)isApproved;
- (_Bool)isRemoved;
- (_Bool)isSpam;
- (_Bool)isArchived;

@end

#endif /* RDKComment_h */
