//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKFlair_h
#define RDKFlair_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSString, NSURL;

@interface RDKFlair : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (copy, nonatomic) NSString *flairType;
@property (copy, nonatomic) NSURL *imageURL;
@property (copy, nonatomic) NSString *text;
@property (copy, nonatomic) NSString *emojiLabel;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)imageURLJSONTransformer;
+ (id)textJSONTransformer;
+ (id)emojiLabelJSONTransformer;

/* instance methods */
- (id)initWithRawText:(id)text;

@end

#endif /* RDKFlair_h */
