//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKFlairOption_h
#define RDKFlairOption_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSArray, NSString;

@interface RDKFlairOption : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (nonatomic) _Bool isEditable;
@property (retain, nonatomic) NSArray *flairs;
@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *textRepresentation;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)flairsJSONTransformer;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* RDKFlairOption_h */
