//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKGalleryItem_h
#define RDKGalleryItem_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "RDKGalleryItemImage.h"

@class NSArray, NSObject, NSString, NSURL;

@interface RDKGalleryItem : NSObject <NSSecureCoding>

@property (copy, nonatomic) NSString *caption;
@property (nonatomic) long long identifier;
@property (copy, nonatomic) NSString *mediaIdentifier;
@property (copy, nonatomic) NSURL *outboundURL;
@property (copy, nonatomic) NSArray *previewImages;
@property (copy, nonatomic) RDKGalleryItemImage *image;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)initWithMediaMetadata:(id)metadata galleryData:(id)data;

@end

#endif /* RDKGalleryItem_h */
