//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKGallery_h
#define RDKGallery_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSArray, NSObject;

@interface RDKGallery : NSObject <NSSecureCoding>

@property (retain, nonatomic) NSArray *items;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithMediaMetadata:(id)metadata galleryData:(id)data;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* RDKGallery_h */
