//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKLinkPreviewMedia_h
#define RDKLinkPreviewMedia_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "RDKLinkPreviewItem.h"

@class MTLModel, NSArray;

@interface RDKLinkPreviewMedia : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) NSArray *images;
@property (retain, nonatomic) RDKLinkPreviewItem *sourceImage;
@property (retain, nonatomic) NSArray *MP4s;
@property (retain, nonatomic) RDKLinkPreviewItem *sourceMP4;
@property (retain, nonatomic) NSArray *GIFs;
@property (retain, nonatomic) RDKLinkPreviewItem *sourceGIF;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)allowedSecureCodingClassesByPropertyKey;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)imagesJSONTransformer;
+ (id)sourceImageJSONTransformer;
+ (id)MP4sJSONTransformer;
+ (id)sourceMP4JSONTransformer;
+ (id)GIFsJSONTransformer;
+ (id)sourceGIFJSONTransformer;

/* instance methods */

@end

#endif /* RDKLinkPreviewMedia_h */
