//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKLinkPreviewItem_h
#define RDKLinkPreviewItem_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSURL;

@interface RDKLinkPreviewItem : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (nonatomic) double width;
@property (nonatomic) double height;
@property (copy, nonatomic) NSURL *URL;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)URLJSONTransformer;

/* instance methods */

@end

#endif /* RDKLinkPreviewItem_h */
