//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKModmailMessage_h
#define RDKModmailMessage_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "RDKModmailAuthor.h"
#include "RDKModmailConversationInfo.h"

@class MTLModel, NSDate, NSString;

@interface RDKModmailMessage : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) RDKModmailAuthor *author;
@property (copy, nonatomic) NSString *bodyHTML;
@property (copy, nonatomic) NSString *bodyMarkdown;
@property (copy, nonatomic) NSDate *date;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) _Bool isInternal;
@property (retain, nonatomic) RDKModmailConversationInfo *conversationInfo;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)authorJSONTransformer;
+ (id)dateJSONTransformer;

/* instance methods */

@end

#endif /* RDKModmailMessage_h */
