//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKModmailConversation_h
#define RDKModmailConversation_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "RDKModmailConversationInfo.h"
#include "RDKModmailUser.h"

@class MTLModel, NSArray;

@interface RDKModmailConversation : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) RDKModmailConversationInfo *firstOptionConversationInfo;
@property (retain, nonatomic) RDKModmailConversationInfo *secondOptionConversationInfo;
@property (retain, nonatomic) RDKModmailConversationInfo *conversationInfo;
@property (retain, nonatomic) NSArray *messages;
@property (retain, nonatomic) NSArray *modActions;
@property (retain, nonatomic) RDKModmailUser *user;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)allowedSecureCodingClassesByPropertyKey;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)modActionsJSONTransformer;
+ (id)firstOptionConversationInfoJSONTransformer;
+ (id)secondOptionConversationInfoJSONTransformer;
+ (id)messagesJSONTransformer;
+ (id)userJSONTransformer;

/* instance methods */

@end

#endif /* RDKModmailConversation_h */
