//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKMultireddit_h
#define RDKMultireddit_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSArray, NSDate, NSString;

@interface RDKMultireddit : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (copy, nonatomic) NSString *ownerUsername;
@property (readonly, copy, nonatomic) NSString *name;
@property (readonly, copy, nonatomic) NSString *displayName;
@property (readonly, copy, nonatomic) NSString *path;
@property (readonly, copy, nonatomic) NSString *descriptionHTML;
@property (readonly, copy, nonatomic) NSString *descriptionMarkdown;
@property (readonly, copy, nonatomic) NSString *copiedFrom;
@property (retain, nonatomic) NSArray *subreddits;
@property (readonly, nonatomic) _Bool editable;
@property (readonly, nonatomic) unsigned long long visibility;
@property (readonly, nonatomic) NSDate *createdUTC;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)modelVersion;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)subredditsJSONTransformer;
+ (id)visibilityJSONTransformer;
+ (id)createdUTCJSONTransformer;

/* instance methods */
- (id)description;
- (id)username;
- (_Bool)isEditable;

@end

#endif /* RDKMultireddit_h */
