//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKModmailConversationInfo_h
#define RDKModmailConversationInfo_h
@import Foundation;

#include "IGListDiffable-Protocol.h"
#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "RDKModmailAuthor.h"

@class MTLModel, NSArray, NSDate, NSDictionary, NSString;

@interface RDKModmailConversationInfo : MTLModel <IGListDiffable, MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) NSArray *authors;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) _Bool isAutomoderator;
@property (nonatomic) _Bool isHighlighted;
@property (nonatomic) _Bool isInternal;
@property (nonatomic) _Bool isRepliable;
@property (retain, nonatomic) NSDate *lastModeratorUpdate;
@property (retain, nonatomic) NSDate *lastUnread;
@property (retain, nonatomic) NSDate *lastUpdated;
@property (retain, nonatomic) NSDate *lastUserUpdate;
@property (nonatomic) long long totalMessages;
@property (retain, nonatomic) NSDictionary *owner;
@property (retain, nonatomic) RDKModmailAuthor *participant;
@property (nonatomic) long long state;
@property (copy, nonatomic) NSString *subject;
@property (retain, nonatomic) NSArray *objIDs;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)allowedSecureCodingClassesByPropertyKey;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)authorsJSONTransformer;
+ (id)lastModeratorUpdateJSONTransformer;
+ (id)lastUnreadJSONTransformer;
+ (id)lastUpdatedJSONTransformer;
+ (id)lastUserUpdateJSONTransformer;
+ (id)participantJSONTransformer;

/* instance methods */
- (id)diffIdentifier;
- (_Bool)isEqualToDiffableObject:(id)object;

@end

#endif /* RDKModmailConversationInfo_h */
