//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKMedia_h
#define RDKMedia_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "RDKVideo.h"

@class MTLModel;

@interface RDKMedia : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) RDKVideo *video;

/* class methods */
+ (id)JSONKeyPathsByPropertyKey;
+ (id)videoJSONTransformer;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* RDKMedia_h */
