//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKModmailBanStatus_h
#define RDKModmailBanStatus_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSDate, NSString;

@interface RDKModmailBanStatus : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (retain, nonatomic) NSDate *endDate;
@property (nonatomic) _Bool isBanned;
@property (nonatomic) _Bool isPermanent;
@property (copy, nonatomic) NSString *reason;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)endDateJSONTransformer;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* RDKModmailBanStatus_h */
