//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKOAuthCredential_h
#define RDKOAuthCredential_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "RDKAccessToken.h"

@class NSObject, NSString, NSURL;

@interface RDKOAuthCredential : NSObject <NSSecureCoding>

@property (retain, nonatomic) NSString *clientIdentifier;
@property (retain, nonatomic) NSURL *redirectURI;
@property (retain, nonatomic) NSString *authorizationCode;
@property (retain, nonatomic) RDKAccessToken *accessToken;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* RDKOAuthCredential_h */
