//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKOperation_h
#define RDKOperation_h
@import Foundation;

@class NSDictionary, NSObject, NSString;

@interface RDKOperation : NSObject

@property (copy, nonatomic) NSString *method;
@property (copy, nonatomic) NSString *path;
@property (copy, nonatomic) NSDictionary *parameters;
@property (copy, nonatomic) id /* block */ completion;

/* class methods */
+ (id)operationWithMethod:(id)method path:(id)path parameters:(id)parameters completion:(id /* block */)completion;

/* instance methods */
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;

@end

#endif /* RDKOperation_h */
