//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKPollOption_h
#define RDKPollOption_h
@import Foundation;

#include "MTLJSONSerializing-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class MTLModel, NSString;

@interface RDKPollOption : MTLModel <MTLJSONSerializing, NSSecureCoding>

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *text;
@property (nonatomic) long long voteCount;

/* class methods */
+ (unsigned long long)modelVersion;
+ (_Bool)supportsSecureCoding;
+ (id)JSONKeyPathsByPropertyKey;

/* instance methods */

@end

#endif /* RDKPollOption_h */
