//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef RDKSubreddit_h
#define RDKSubreddit_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "RDKCreated.h"

@class NSDictionary, NSString, NSURL;

@interface RDKSubreddit : RDKCreated <NSSecureCoding>

@property (retain, nonatomic) NSURL *communityIconURL;
@property (retain, nonatomic) NSURL *iconImageURL;
@property (readonly, nonatomic) unsigned long long accountsActive;
@property (readonly, nonatomic) unsigned long long commentScoreHiddenDuration;
@property (readonly, copy, nonatomic) NSString *name;
@property (nonatomic) _Bool canCrosspostTo;
@property (readonly, copy, nonatomic) NSString *subredditDescription;
@property (readonly, copy, nonatomic) NSString *subredditDescriptionHTML;
@property (nonatomic) _Bool isEnrolledInNewModmail;
@property (copy, nonatomic) NSString *whitelistStatus;
@property (readonly, copy, nonatomic) NSString *publicDescription;
@property (readonly, nonatomic) NSURL *headerImageURL;
@property (readonly, copy, nonatomic) NSString *headerTitle;
@property (copy, nonatomic) NSString *redesignColorHexcode;
@property (copy, nonatomic) NSString *oldSiteColorHexcode;
@property (copy, nonatomic) NSString *userFlairID;
@property (nonatomic) _Bool showUserFlair;
@property (nonatomic) _Bool canSetFlair;
@property (readonly, copy, nonatomic) NSString *title;
@property (readonly, copy, nonatomic) NSString *URL;
@property (readonly, nonatomic) _Bool over18;
@property (readonly, nonatomic) _Bool contributor;
@property (readonly, nonatomic) _Bool moderator;
@property (readonly, nonatomic) _Bool subscriber;
@property (readonly, nonatomic) _Bool banned;
@property (readonly, nonatomic) unsigned long long totalSubscribers;
@property (readonly, nonatomic) unsigned long long acceptedSubmissionsType;
@property (nonatomic) _Bool allowImagePosts;
@property (nonatomic) _Bool allowVideoGIFPosts;
@property (nonatomic) _Bool allowVideoPosts;
@property (readonly, nonatomic) unsigned long long subredditType;
@property (readonly, nonatomic) unsigned long long commentSpamFilterStrength;
@property (readonly, nonatomic) unsigned long long linkSpamFilterStrength;
@property (readonly, nonatomic) unsigned long long selfPostSpamFilterStrength;
@property (copy, nonatomic) NSDictionary *rules;
@property (readonly, copy, nonatomic) NSString *submitLinkPostLabel;
@property (readonly, copy, nonatomic) NSString *submitTextPostLabel;
@property (readonly, copy, nonatomic) NSString *submitText;
@property (readonly, copy, nonatomic) NSString *submitTextHTML;
@property (readonly, nonatomic) _Bool trafficPagePubliclyAccessible;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)JSONTransformerForKey:(id)key;
+ (id)totalSubscribersJSONTransformer;
+ (id)accountsActiveJSONTransformer;
+ (id)canCrosspostToJSONTransformer;
+ (id)headerImageURLJSONTransformer;
+ (id)communityIconURLJSONTransformer;
+ (id)iconImageURLJSONTransformer;
+ (id)acceptedSubmissionsTypeJSONTransformer;
+ (id)subredditTypeJSONTransformer;
+ (id)showUserFlairJSONTransformer;
+ (id)commentSpamFilterStrengthJSONTransformer;
+ (id)linkSpamFilterStrengthJSONTransformer;
+ (id)selfPostSpamFilterStrengthJSONTransformer;
+ (id)spamFilterValueTransformer;
+ (id)rulesJSONTransformer;

/* instance methods */
- (id)description;
- (id)iconURL;
- (_Bool)isOver18;
- (_Bool)isContributor;
- (_Bool)isModerator;
- (_Bool)isSubscriber;
- (_Bool)isBanned;

@end

#endif /* RDKSubreddit_h */
