//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef StatsigOptions_h
#define StatsigOptions_h
@import Foundation;

@class NSObject, pollo.SpinnerCellNode;

@interface StatsigOptions : NSObject { // (Swift)
    /* instance variables */
    _Atomic pollo.SpinnerCellNode optionsInternal;
}

/* instance methods */
- (id)init;
- (id)initWithInitTimeout:(double)timeout;
- (id)initWithDisableCurrentVCLogging:(_Bool)vclogging;
- (id)initWithEnvironment:(id)environment;
- (id)initWithEnableAutoValueUpdate:(_Bool)update;
- (id)initWithOverrideStableID:(id)id;
- (id)initWithEnvironment:(id)environment overrideStableID:(id)id;
- (id)initWithEnableCacheByFile:(_Bool)file;
- (id)initWithInitTimeout:(double)timeout disableCurrentVCLogging:(_Bool)vclogging environment:(id)environment enableAutoValueUpdate:(_Bool)update overrideStableID:(id)id enableCacheByFile:(_Bool)file;

@end

#endif /* StatsigOptions_h */
