//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef StatsigUser_h
#define StatsigUser_h
@import Foundation;

@class NSObject, pollo.SpinnerCellNode;

@interface StatsigUser : NSObject { // (Swift)
    /* instance variables */
    _Atomic pollo.SpinnerCellNode user;
}

/* instance methods */
- (id)init;
- (id)initWithUserID:(id)id;
- (id)initWithCustomIDs:(id)ids;
- (id)initWithUserID:(id)id email:(id)email ip:(id)ip country:(id)country locale:(id)locale appVersion:(id)version custom:(id)custom privateAttributes:(id)attributes;
- (id)initWithUserID:(id)id email:(id)email ip:(id)ip country:(id)country locale:(id)locale appVersion:(id)version custom:(id)custom privateAttributes:(id)attributes customIDs:(id)ids;
- (id)getUserID;
- (id)getCustomIDs;
- (id)toDictionary;

@end

#endif /* StatsigUser_h */
