//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef UIViewControllerAnimatedTransitioning_Protocol_h
#define UIViewControllerAnimatedTransitioning_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol UIViewControllerAnimatedTransitioning <NSObject>

@required

/* required instance methods */
- (double)transitionDuration:(id)duration;
- (double)transitionDuration:(id)duration;
- (void)animateTransition:(id)transition;
- (void)animateTransition:(id)transition;

@optional

/* optional instance methods */
- (id)interruptibleAnimatorForTransition:(id)transition;
- (id)interruptibleAnimatorForTransition:(id)transition;
- (void)animationEnded:(_Bool)ended;

@end

#endif /* UIViewControllerAnimatedTransitioning_Protocol_h */
