//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
#ifndef WKNavigationDelegate_Protocol_h
#define WKNavigationDelegate_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol WKNavigationDelegate <NSObject>

@required

@optional

/* optional instance methods */
- (void)webView:(id)view decidePolicyForNavigationAction:(id)action decisionHandler:(id /* block */)handler;
- (void)webView:(id)view decidePolicyForNavigationAction:(id)action decisionHandler:(id /* block */)handler;
- (void)webView:(id)view decidePolicyForNavigationAction:(id)action preferences:(id)preferences decisionHandler:(id /* block */)handler;
- (void)webView:(id)view decidePolicyForNavigationAction:(id)action preferences:(id)preferences decisionHandler:(id /* block */)handler;
- (void)webView:(id)view decidePolicyForNavigationResponse:(id)response decisionHandler:(id /* block */)handler;
- (void)webView:(id)view decidePolicyForNavigationResponse:(id)response decisionHandler:(id /* block */)handler;
- (void)webView:(id)view didStartProvisionalNavigation:(id)navigation;
- (void)webView:(id)view didReceiveServerRedirectForProvisionalNavigation:(id)navigation;
- (void)webView:(id)view didFailProvisionalNavigation:(id)navigation withError:(id)error;
- (void)webView:(id)view didCommitNavigation:(id)navigation;
- (void)webView:(id)view didCommitNavigation:(id)navigation;
- (void)webView:(id)view didFinishNavigation:(id)navigation;
- (void)webView:(id)view didFinishNavigation:(id)navigation;
- (void)webView:(id)view didFailNavigation:(id)navigation withError:(id)error;
- (void)webView:(id)view didFailNavigation:(id)navigation withError:(id)error;
- (void)webView:(id)view didReceiveAuthenticationChallenge:(id)challenge completionHandler:(id /* block */)handler;
- (void)webView:(id)view didReceiveAuthenticationChallenge:(id)challenge completionHandler:(id /* block */)handler;
- (void)webViewWebContentProcessDidTerminate:(id)terminate;
- (void)webView:(id)view authenticationChallenge:(id)challenge shouldAllowDeprecatedTLS:(id /* block */)tls;
- (void)webView:(id)view navigationAction:(id)action didBecomeDownload:(id)download;
- (void)webView:(id)view navigationAction:(id)action didBecomeDownload:(id)download;
- (void)webView:(id)view navigationResponse:(id)response didBecomeDownload:(id)download;
- (void)webView:(id)view navigationResponse:(id)response didBecomeDownload:(id)download;

@end

#endif /* WKNavigationDelegate_Protocol_h */
