//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

protocol conformance Apollo.MediaConsumptionActivity : protocol descriptor for GroupActivity {
  /* resilient witnesses */
    base conformance descriptor for GroupActivity: Decodable
    base conformance descriptor for GroupActivity: Encodable
    method descriptor for static GroupActivity.activityIdentifier.getter
    method descriptor for GroupActivity.metadata.getter
    method descriptor for static GroupActivity._identifiable(by:)
}
