//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

protocol conformance Apollo.CrossOutPriceShape : protocol descriptor for Animatable {
  /* resilient witnesses */
    associated conformance descriptor for Animatable.Animatable.AnimatableData: VectorArithmetic
    associated type descriptor for Animatable.AnimatableData
    method descriptor for Animatable.animatableData.getter
    method descriptor for Animatable.animatableData.setter
    method descriptor for Animatable.animatableData.modify
    method descriptor for static Animatable._makeAnimatable(value:inputs:)
}
