//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

protocol conformance PreferredLineLimit.SplittingElement : protocol descriptor for Hashable {
  /* resilient witnesses */
    base conformance descriptor for Hashable: Equatable
    method descriptor for Hashable.hashValue.getter
    method descriptor for Hashable.hash(into:)
    method descriptor for Hashable._rawHashValue(seed:)
}
