//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

protocol conformance Markdown.TypedChildIndexPath : protocol descriptor for BidirectionalCollection {
  /* resilient witnesses */
    base conformance descriptor for BidirectionalCollection: Collection
    associated conformance descriptor for BidirectionalCollection.Collection.Indices: BidirectionalCollection
    associated conformance descriptor for BidirectionalCollection.Collection.SubSequence: BidirectionalCollection
    method descriptor for BidirectionalCollection.index(before:)
    method descriptor for BidirectionalCollection.formIndex(before:)
    method descriptor for BidirectionalCollection.index(_:offsetBy:)
    method descriptor for BidirectionalCollection.index(_:offsetBy:limitedBy:)
    method descriptor for BidirectionalCollection.distance(from:to:)
}
