//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.AlbumThumbnailsNode: ASDisplayNode {
  /* fields */
    let imgurAlbum: Apollo.ImgurAlbum ?
    let redditGallery: RDKGallery?
    let isNSFW: Swift.Bool
    let isSpoiler: Swift.Bool
    let thumbnailNode1: Apollo.TouchHintNetworkImageNode
    let thumbnailNode2: Apollo.TouchHintNetworkImageNode
    let thumbnailNode3: Apollo.TouchHintNetworkImageNode ?
    let totalImagesNode: Apollo.SmallInfoOverlayNode
    var obscuredContentInfoOverlayNode: Apollo.ObscuredContentInfoOverlayNode ?
  /* methods */
    // <stripped> func obscuredContentInfoOverlayNode.getter 
    // <stripped> func obscuredContentInfoOverlayNode.setter 
    // <stripped> func obscuredContentInfoOverlayNode.modify 
    // <stripped> static func init
    // <stripped> static func init
    func sub_1002ff8d0 // method (instance)
    // <stripped> func method (instance)
    func sub_1003013fc // method (instance)
}
