//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalsOverlayView: View {
    typealias Body = nominal type descriptor for SubscriptionView nominal type descriptor for NSNotificationCenter.Publisher nominal type descriptor for ModifiedContent nominal type descriptor for ZStack nominal type descriptor for TupleView opaque type descriptor for <<opaque return type of View.onTapGesture(count:perform:)>> nominal type descriptor for Color _$s_Qo__ACyACyAC -> nominal type descriptor for VStack _$syAEyACyACyAD -> nominal type descriptor for _ConditionalContent _$syAI -> Apollo.PixelPalsInfoView Apollo.PixelPalFoodView _$sG Apollo.PixelPalGameSelectionView _$sGG nominal type descriptor for _BackgroundStyleModifier _$sAFG nominal type descriptor for _ClipEffect nominal type descriptor for RoundedRectangle _$sGG_AI -> nominal type descriptor for EmptyView Apollo.PixelPalsChangePixelPalButton _$sGtGG nominal type descriptor for _PaddingLayout _$sG nominal type descriptor for _OffsetEffect _$sG nominal type descriptor for _FlexFrameLayout _$sGtGG nominal type descriptor for _SafeAreaRegionsIgnoringLayout
}
