//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalChooserView: View {
    typealias Body = nominal type descriptor for ModifiedContent nominal type descriptor for SubscriptionView nominal type descriptor for NSNotificationCenter.Publisher _$sAA -> nominal type descriptor for _ConditionalContent nominal type descriptor for AnyView nominal type descriptor for List nominal type descriptor for Never nominal type descriptor for TupleView _$syAAyAA -> nominal type descriptor for Section nominal type descriptor for EmptyView nominal type descriptor for HStack _$syAHyAA -> nominal type descriptor for Text nominal type descriptor for _PaddingLayout _$sG_ nominal type descriptor for Spacer _$sAA -> opaque type descriptor for <<opaque return type of View.labelsHidden()>> nominal type descriptor for Toggle _$syALG_Qo_ -> nominal type descriptor for _ValueActionModifier _$sSbGGtGGAJ nominal type descriptor for _TraitWritingModifier nominal type descriptor for ListRowBackgroundTraitKey _$sGGAY -> nominal type descriptor for ListRowInsetsTraitKey _$sGG_AHyAIyAJ nominal type descriptor for ForEach  empty-list Array -> Apollo.PixelPal _$sGSSAA -> nominal type descriptor for Button Apollo.PixelPalRow _$sGA_GGAJG_AIyAjAyAAyAAyAAyA7_yAKyAHyAA -> Apollo.PixelImage nominal type descriptor for _FrameLayout _$sG_ALtGGGAMGA2_G nominal type descriptor for _FlexFrameLayout _$sG nominal type descriptor for _BackgroundStyleModifier nominal type descriptor for Color _$sGGAJGtGSgAHyAAyAAyAIyAAyAAyAAyAAyAAyAnMG -> nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Font _$sSgGGA31_ -> nominal type descriptor for Text.Case _$sSgGGA31_yA24_SgGGAMGAA -> Apollo.LockAndHomeScreenWidgetPreviewView _$sA_GAJGA2_GA21_G_AIyA42_AAyAAyAAyAAyA7_yAKyALGGAMGA2_GA21_GA25_GANGtGSgtGGGA25_GG nominal type descriptor for _AppearanceActionModifier
}
