//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalNonCutOutDeviceAnnouncementView: View {
    typealias Body = nominal type descriptor for ModifiedContent _$syAAyAA -> nominal type descriptor for VStack nominal type descriptor for TupleView _$syAB -> nominal type descriptor for HStack _$syAAyAA -> nominal type descriptor for Text nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for TextAlignment _$sGG -> nominal type descriptor for _FlexFrameLayout _$sGGG_AAyAA -> nominal type descriptor for Image nominal type descriptor for _AspectRatioLayout _$sG nominal type descriptor for _ClipEffect nominal type descriptor for RoundedRectangle _$sGGAAyAAyAAyAiF -> nominal type descriptor for CGFloat _$sGG nominal type descriptor for _OpacityEffect _$sG nominal type descriptor for _PaddingLayout _$sGAByAC -> opaque type descriptor for <<opaque return type of View.buttonStyle<A>(_:)>> nominal type descriptor for Button _$syAEG_ -> Apollo.PixelPalAnnouncementContinueButtonStyle _$sQo__AAyA1_AZGtGGtGGAZG nominal type descriptor for _BackgroundModifier _$syAA -> nominal type descriptor for Color _$sASGGG nominal type descriptor for _AppearanceActionModifier
}
