//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalRow: View {
    typealias Body = opaque type descriptor for <<opaque return type of View.labelStyle<A>(_:)>> nominal type descriptor for Label nominal type descriptor for HStack nominal type descriptor for TupleView nominal type descriptor for VStack _$syAC -> nominal type descriptor for Text _$s_AEtGG_ nominal type descriptor for Spacer nominal type descriptor for ModifiedContent _$syAI -> nominal type descriptor for Image nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Image.Scale _$sGGAK -> nominal type descriptor for Color _$sSgGGtGGAIyAIyAJ nominal type descriptor for _ScaleEffect _$sG nominal type descriptor for _PaddingLayout _$sGG_ Apollo.CenteredLabelStyle _$sQo_
}
