//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.ChangelogBottomButtonArea: View {
    typealias Body = nominal type descriptor for ModifiedContent _$syAAyAA -> nominal type descriptor for VStack nominal type descriptor for _ConditionalContent _$syAA -> nominal type descriptor for ZStack _$syAC -> opaque type descriptor for <<opaque return type of View.progressViewStyle<A>(_:)>> nominal type descriptor for ProgressView nominal type descriptor for EmptyView _$sAFG_ -> nominal type descriptor for CircularProgressViewStyle _$sQo_AAyAA -> nominal type descriptor for Menu nominal type descriptor for Label nominal type descriptor for Text _$sAA -> nominal type descriptor for Image nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Font _$sSgGGG -> nominal type descriptor for TupleView nominal type descriptor for Button _$syAKyAlMGG_A2WtGGAN -> nominal type descriptor for Color _$sSgGG nominal type descriptor for _BackgroundModifier _$syAAyAAyAA -> nominal type descriptor for RoundedRectangle _$sA0_G nominal type descriptor for _PaddingLayout _$sGA5_GGGGGA5_GAT -> Apollo.ApolloContinueButton _$s_AUyALGtGGGA5_GA5_G nominal type descriptor for _BackgroundStyleModifier _$sAZG
}
