//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.ApolloContinueButton: View {
    typealias Body = opaque type descriptor for <<opaque return type of View.buttonStyle<A>(_:)>> nominal type descriptor for Button nominal type descriptor for Text _$sG_ -> Apollo.ApolloContinueButtonStyle _$sQo_
}
