//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.ApolloUltraSummonLocation {
    case proFeature: Apollo.ProFeature
    case changelog
    case ultraIcon
    case communityIcon
    case inboxNotifications
    case subredditWatcherSettings
    case trendingPostsSettings
    case subredditNotifications
    case settings
    case about
    case theming
    case remindMeIn
    case issueFixRefund
    case issueFixChurn
    case issueFixBilling
    case linkedWatcher
    case pixelPals
    case savedCategory
    case blackFriday
    case timePopup
    case christmas
    case easter
    case newCommentsHighlighter
    case indieSupport
    case subredditWeather
}
