//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalWidgetInstructionView: View {
    typealias Body = nominal type descriptor for HStack nominal type descriptor for TupleView nominal type descriptor for ModifiedContent _$syACyACyAC -> nominal type descriptor for Image nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Font _$sSgGGAE -> nominal type descriptor for Color _$sSgGG nominal type descriptor for _BackgroundModifier _$syAC -> nominal type descriptor for Circle._Inset _$sALGGGAQG_ nominal type descriptor for Text _$stG
}
