//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.WallpaperAlertView: View {
    typealias Body = nominal type descriptor for ModifiedContent _$syAA -> nominal type descriptor for ZStack nominal type descriptor for TupleView nominal type descriptor for Color  first-element-marker  -> nominal type descriptor for _ConditionalContent _$syAAyAA -> nominal type descriptor for VStack _$syACyAAyAA -> nominal type descriptor for Image nominal type descriptor for _PaddingLayout _$sG nominal type descriptor for _FlexFrameLayout _$sG_ nominal type descriptor for Text _$sAAyAL nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for TextAlignment _$sGGAA -> opaque type descriptor for <<opaque return type of View.buttonStyle<A>(_:)>> nominal type descriptor for Button _$syALG_ -> Apollo.NiceTappableButtonStyle _$sQo_AHGtGGAJGAHGAAyAAyAAyAFyACyAFyACyAAyAAyAA -> nominal type descriptor for Label _$syAlGGAM -> nominal type descriptor for Font _$sSgGGAMyADSgGG nominal type descriptor for _OpacityEffect _$sG_ALtGG_AlAyAAyAAyAAyAtJGAHGA7_G nominal type descriptor for _OverlayModifier _$syAA -> nominal type descriptor for ProgressView nominal type descriptor for EmptyView _$sA16_GA7_GGGSgAEyAA -> Apollo.WallpaperCarousel _$sAHGAA -> Apollo.WallpaperAllUpView _$sAHGGAEyAAyArJG nominal type descriptor for Spacer _$sGtGGAHGAHGAHGGtGGA14_yAAyAAyAAyAAyAFyACyA11__ARtGGAHGAHGAHG nominal type descriptor for _BackgroundStyleModifier _$sADGGSgG nominal type descriptor for _SafeAreaRegionsIgnoringLayout
}
