//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPals2AnnouncementHeaderView: View {
    typealias Body = nominal type descriptor for ModifiedContent _$syAAyAA -> nominal type descriptor for VStack nominal type descriptor for TupleView nominal type descriptor for HStack _$syAC -> Apollo.PixelHeaderImage _$s_AEtGG_AAyADyACyAE_A3EtGG nominal type descriptor for _PaddingLayout _$sGtGGAJG nominal type descriptor for _OverlayModifier _$syAAyAE nominal type descriptor for _OffsetEffect _$sGGG nominal type descriptor for _AppearanceActionModifier
}
