//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.LockAndHomeScreenWidgetPreviewView: View {
    typealias Body = nominal type descriptor for VStack nominal type descriptor for TupleView nominal type descriptor for ZStack _$syAB -> nominal type descriptor for ModifiedContent nominal type descriptor for Image nominal type descriptor for _AspectRatioLayout _$sG_ADyAG -> nominal type descriptor for _OpacityEffect _$sGtGG_ADyADyADyADyADyAAyAB -> nominal type descriptor for Text _$s_AAyAB -> Apollo.PixelPalWidgetInstructionView _$s_A5MtGGADyAL nominal type descriptor for _PaddingLayout _$sGAAyAByAM_A4MtGGtGG nominal type descriptor for _FixedSizeLayout _$sGAPGAPGAPG nominal type descriptor for _AppearanceActionModifier _$sGtG
}
