//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.PixelPalsWandGameView: View {
    typealias Body = nominal type descriptor for GeometryReader nominal type descriptor for ModifiedContent _$syAB -> nominal type descriptor for ZStack nominal type descriptor for TupleView nominal type descriptor for Color  first-element-marker  -> opaque type descriptor for <<opaque return type of View.gesture<A>(_:including:)>> _$syAByAByAByAByAB -> nominal type descriptor for Image nominal type descriptor for _ScaleEffect _$sG nominal type descriptor for _OffsetEffect _$sG nominal type descriptor for _PaddingLayout _$sG nominal type descriptor for _AnimationModifier _$sSdG nominal type descriptor for _AppearanceActionModifier _$sG_ nominal type descriptor for _ChangedGesture nominal type descriptor for DragGesture _$sGQo_ -> nominal type descriptor for VStack _$syAD -> nominal type descriptor for Spacer _$s_AByAByAF nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Font _$sSgGG -> nominal type descriptor for _OpacityEffect _$sGAB -> nominal type descriptor for Text _$sA1_G nominal type descriptor for Button _$sA3_GAWtGGtG nominal type descriptor for _SafeAreaRegionsIgnoringLayout _$sG nominal type descriptor for _BackgroundStyleModifier nominal type descriptor for Material _$sGG ->
}
