//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.ApolloDiscreteSlider: UISlider {
  /* fields */
    var incrementAmount: Int
    var steps: Int
    var trackColor: UIColor
    var discreteValueChangedHandler: ((_:))?
    var discreteValueChangeEndedHandler: ((_:))?
    var discreteValue: Int
  /* methods */
    // <stripped> func incrementAmount.getter 
    // <stripped> func incrementAmount.setter 
    // <stripped> func incrementAmount.modify 
    // <stripped> func steps.getter 
    // <stripped> func steps.setter 
    // <stripped> func steps.modify 
    // <stripped> func trackColor.getter 
    // <stripped> func trackColor.setter 
    // <stripped> func trackColor.modify 
    // <stripped> func discreteValueChangedHandler.getter 
    // <stripped> func discreteValueChangedHandler.setter 
    // <stripped> func discreteValueChangedHandler.modify 
    // <stripped> func discreteValueChangeEndedHandler.getter 
    // <stripped> func discreteValueChangeEndedHandler.setter 
    // <stripped> func discreteValueChangeEndedHandler.modify 
    // <stripped> func discreteValue.getter 
    // <stripped> func discreteValue.setter 
    // <stripped> func discreteValue.modify 
    // <stripped> func method (instance)
    func sub_100741a6c // method (instance)
}
