//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.RenamePixelPalButtonConfiguration: ButtonStyle {
    typealias Body = nominal type descriptor for ModifiedContent _$syAAyAAyAAyAAyAAyAA -> nominal type descriptor for ButtonStyleConfiguration.Label nominal type descriptor for _EnvironmentKeyWritingModifier _$sySiSgGGAC -> nominal type descriptor for Font _$sSgGGAC -> nominal type descriptor for Color _$sSgGG nominal type descriptor for _PaddingLayout _$sGAOG nominal type descriptor for _BackgroundModifier _$syAAyAK nominal type descriptor for _ClipEffect nominal type descriptor for RoundedRectangle _$sGGGG -> nominal type descriptor for _OpacityEffect
}
