//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

extension Apollo.FeatureIcon: View {
    typealias Body = nominal type descriptor for ModifiedContent nominal type descriptor for ZStack nominal type descriptor for _ConditionalContent _$syAAyAA -> nominal type descriptor for Image nominal type descriptor for _EnvironmentKeyWritingModifier nominal type descriptor for Color _$sSgGGAE -> nominal type descriptor for Font _$sSgGGAAyAAyAD nominal type descriptor for _AspectRatioLayout _$sG nominal type descriptor for _FrameLayout _$sGGGAP
}
