//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

struct __C.ASPrimitiveTraitCollection {
    var horizontalSizeClass: __C.UIUserInterfaceSizeClass
    var verticalSizeClass: __C.UIUserInterfaceSizeClass
    var displayScale: nominal type descriptor for CGFloat
    var displayGamut: __C.UIDisplayGamut
    var userInterfaceIdiom: __C.UIUserInterfaceIdiom
    var forceTouchCapability: __C.UIForceTouchCapability
    var layoutDirection: __C.UITraitEnvironmentLayoutDirection
    var userInterfaceStyle: __C.UIUserInterfaceStyle
    var preferredContentSizeCategory: nominal type descriptor for Unmanaged NSString
    var containerSize: __C.CGSize
    var userInterfaceLevel: __C.UIUserInterfaceLevel
    var accessibilityContrast: __C.UIAccessibilityContrast
    var legibilityWeight: __C.UILegibilityWeight
}
