//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.AutomaticEvents: NSObject {
  /* fields */
    var _minimumSessionDuration: nominal type descriptor for UInt64
    var _maximumSessionDuration: nominal type descriptor for UInt64
    var awaitingTransactions: [String : SKPaymentTransaction]
    let defaults: NSUserDefaults?
    var delegate: Mixpanel.AEDelegate ?
    var sessionLength: Double
    var sessionStartTime: Double
    var hasAddedObserver: Swift.Bool
    let awaitingTransactionsWriteLock: DispatchQueue
  /* methods */
    // <stripped> func _minimumSessionDuration.getter 
    // <stripped> func _minimumSessionDuration.setter 
    // <stripped> func _minimumSessionDuration.modify 
    // <stripped> func _maximumSessionDuration.getter 
    // <stripped> func _maximumSessionDuration.setter 
    // <stripped> func _maximumSessionDuration.modify 
    // <stripped> func awaitingTransactions.getter 
    // <stripped> func awaitingTransactions.setter 
    // <stripped> func awaitingTransactions.modify 
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func sessionLength.getter 
    // <stripped> func sessionLength.setter 
    // <stripped> func sessionLength.modify 
    // <stripped> func sessionStartTime.getter 
    // <stripped> func sessionStartTime.setter 
    // <stripped> func sessionStartTime.modify 
    // <stripped> func hasAddedObserver.getter 
    // <stripped> func hasAddedObserver.setter 
    // <stripped> func hasAddedObserver.modify 
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    func sub_1008f64f4 // method (instance)
    func sub_1008f6de8 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
