//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.AvailableAward.AwardKeys {
    case identifier
    case name
    case type
    case subType
    case coinPrice
    case awardDescription
    case isEnabled
    case icon32URL
    case icon128URL
    case iconLargeURL
}
