//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.AwardGiftingViewController: ASDKViewController<ASDisplayNode> {
  /* fields */
    let rootNode: ASDisplayNode
    let tableNode: ASTableNode
    let thingToAward: RDKThing
    let titleViewButton: UIButton
    let cancelBarButtonItem: UIBarButtonItem
    let infoBarButtonItem: UIBarButtonItem
    let spinner: UIActivityIndicatorView
    var balanceRefreshingTimer: NSTimer?
    var awardSections: Array empty-list Array -> Apollo.AvailableAward _$sGGSg
  /* methods */
    // <stripped> func balanceRefreshingTimer.getter 
    // <stripped> func balanceRefreshingTimer.setter 
    // <stripped> func balanceRefreshingTimer.modify 
    // <stripped> func awardSections.getter 
    // <stripped> func awardSections.setter 
    // <stripped> func awardSections.modify 
    // <stripped> static func init
    func sub_1006a0294 // method (instance)
    func sub_1006a0354 // method (instance)
    func sub_1006a0794 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
