//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

struct __C.cmark_node {
    var content: __C.cmark_strbuf
    var next: UnsafeMutablePointer -> __C.cmark_node ?
    var prev: UnsafeMutablePointer -> __C.cmark_node ?
    var parent: UnsafeMutablePointer -> __C.cmark_node ?
    var first_child: UnsafeMutablePointer -> __C.cmark_node ?
    var last_child: UnsafeMutablePointer -> __C.cmark_node ?
    var user_data: UnsafeMutableRawPointer?
    var user_data_free_func:  empty-list UnsafeMutablePointer -> __C.cmark_mem _$sGSg_SvSgtXCSg
    var start_line: nominal type descriptor for Int32
    var start_column: nominal type descriptor for Int32
    var end_line: nominal type descriptor for Int32
    var end_column: nominal type descriptor for Int32
    var internal_offset: nominal type descriptor for Int32
    var type: nominal type descriptor for UInt16
    var flags: nominal type descriptor for UInt16
    var backtick_count: nominal type descriptor for Int32
    var extension: UnsafeMutablePointer -> __C.cmark_syntax_extension ?
    var as: __C.cmark_node.__Unnamed_union_as
}
