//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

struct __C.cmark_renderer {
    var mem: UnsafeMutablePointer -> __C.cmark_mem ?
    var buffer: UnsafeMutablePointer -> __C.cmark_strbuf ?
    var prefix: UnsafeMutablePointer -> __C.cmark_strbuf ?
    var column: nominal type descriptor for Int32
    var width: nominal type descriptor for Int32
    var need_cr: nominal type descriptor for Int32
    var last_breakable: nominal type descriptor for Int32
    var begin_line: Swift.Bool
    var begin_content: Swift.Bool
    var no_linebreaks: Swift.Bool
    var in_tight_list_item: Swift.Bool
    var outc:  empty-list UnsafeMutablePointer -> __C.cmark_renderer _$sGSg_Sp -> __C.cmark_node ? __C.cmark_escaping nominal type descriptor for Int32 nominal type descriptor for UInt8 _$stXCSg
    var cr:  empty-list UnsafeMutablePointer -> __C.cmark_renderer _$sGSgXCSg
    var blankline:  empty-list UnsafeMutablePointer -> __C.cmark_renderer _$sGSgXCSg
    var out:  empty-list UnsafeMutablePointer -> __C.cmark_renderer _$sGSg_Sp -> __C.cmark_node _$sGSgSP -> nominal type descriptor for Int8 _$sGSgSb __C.cmark_escaping _$stXCSg
    var footnote_ix: nominal type descriptor for UInt32
}
