//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CommentsHeaderSectionController: Apollo.SectionController {
  /* fields */
    var delegate: Apollo.CommentsHeaderSectionControllerDelegate ?
    let crosspostCellActionTaker: Apollo.PostCellActionTaker ?
    var didSuccessfullyPresentFromContextMenu: Swift.Bool
    var isWaitingOnUserToReturnFromSafariPollVote: Swift.Bool
    var mostRecentContextMenuRequest: nominal type descriptor for Date ?
    var link: RDKLink
    var lazy showEndLiveActivityButton: Bool?
  /* methods */
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func didSuccessfullyPresentFromContextMenu.getter 
    // <stripped> func didSuccessfullyPresentFromContextMenu.setter 
    // <stripped> func didSuccessfullyPresentFromContextMenu.modify 
    // <stripped> func isWaitingOnUserToReturnFromSafariPollVote.getter 
    // <stripped> func isWaitingOnUserToReturnFromSafariPollVote.setter 
    // <stripped> func isWaitingOnUserToReturnFromSafariPollVote.modify 
    // <stripped> func mostRecentContextMenuRequest.getter 
    // <stripped> func mostRecentContextMenuRequest.setter 
    // <stripped> func mostRecentContextMenuRequest.modify 
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    func showEndLiveActivityButton.getter.sub_1004d9494
    func showEndLiveActivityButton.setter.sub_1004d94dc
    // <stripped> func showEndLiveActivityButton.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_1004d9eac // method (instance)
    func sub_1004da2c8 // method (instance)
}
