//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CommunityIconPackAlertViewController: UIViewController {
  /* fields */
    let titleLabel: UILabel
    let descriptionLabel: UILabel
    let buyButton: UIButton
    let spinner: UIActivityIndicatorView
    let closeButton: UIButton
    let restoreButton: UIButton
    let footerTextView: UITextView
    let successfulUnlockView: Apollo.CommunityIconPackSuccessfulUnlockView
    let titleTopVerticalSpacing: nominal type descriptor for CGFloat
    let descriptionTopVerticalSpacing: nominal type descriptor for CGFloat
    let buyButtonTopVerticalSpacing: nominal type descriptor for CGFloat
    let buyButtonHeight: nominal type descriptor for CGFloat
    let restoreButtonTopVerticalSpacing: nominal type descriptor for CGFloat
    let footerTopVerticalSpacing: nominal type descriptor for CGFloat
    let footerBottomVerticalSpacing: nominal type descriptor for CGFloat
    let closeButtonDiameter: nominal type descriptor for CGFloat
    let productID: String
    var communityIconPackProduct: SKProduct?
    var restoring: Swift.Bool
    var transactionInProgress: Swift.Bool
  /* methods */
    // <stripped> func communityIconPackProduct.getter 
    // <stripped> func communityIconPackProduct.setter 
    // <stripped> func communityIconPackProduct.modify 
    // <stripped> func restoring.getter 
    // <stripped> func restoring.setter 
    // <stripped> func restoring.modify 
    // <stripped> func transactionInProgress.getter 
    // <stripped> func transactionInProgress.setter 
    // <stripped> func transactionInProgress.modify 
    func sub_10069a28c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10069a638 // method (instance)
    func sub_10069a750 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10069b124 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
