//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CommentCellNode: ASCellNode {
  /* fields */
    var comment: RDKComment
    let showPostContext: Swift.Bool
    let postAuthor: String?
    let isLinkedToComment: Swift.Bool
    let isInModQueue: Swift.Bool
    let censorUsername: Swift.Bool
    let commentPreviewType: Apollo.ShowingInPreviewType ?
    let limitLength: Swift.Bool
    let depthIndicatorNode: ASDisplayNode
    var stickyIndicatorNode: ASImageNode?
    let authorNode: Apollo.ApolloButtonNode
    let cakedayNode: ASImageNode?
    var sharePlayNode: Apollo.ApolloButtonNode ?
    let pointsNode: Apollo.ApolloButtonNode
    let editedIndicatorNode: Apollo.ApolloButtonNode ?
    var awardsNode: Apollo.AwardsNode ?
    var lockedNode: ASImageNode?
    let moreOptionsNode: Apollo.ApolloButtonNode ?
    let ageNode: ASTextNode
    let collapseDisclosureIndicator: ASImageNode
    let totalCollapsedChildrenIndicator: ASTextNode
    let bodyNode: Apollo.MarkdownNode
    var linkButtonNodes: Array -> Apollo.LinkButtonNode
    let postContextNode: Apollo.CommentPostContextNode ?
    let savedIndicatorNode: ASImageNode
    var moderatorBannerNode: Apollo.InlineModeratorBannerNode ?
    let flairNode: Apollo.FlairNode ?
    let modOptionsNode: Apollo.CompactModOptionsNode ?
    let moderatorButton: Apollo.ApolloButtonNode ?
    var actionDelegate: Apollo.CommentCellActionDelegate ?
  /* methods */
    // <stripped> func comment.getter 
    // <stripped> func comment.setter 
    // <stripped> func comment.modify 
    // <stripped> func stickyIndicatorNode.getter 
    // <stripped> func stickyIndicatorNode.setter 
    // <stripped> func stickyIndicatorNode.modify 
    // <stripped> func sharePlayNode.getter 
    // <stripped> func sharePlayNode.setter 
    // <stripped> func sharePlayNode.modify 
    // <stripped> func awardsNode.getter 
    // <stripped> func awardsNode.setter 
    // <stripped> func awardsNode.modify 
    // <stripped> func lockedNode.getter 
    // <stripped> func lockedNode.setter 
    // <stripped> func lockedNode.modify 
    // <stripped> func linkButtonNodes.getter 
    // <stripped> func linkButtonNodes.setter 
    // <stripped> func linkButtonNodes.modify 
    // <stripped> func moderatorBannerNode.getter 
    // <stripped> func moderatorBannerNode.setter 
    // <stripped> func moderatorBannerNode.modify 
    // <stripped> func actionDelegate.getter 
    // <stripped> func actionDelegate.setter 
    // <stripped> func actionDelegate.modify 
    // <stripped> static func init
    func sub_100500fd0 // method (instance)
    func sub_1005045b8 // method (instance)
    func sub_100505330 // method (instance)
    func sub_100505a2c // method (instance)
    // <stripped> func method (instance)
    func sub_100507ce0 // method (instance)
    func sub_100507e78 // method (instance)
    func sub_1005084d4 // method (instance)
    func sub_1005086dc // method (instance)
}
