//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.ContentIdentifier.ContentType {
    case image: nominal type descriptor for URL url_t
    case imageWithoutThumbnail: nominal type descriptor for URL url_t
    case imgurAlbum: Apollo.ImgurAlbum album_t
    case redditGallery: (gallery: RDKGallery)
    case imgurAlbumUnexpanded: nominal type descriptor for URL albumURL_t
    case gif: nominal type descriptor for URL url_t
    case autoplayableVideo: Apollo.AutoplayableVideoSource source_SSSg2idt
    case video: Apollo.VideoSource source_SSSg2idAC11secondaryIDt
    case selfPost: (markdownBody: String?, htmlBody: String?)
    case link: nominal type descriptor for URL url_t
    case redditComments: (linkID: String, subreddit: String?, commentID: String?, context: Int?)
    case redditUser: (username: String)
    case subreddit: (name: String)
    case multireddit: (user: String, name: String)
    case manualMultireddit: (subreddits: [String])
    case xkcd: (id: String)
    case wikipediaPage: Apollo.WikipediaMetadata metadata_t
    case twitterStatus: (id: String)
    case twitterProfile: (username: String)
    case subredditWiki: (subredditName: String, path: String)
    case subredditSearch: _$sSS13subredditName_SS5quer -> __C.RDKSearchSortingMethod _$sSg4sortt
    case message: (messageID: String)
    case newModmailConversation: (conversationID: String)
    case composeMessage: (recipient: String?, subject: String?, message: String?)
    case notificationComposer: Apollo.Watcher watcher_t
    case redditHome
    case mediaButMoreTimeNeeded
    case inAppLink
}
