//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CrosspostPerformViewController: ASDKViewController<ASDisplayNode> {
  /* fields */
    let crosspostParent: RDKLink
    let rootNode: ASScrollNode
    let titleNode: ASTextNode
    let closeButtonNode: Apollo.ApolloButtonNode
    let crosspostNode: Apollo.CrosspostNode
    let textEntryNode: ASEditableTextNode
    let optionsNode: Apollo.CrosspostOptionsNode
    let submitPostButtonNode: Apollo.ApolloButtonNode
    let closeButtonDiameter: nominal type descriptor for CGFloat
    var selectedSubreddit: String?
    var flairOptions: [[String : Any]]?
    var selectedFlairOption: [String : Any]?
  /* methods */
    // <stripped> func selectedSubreddit.getter 
    // <stripped> func selectedSubreddit.setter 
    // <stripped> func selectedSubreddit.modify 
    // <stripped> func flairOptions.getter 
    // <stripped> func flairOptions.setter 
    // <stripped> func flairOptions.modify 
    // <stripped> func selectedFlairOption.getter 
    // <stripped> func selectedFlairOption.setter 
    // <stripped> func selectedFlairOption.modify 
    // <stripped> static func init
    func sub_100499a7c // method (instance)
    func sub_100499fc0 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10049a810 // method (instance)
    func sub_10049a8d8 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10049abfc // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10049c0c8 // method (instance)
}
