//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CrosspostOptionsNode: ASDisplayNode {
  /* fields */
    let selectedSubreddit: String?
    let selectedFlair: Apollo.CrosspostFlairSelection
    var subredditSelectorNode: Apollo.CrosspostOptionSelectorNode
    var flairSelectorNode: Apollo.CrosspostOptionSelectorNode ?
    var separatorNode: ASDisplayNode?
  /* methods */
    // <stripped> func subredditSelectorNode.getter 
    // <stripped> func subredditSelectorNode.setter 
    // <stripped> func subredditSelectorNode.modify 
    // <stripped> func flairSelectorNode.getter 
    // <stripped> func flairSelectorNode.setter 
    // <stripped> func flairSelectorNode.modify 
    // <stripped> func separatorNode.getter 
    // <stripped> func separatorNode.setter 
    // <stripped> func separatorNode.modify 
    // <stripped> static func init
    // <stripped> static func init
    func sub_10049d694 // method (instance)
}
