//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.CrosspostOptionSelectorNode: ASControlNode {
  /* fields */
    let title: String?
    let subtitle: String?
    let showRulesButton: Swift.Bool
    let titleNode: ASTextNode?
    let rulesButton: Apollo.ApolloButtonNode ?
    let subtitleNode: ASTextNode?
  /* methods */
    // <stripped> static func init
    // <stripped> static func init
    func sub_10049d83c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
