//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.DeviceModel {
    case iPodTouch5
    case iPodTouch6
    case iPhone4
    case iPhone4s
    case iPhone5
    case iPhone5c
    case iPhone5s
    case iPhone6
    case iPhone6Plus
    case iPhone6s
    case iPhone6sPlus
    case iPhone7
    case iPhone7Plus
    case iPhone8
    case iPhone8Plus
    case iPhoneX
    case iPhoneXS
    case iPhoneXSMax
    case iPhoneXR
    case iPhone11
    case iPhone11Pro
    case iPhone11ProMax
    case iPhone12
    case iPhone12Mini
    case iPhone12Pro
    case iPhone12ProMax
    case iPhone13
    case iPhone13Mini
    case iPhone13Pro
    case iPhone13ProMax
    case iPhone14Pro
    case iPhone14ProMax
    case iPhone14
    case iPhone14Plus
    case iPhoneSE
    case iPhoneSE2
    case iPhoneSE3
    case iPad2
    case iPad3
    case iPad4
    case iPadAir
    case iPadAir2
    case iPadMini
    case iPadMini2
    case iPadMini3
    case iPadMini4
    case iPadPro9Point7
    case iPadPro12Point9
    case iPad5
    case iPadPro12Point9Gen2
    case iPadPro10Point5
    case iPad6
    case iPadPro11
    case iPadPro11Gen2
    case iPadPro11Gen3
    case iPadPro12Point9Gen3
    case iPadPro12Point9Gen4
    case iPadPro12Point9Gen5
    case iPadAirGen4
    case iPadMini6
    case iPadPro
    case AppleTV
    case simulator
}
