//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.DropDownDataSource: NSObject {
  /* fields */
    var state: Apollo.DropDownDataSource.DropDownType
    var localSubredditSuggestions: [String]
    var remoteSubredditSuggestions: (String, [String])?
    var filteredRemoteSubredditSuggestions: [String]?
    let goalResultsAmount: Int
    var searchQuery: String?
    var previousSearchQuery: String?
  /* methods */
    // <stripped> func state.getter 
    // <stripped> func state.setter 
    // <stripped> func state.modify 
    // <stripped> func localSubredditSuggestions.getter 
    // <stripped> func localSubredditSuggestions.setter 
    // <stripped> func localSubredditSuggestions.modify 
    // <stripped> func remoteSubredditSuggestions.getter 
    // <stripped> func remoteSubredditSuggestions.setter 
    // <stripped> func remoteSubredditSuggestions.modify 
    // <stripped> func filteredRemoteSubredditSuggestions.getter 
    // <stripped> func filteredRemoteSubredditSuggestions.setter 
    // <stripped> func filteredRemoteSubredditSuggestions.modify 
    // <stripped> func searchQuery.getter 
    // <stripped> func searchQuery.setter 
    // <stripped> func searchQuery.modify 
    // <stripped> func previousSearchQuery.getter 
    // <stripped> func previousSearchQuery.setter 
    // <stripped> func previousSearchQuery.modify 
    func sub_1006d6c80 // method (instance)
    // <stripped> func method (instance)
    func sub_1006d6e98 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1006d835c // method (instance)
}
