//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.DualStateButtonNode: ASControlNode {
  /* fields */
    let isArchived: Swift.Bool
    let type: Apollo.DualStateButtonNode.DualStateButtonType
    let colorType: Apollo.DualStateButtonNode.ColorType
    var interactionFailed: Swift.Bool
    let themeable: Swift.Bool
    let backgroundNode: ASDisplayNode
    let iconNode: ASImageNode
    let selectionGenerator: UISelectionFeedbackGenerator
    var isActive: Swift.Bool
    let maximumBackgroundSize: __C.CGSize ?
  /* methods */
    // <stripped> func interactionFailed.getter 
    // <stripped> func interactionFailed.setter 
    // <stripped> func interactionFailed.modify 
    // <stripped> func isActive.getter 
    // <stripped> func isActive.setter 
    // <stripped> func isActive.modify 
    // <stripped> static func init
    func sub_10044bb6c // method (instance)
    func sub_10044bc94 // method (instance)
}
