//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.FancyTextEntryController: UIAlertController {
  /* fields */
    var textFieldsValidationStatus: [Int : Bool]
  /* methods */
    // <stripped> func textFieldsValidationStatus.getter 
    // <stripped> func textFieldsValidationStatus.setter 
    // <stripped> func textFieldsValidationStatus.modify 
    func sub_100210334 // getter (instance)
    // <stripped> func getter (instance)
    func sub_10021047c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
