//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.FlushRequest: Mixpanel.Network {
  /* fields */
    var networkRequestsAllowedAfterTime: Double
    var networkConsecutiveFailures: Int
  /* methods */
    // <stripped> func networkRequestsAllowedAfterTime.getter 
    // <stripped> func networkRequestsAllowedAfterTime.setter 
    // <stripped> func networkRequestsAllowedAfterTime.modify 
    // <stripped> func networkConsecutiveFailures.getter 
    // <stripped> func networkConsecutiveFailures.setter 
    // <stripped> func networkConsecutiveFailures.modify 
    func sub_1008fdd08 // method (instance)
    // <stripped> func method (instance)
    func sub_1008fe394 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
