//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.FontManager: NSObject {
  /* fields */
    var contentSizeCategory: __C.UIContentSizeCategory
  /* methods */
    // <stripped> func contentSizeCategory.getter 
    // <stripped> func contentSizeCategory.setter 
    // <stripped> func contentSizeCategory.modify 
    // <stripped> func method (instance)
    // <stripped> func getter (instance)
    func sub_1002510b0 // getter (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    func sub_100251740 // getter (instance)
    // <stripped> func getter (instance)
    func sub_100251864 // method (instance)
    func sub_100251994 // method (instance)
    func sub_100251ac4 // method (instance)
    func sub_100251bf0 // method (instance)
    func sub_100251d1c // method (instance)
    func sub_100251e50 // method (instance)
    func sub_100252444 // method (instance)
    func sub_100251f8c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func getter (instance)
    // <stripped> func method (instance)
    // <stripped> func getter (instance)
}
