//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.GfycatClient {
  /* fields */
    let session: NSURLSession
    var gfycatCache: Dictionary empty-list String Apollo.GfycatVideo
    let dispatchQueue: DispatchQueue
  /* methods */
    // <stripped> func gfycatCache.getter 
    // <stripped> func gfycatCache.setter 
    // <stripped> func gfycatCache.modify 
    // <stripped> static func init
    func sub_100221420 // method (instance)
    func sub_1002215d8 // method (instance)
    func sub_1002228a4 // method (instance)
}
