//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.GroupActivitiesManager: NSObject {
  /* fields */
    var lazy groupMessenger: nominal type descriptor for GroupSessionMessenger ??
    var lazy tasks: Set empty-list Task empty-list () nominal type descriptor for Never _$sGGSg
    var _groupSession: Any?
    var groupStateObserver: nominal type descriptor for GroupStateObserver
    var isEligibleForSharePlay: Swift.Bool
    var _subscriptions: Set -> nominal type descriptor for AnyHashable
    var _eligibilitySubscriptions: Set -> nominal type descriptor for AnyHashable
  /* methods */
    // <stripped> func groupMessenger.getter 
    // <stripped> func groupMessenger.setter 
    // <stripped> func groupMessenger.modify 
    func tasks.getter.sub_1004f9c04
    // <stripped> func tasks.setter 
    // <stripped> func tasks.modify 
    // <stripped> func _groupSession.getter 
    func _groupSession.setter.sub_1004f9c50
    // <stripped> func _groupSession.modify 
    // <stripped> func groupStateObserver.getter 
    // <stripped> func groupStateObserver.setter 
    // <stripped> func groupStateObserver.modify 
    // <stripped> func isEligibleForSharePlay.getter 
    // <stripped> func isEligibleForSharePlay.setter 
    // <stripped> func isEligibleForSharePlay.modify 
    func _subscriptions.getter.sub_1004f9d54
    // <stripped> func _subscriptions.setter 
    // <stripped> func _subscriptions.modify 
    // <stripped> func _eligibilitySubscriptions.getter 
    // <stripped> func _eligibilitySubscriptions.setter 
    func _eligibilitySubscriptions.modify.sub_1004f9d64
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    func sub_1004f9e34 // modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
}
