//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.Group {
  /* fields */
    let apiToken: String
    let serialQueue: DispatchQueue
    let lock: Mixpanel.ReadWriteLock
    let groupKey: String
    let groupID: Mixpanel.MixpanelType
    var delegate: Mixpanel.FlushDelegate ?
    let metadata: Mixpanel.SessionMetadata
    let mixpanelPersistence: Mixpanel.MixpanelPersistence
    var mixpanelInstance: Mixpanel.MixpanelInstance ?
  /* methods */
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func mixpanelInstance.getter 
    // <stripped> func mixpanelInstance.setter 
    // <stripped> func mixpanelInstance.modify 
    // <stripped> static func init
    func Group.addGroupRecordToQueueWithAction(_:properties:)
    func Group.set(properties:)
    func Group.set(property:to:)
    func Group.setOnce(properties:)
    func Group.unset(property:)
    func Group.remove(key:value:)
    func Group.union(key:values:)
    func Group.deleteGroup()
}
