//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.HollaView: UIView {
  /* fields */
    let index: Int
    var status: Apollo.HollaStatus
  /* methods */
    func status.getter.sub_10051bf28
    // <stripped> func status.setter 
    // <stripped> func status.modify 
    // <stripped> static func init
}
