//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.HorizontalItemCollectionViewCell: UICollectionViewCell {
  /* fields */
    var itemLabel: UILabel?
    var leftDivider: UIView?
    var rightDivider: UIView?
  /* methods */
    // <stripped> func itemLabel.getter 
    // <stripped> func itemLabel.setter 
    // <stripped> func itemLabel.modify 
    // <stripped> func leftDivider.getter 
    // <stripped> func leftDivider.setter 
    // <stripped> func leftDivider.modify 
    // <stripped> func rightDivider.getter 
    // <stripped> func rightDivider.setter 
    // <stripped> func rightDivider.modify 
    func sub_10073fe54 // method (instance)
}
