//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.IconTextTableViewCell: UITableViewCell {
  /* fields */
    let iconImageView: UIImageView
    let titleLabel: UILabel
    let disclosureIndicator: UIImageView
    var colorAsModerator: Swift.Bool
    var showDisclosureIndicator: Swift.Bool
  /* methods */
    // <stripped> func colorAsModerator.getter 
    // <stripped> func colorAsModerator.setter 
    // <stripped> func colorAsModerator.modify 
    // <stripped> func showDisclosureIndicator.getter 
    // <stripped> func showDisclosureIndicator.setter 
    // <stripped> func showDisclosureIndicator.modify 
    func sub_1005e5884 // method (instance)
}
