//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.IconTextCellNode: ASCellNode {
  /* fields */
    let iconColor: Apollo.IconTextCellNode.IconColor
    let iconImage: UIImage
    let text: String
    let textInset: nominal type descriptor for CGFloat
    let showDisclosureIndicator: Swift.Bool
    let iconNode: ASImageNode
    let textNode: ASTextNode
    let disclosureIndicator: ASImageNode?
  /* methods */
    // <stripped> static func init
    func sub_100184984 // method (instance)
}
