//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

struct Apollo.ImgurAlbum {
    let id: String
    let title: String?
    let description: String?
    let coverID: String?
    let views: Int
    let isNSFW: Swift.Bool
    let images: Array -> Apollo.ImgurImage
    let url: nominal type descriptor for URL
    let deleteHash: String?
}
