//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class SwiftyStoreKit.InAppReceiptVerificator: NSObject {
  /* fields */
    let appStoreReceiptURL: nominal type descriptor for URL ?
    var receiptRefreshRequest: SwiftyStoreKit.InAppReceiptRefreshRequest ?
  /* methods */
    // <stripped> static func init
    // <stripped> func getter (instance)
    // <stripped> func receiptRefreshRequest.getter 
    // <stripped> func receiptRefreshRequest.setter 
    // <stripped> func receiptRefreshRequest.modify 
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
