//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.InboxCellNode: ASCellNode {
  /* fields */
    var message: RDKMessage?
    var newModmailConversationInfo: RDKModmailConversationInfo?
    let newModmailMessage: RDKModmailMessage?
    let typeNode: ASImageNode
    var extraDetailIconNode: ASImageNode?
    let overviewTextNode: ASTextNode
    let bodyTextNode: ASTextNode
    let subredditButtonNode: Apollo.ApolloButtonNode ?
    let authorButtonNode: Apollo.ApolloButtonNode ?
    let recipientButtonNode: Apollo.ApolloButtonNode ?
    let moreOptionsButtonNode: Apollo.ApolloButtonNode ?
    let ageNode: ASTextNode
    let separatorNode: ASDisplayNode
    var actionDelegate: Apollo.InboxCellActionDelegate ?
  /* methods */
    // <stripped> func message.getter 
    // <stripped> func message.setter 
    // <stripped> func message.modify 
    // <stripped> func newModmailConversationInfo.getter 
    // <stripped> func newModmailConversationInfo.setter 
    // <stripped> func newModmailConversationInfo.modify 
    // <stripped> func extraDetailIconNode.getter 
    // <stripped> func extraDetailIconNode.setter 
    // <stripped> func extraDetailIconNode.modify 
    // <stripped> func actionDelegate.getter 
    // <stripped> func actionDelegate.setter 
    // <stripped> func actionDelegate.modify 
    // <stripped> static func init
    // <stripped> static func init
    func sub_10067a41c // method (instance)
    func sub_10067b8d4 // method (instance)
    // <stripped> func method (instance)
}
