//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.InboxViewController: Apollo.ASTableViewController {
  /* fields */
    var inboxType: Apollo.InboxType
    let signInSplashView: Apollo.SignInSplashView ?
    let listAdapter: Apollo.ListAdapter
    let refreshControl: UIRefreshControl
    let newMessageBarButtonItem: UIBarButtonItem?
    let markAllReadBarButtonItem: UIBarButtonItem?
    var messages: [RDKMessage]?
    var currentPagination: RDKPagination?
    var canMarkAllRead: Swift.Bool
    var restoredVisibleMessage: RDKMessage?
    var restoredContentOffsetY: nominal type descriptor for CGFloat ?
    var restoredViewWidth: nominal type descriptor for CGFloat ?
    var refreshingTimer: weak NSTimer?
    var fullNameToMarkRead: String?
  /* methods */
    // <stripped> func inboxType.getter 
    // <stripped> func inboxType.setter 
    // <stripped> func inboxType.modify 
    // <stripped> func messages.getter 
    // <stripped> func messages.setter 
    func messages.modify.sub_100199f08
    // <stripped> func currentPagination.getter 
    // <stripped> func currentPagination.setter 
    // <stripped> func currentPagination.modify 
    // <stripped> func canMarkAllRead.getter 
    // <stripped> func canMarkAllRead.setter 
    // <stripped> func canMarkAllRead.modify 
    // <stripped> func restoredVisibleMessage.getter 
    // <stripped> func restoredVisibleMessage.setter 
    // <stripped> func restoredVisibleMessage.modify 
    // <stripped> func restoredContentOffsetY.getter 
    // <stripped> func restoredContentOffsetY.setter 
    // <stripped> func restoredContentOffsetY.modify 
    // <stripped> func restoredViewWidth.getter 
    // <stripped> func restoredViewWidth.setter 
    // <stripped> func restoredViewWidth.modify 
    // <stripped> func refreshingTimer.getter 
    // <stripped> func refreshingTimer.setter 
    // <stripped> func refreshingTimer.modify 
    // <stripped> static func init
    func sub_10019b470 // method (instance)
    // <stripped> func method (instance)
    func sub_10019c070 // method (instance)
    func sub_10019c250 // method (instance)
    func sub_10019c56c // method (instance)
    // <stripped> func method (instance)
    func sub_10019d430 // method (instance)
    // <stripped> func fullNameToMarkRead.getter 
    // <stripped> func fullNameToMarkRead.setter 
    // <stripped> func fullNameToMarkRead.modify 
    func sub_10019d85c // method (instance)
}
