//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.InputBarButtonItem: UIButton {
  /* fields */
    var messageInputBar: Apollo.MessageInputBar ?
    var spacing: Apollo.InputBarButtonItem.Spacing
    var size: __C.CGSize ?
    var parentStackViewPosition: Apollo.InputStackView.Position ?
    var onTouchUpInsideAction: Apollo.InputBarButtonItem _$scSg ->
    var onKeyboardEditingBeginsAction: Apollo.InputBarButtonItem _$scSg ->
    var onKeyboardEditingEndsAction: Apollo.InputBarButtonItem _$scSg ->
    var onTextViewDidChangeAction: Apollo.InputBarButtonItem  first-element-marker  -> Apollo.InputTextView _$stcSg
    var onSelectedAction: Apollo.InputBarButtonItem _$scSg ->
    var onDeselectedAction: Apollo.InputBarButtonItem _$scSg ->
    var onEnabledAction: Apollo.InputBarButtonItem _$scSg ->
    var onDisabledAction: Apollo.InputBarButtonItem _$scSg ->
  /* methods */
    func InputBarButtonItem.messageInputBar.getter
    func InputBarButtonItem.messageInputBar.setter
    func InputBarButtonItem.messageInputBar.modify
    func InputBarButtonItem.spacing.getter
    func InputBarButtonItem.spacing.setter
    func InputBarButtonItem.spacing.modify
    // <stripped> func size.getter 
    // <stripped> func size.setter 
    // <stripped> func size.modify 
    func InputBarButtonItem.parentStackViewPosition.getter
    func InputBarButtonItem.parentStackViewPosition.setter
    func InputBarButtonItem.parentStackViewPosition.modify
    func InputBarButtonItem.title.getter
    func InputBarButtonItem.title.setter
    func InputBarButtonItem.title.modify
    func InputBarButtonItem.image.getter
    func InputBarButtonItem.image.setter
    func InputBarButtonItem.image.modify
    // <stripped> func onKeyboardEditingEndsAction.getter 
    // <stripped> func onKeyboardEditingEndsAction.setter 
    // <stripped> func onKeyboardEditingEndsAction.modify 
    // <stripped> func onTextViewDidChangeAction.getter 
    // <stripped> func onTextViewDidChangeAction.setter 
    // <stripped> func onTextViewDidChangeAction.modify 
    // <stripped> func onSelectedAction.getter 
    // <stripped> func onSelectedAction.setter 
    // <stripped> func onSelectedAction.modify 
    // <stripped> func onDeselectedAction.getter 
    // <stripped> func onDeselectedAction.setter 
    // <stripped> func onDeselectedAction.modify 
    // <stripped> func onEnabledAction.getter 
    // <stripped> func onEnabledAction.setter 
    // <stripped> func onEnabledAction.modify 
    // <stripped> func onDisabledAction.getter 
    // <stripped> func onDisabledAction.setter 
    // <stripped> func onDisabledAction.modify 
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    func InputBarButtonItem.setup()
    func InputBarButtonItem.setSize(_:animated:)
    func InputBarButtonItem.configure(_:)
    func InputBarButtonItem.onKeyboardEditingBegins(_:)
    func InputBarButtonItem.onKeyboardEditingEnds(_:)
    func InputBarButtonItem.onTextViewDidChange(_:)
    func InputBarButtonItem.onTouchUpInside(_:)
    func InputBarButtonItem.onSelected(_:)
    func InputBarButtonItem.onDeselected(_:)
    func InputBarButtonItem.onEnabled(_:)
    func InputBarButtonItem.onDisabled(_:)
    func InputBarButtonItem.textViewDidChangeAction(with:)
    func InputBarButtonItem.keyboardEditingEndsAction()
    func InputBarButtonItem.keyboardEditingBeginsAction()
    func InputBarButtonItem.touchUpInsideAction()
}
