//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.InputTextView: Apollo.PasteableTextView {
  /* fields */
    var isImagePasteEnabled: Swift.Bool
    let placeholderLabel: UILabel
    var placeholder: String?
    var placeholderTextColor: UIColor?
    var placeholderLabelInsets: __C.UIEdgeInsets
    var messageInputBar: Apollo.MessageInputBar ?
    var placeholderLabelConstraintSet: Apollo.NSLayoutConstraintSet ?
  /* methods */
    func InputTextView.images.getter
    func InputTextView.components.getter
    func InputTextView.isImagePasteEnabled.getter
    func InputTextView.isImagePasteEnabled.setter
    func InputTextView.isImagePasteEnabled.modify
    func InputTextView.placeholder.getter
    func InputTextView.placeholder.setter
    func InputTextView.placeholder.modify
    func InputTextView.placeholderTextColor.getter
    func InputTextView.placeholderTextColor.setter
    func InputTextView.placeholderTextColor.modify
    func InputTextView.placeholderLabelInsets.getter
    func InputTextView.placeholderLabelInsets.setter
    func InputTextView.placeholderLabelInsets.modify
    func InputTextView.messageInputBar.getter
    func InputTextView.messageInputBar.setter
    func InputTextView.messageInputBar.modify
    // <stripped> func placeholderLabelConstraintSet.getter 
    // <stripped> func placeholderLabelConstraintSet.setter 
    // <stripped> func placeholderLabelConstraintSet.modify 
    func InputTextView.setup()
    func InputTextView.setupPlaceholderLabel()
    // <stripped> func method (instance)
    func InputTextView.updateConstraintsForPlaceholderLabel()
    // <stripped> func method (instance)
    func InputTextView.textViewTextDidChange()
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func InputTextView.parseForComponents()
    func InputTextView.redrawTextAttachments()
}
