//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.LargePostCellNode: ASCellNode {
  /* fields */
    var link: RDKLink
    let isOnProfile: Swift.Bool
    let inSpecificSubreddit: Swift.Bool
    var isRead: Swift.Bool
    let upperSubredditIconNode: Apollo.TouchHintNetworkImageNode ?
    let upperSubredditNode: Apollo.ApolloButtonNode ?
    let titleNode: Apollo.PostTitleNode
    let postInfoNode: Apollo.PostInfoNode
    let optionButtonsNode: Apollo.LargePostOptionButtonsNode ?
    let moderatorOptionsNode: Apollo.LargePostModButtonsNode ?
    let savedIndicatorNode: ASImageNode
    var richMediaNode: Apollo.RichMediaNode ?
    var crosspostNode: Apollo.CrosspostNode ?
    var moderatorBannerNode: Apollo.InlineModeratorBannerNode ?
    var actionDelegate: Apollo.PostCellActionDelegate ?
    var isUsingPlaceholderSubredditIcon: Swift.Bool
    var lastOffsetVisibilityCheck: nominal type descriptor for CGFloat
  /* methods */
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    // <stripped> func isRead.getter 
    // <stripped> func isRead.setter 
    // <stripped> func isRead.modify 
    // <stripped> func richMediaNode.getter 
    // <stripped> func richMediaNode.setter 
    // <stripped> func richMediaNode.modify 
    // <stripped> func crosspostNode.getter 
    // <stripped> func crosspostNode.setter 
    // <stripped> func crosspostNode.modify 
    // <stripped> func moderatorBannerNode.getter 
    // <stripped> func moderatorBannerNode.setter 
    // <stripped> func moderatorBannerNode.modify 
    // <stripped> func actionDelegate.getter 
    // <stripped> func actionDelegate.setter 
    // <stripped> func actionDelegate.modify 
    // <stripped> static func init
    func sub_100303ed0 // method (instance)
    // <stripped> func method (instance)
    func sub_100304694 // method (instance)
    func sub_100305eb4 // method (instance)
    // <stripped> func isUsingPlaceholderSubredditIcon.getter 
    // <stripped> func isUsingPlaceholderSubredditIcon.setter 
    // <stripped> func isUsingPlaceholderSubredditIcon.modify 
    func sub_100306194 // method (instance)
    func sub_100306b90 // method (instance)
    func sub_10030701c // method (instance)
    // <stripped> func lastOffsetVisibilityCheck.getter 
    // <stripped> func lastOffsetVisibilityCheck.setter 
    // <stripped> func lastOffsetVisibilityCheck.modify 
    func sub_100307dd8 // method (instance)
    func sub_100307f10 // method (instance)
}
