//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.ListAdapter: NSObject {
  /* fields */
    var viewController: weak UIViewController?
    var dataSource: Apollo.ListAdapterDataSource ?
    var delegate: Apollo.ListAdapterDelegate ?
    var scrollingDelegate: Apollo.ListAdapterScrollingDelegate ?
    var objects: Array -> nominal type descriptor for AnyHashable
    var objectToIndexPathMapping: Dictionary -> nominal type descriptor for AnyHashable nominal type descriptor for IndexPath
    var indexPathToSectionControllerMapping: Dictionary -> nominal type descriptor for IndexPath Apollo.SectionController
    var emptyView: UIView?
    var tableNode: weak ASTableNode?
    var scrollOffsetAtStartOfDrag: nominal type descriptor for CGFloat ?
  /* methods */
    // <stripped> func viewController.getter 
    // <stripped> func viewController.setter 
    // <stripped> func viewController.modify 
    // <stripped> func dataSource.getter 
    // <stripped> func dataSource.setter 
    // <stripped> func dataSource.modify 
    func sub_100172b28 // method (instance)
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func scrollingDelegate.getter 
    // <stripped> func scrollingDelegate.setter 
    // <stripped> func scrollingDelegate.modify 
    // <stripped> func objects.getter 
    // <stripped> func objects.setter 
    // <stripped> func objects.modify 
    // <stripped> func objectToIndexPathMapping.getter 
    // <stripped> func objectToIndexPathMapping.setter 
    // <stripped> func objectToIndexPathMapping.modify 
    // <stripped> func indexPathToSectionControllerMapping.getter 
    // <stripped> func indexPathToSectionControllerMapping.setter 
    // <stripped> func indexPathToSectionControllerMapping.modify 
    // <stripped> func emptyView.getter 
    // <stripped> func emptyView.setter 
    // <stripped> func emptyView.modify 
    // <stripped> func tableNode.getter 
    // <stripped> func tableNode.setter 
    // <stripped> func tableNode.modify 
    // <stripped> func scrollOffsetAtStartOfDrag.getter 
    // <stripped> func scrollOffsetAtStartOfDrag.setter 
    // <stripped> func scrollOffsetAtStartOfDrag.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_100173230 // method (instance)
    func sub_100175168 // method (instance)
}
