//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.LitePostsViewController: ASDKViewController<ASTableNode> {
  /* fields */
    let subreddit: String
    let tableNode: ASTableNode
    var links: [RDKLink]
    var pagination: RDKPagination?
  /* methods */
    // <stripped> func links.getter 
    // <stripped> func links.setter 
    // <stripped> func links.modify 
    // <stripped> func pagination.getter 
    // <stripped> func pagination.setter 
    // <stripped> func pagination.modify 
    // <stripped> static func init
    func sub_1002a0c74 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
