//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MediaViewerAnimationController: NSObject {
  /* fields */
    let isPresenting: Swift.Bool
    var thumbnailImageView: UIImageView?
  /* methods */
    // <stripped> func thumbnailImageView.getter 
    // <stripped> func thumbnailImageView.setter 
    // <stripped> func thumbnailImageView.modify 
    // <stripped> static func init
    func sub_100208610 // method (instance)
    func sub_100208854 // method (instance)
    func sub_10020898c // method (instance)
    // <stripped> func method (instance)
    func sub_10020a430 // method (instance)
    func sub_10020c120 // method (instance)
    // <stripped> func method (instance)
}
