//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MessageSizeCalculator: Apollo.CellSizeCalculator {
  /* fields */
    var incomingAvatarSize: __C.CGSize
    var outgoingAvatarSize: __C.CGSize
    var incomingAvatarPosition: Apollo.AvatarPosition
    var outgoingAvatarPosition: Apollo.AvatarPosition
    var incomingMessagePadding: __C.UIEdgeInsets
    var outgoingMessagePadding: __C.UIEdgeInsets
    var incomingCellTopLabelAlignment: Apollo.LabelAlignment
    var outgoingCellTopLabelAlignment: Apollo.LabelAlignment
    var incomingMessageTopLabelAlignment: Apollo.LabelAlignment
    var outgoingMessageTopLabelAlignment: Apollo.LabelAlignment
    var incomingMessageBottomLabelAlignment: Apollo.LabelAlignment
    var outgoingMessageBottomLabelAlignment: Apollo.LabelAlignment
    var incomingAccessoryViewSize: __C.CGSize
    var outgoingAccessoryViewSize: __C.CGSize
    var incomingAccessoryViewPadding: Apollo.HorizontalEdgeInsets
    var outgoingAccessoryViewPadding: Apollo.HorizontalEdgeInsets
  /* methods */
    static func MessageSizeCalculator.__allocating_init(layout:)
    func MessageSizeCalculator.incomingAvatarSize.getter
    func MessageSizeCalculator.incomingAvatarSize.setter
    func MessageSizeCalculator.incomingAvatarSize.modify
    func MessageSizeCalculator.outgoingAvatarSize.getter
    func MessageSizeCalculator.outgoingAvatarSize.setter
    func MessageSizeCalculator.outgoingAvatarSize.modify
    func MessageSizeCalculator.incomingAvatarPosition.getter
    func MessageSizeCalculator.incomingAvatarPosition.setter
    func MessageSizeCalculator.incomingAvatarPosition.modify
    func MessageSizeCalculator.outgoingAvatarPosition.getter
    func MessageSizeCalculator.outgoingAvatarPosition.setter
    func MessageSizeCalculator.outgoingAvatarPosition.modify
    func MessageSizeCalculator.incomingMessagePadding.getter
    func MessageSizeCalculator.incomingMessagePadding.setter
    func MessageSizeCalculator.incomingMessagePadding.modify
    func MessageSizeCalculator.outgoingMessagePadding.getter
    func MessageSizeCalculator.outgoingMessagePadding.setter
    func MessageSizeCalculator.outgoingMessagePadding.modify
    func MessageSizeCalculator.incomingCellTopLabelAlignment.getter
    func MessageSizeCalculator.incomingCellTopLabelAlignment.setter
    func MessageSizeCalculator.incomingCellTopLabelAlignment.modify
    func MessageSizeCalculator.outgoingCellTopLabelAlignment.getter
    func MessageSizeCalculator.outgoingCellTopLabelAlignment.setter
    func MessageSizeCalculator.outgoingCellTopLabelAlignment.modify
    func MessageSizeCalculator.incomingMessageTopLabelAlignment.getter
    func MessageSizeCalculator.incomingMessageTopLabelAlignment.setter
    func MessageSizeCalculator.incomingMessageTopLabelAlignment.modify
    func MessageSizeCalculator.outgoingMessageTopLabelAlignment.getter
    func MessageSizeCalculator.outgoingMessageTopLabelAlignment.setter
    func MessageSizeCalculator.outgoingMessageTopLabelAlignment.modify
    func MessageSizeCalculator.incomingMessageBottomLabelAlignment.getter
    func MessageSizeCalculator.incomingMessageBottomLabelAlignment.setter
    func MessageSizeCalculator.incomingMessageBottomLabelAlignment.modify
    func MessageSizeCalculator.outgoingMessageBottomLabelAlignment.getter
    func MessageSizeCalculator.outgoingMessageBottomLabelAlignment.setter
    func MessageSizeCalculator.outgoingMessageBottomLabelAlignment.modify
    func MessageSizeCalculator.incomingAccessoryViewSize.getter
    func MessageSizeCalculator.incomingAccessoryViewSize.setter
    func MessageSizeCalculator.incomingAccessoryViewSize.modify
    func MessageSizeCalculator.outgoingAccessoryViewSize.getter
    func MessageSizeCalculator.outgoingAccessoryViewSize.setter
    func MessageSizeCalculator.outgoingAccessoryViewSize.modify
    func MessageSizeCalculator.incomingAccessoryViewPadding.getter
    func MessageSizeCalculator.incomingAccessoryViewPadding.setter
    func MessageSizeCalculator.incomingAccessoryViewPadding.modify
    func MessageSizeCalculator.outgoingAccessoryViewPadding.getter
    func MessageSizeCalculator.outgoingAccessoryViewPadding.setter
    func MessageSizeCalculator.outgoingAccessoryViewPadding.modify
    func MessageSizeCalculator.cellContentHeight(for:at:)
    func MessageSizeCalculator.avatarPosition(for:)
    func MessageSizeCalculator.avatarSize(for:)
    func MessageSizeCalculator.cellTopLabelSize(for:at:)
    func MessageSizeCalculator.cellTopLabelAlignment(for:)
    func MessageSizeCalculator.messageTopLabelSize(for:at:)
    func MessageSizeCalculator.messageTopLabelAlignment(for:)
    func MessageSizeCalculator.messageBottomLabelSize(for:at:)
    func MessageSizeCalculator.messageBottomLabelAlignment(for:)
    func MessageSizeCalculator.accessoryViewSize(for:)
    func MessageSizeCalculator.accessoryViewPadding(for:)
    func MessageSizeCalculator.messageContainerPadding(for:)
    func MessageSizeCalculator.messageContainerSize(for:)
    func MessageSizeCalculator.messageContainerMaxWidth(for:)
    func MessageSizeCalculator.messagesLayout.getter
    // <stripped> func method (instance)
}
