//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MessagesCollectionViewFlowLayout: UICollectionViewFlowLayout {
  /* fields */
    var lazy textMessageSizeCalculator: Apollo.TextMessageSizeCalculator ?
    var lazy attributedTextMessageSizeCalculator: Apollo.TextMessageSizeCalculator ?
    var lazy emojiMessageSizeCalculator: Apollo.TextMessageSizeCalculator ?
    var lazy photoMessageSizeCalculator: Apollo.MediaMessageSizeCalculator ?
    var lazy videoMessageSizeCalculator: Apollo.MediaMessageSizeCalculator ?
    var lazy locationMessageSizeCalculator: Apollo.LocationMessageSizeCalculator ?
  /* methods */
    func MessagesCollectionViewFlowLayout.messagesCollectionView.getter
    func MessagesCollectionViewFlowLayout.messagesDataSource.getter
    func MessagesCollectionViewFlowLayout.messagesLayoutDelegate.getter
    func MessagesCollectionViewFlowLayout.itemWidth.getter
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func MessagesCollectionViewFlowLayout.textMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.textMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.textMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.attributedTextMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.attributedTextMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.attributedTextMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.emojiMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.emojiMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.emojiMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.photoMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.photoMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.photoMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.videoMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.videoMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.videoMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.locationMessageSizeCalculator.getter
    func MessagesCollectionViewFlowLayout.locationMessageSizeCalculator.setter
    func MessagesCollectionViewFlowLayout.locationMessageSizeCalculator.modify
    func MessagesCollectionViewFlowLayout.cellSizeCalculatorForItem(at:)
    func MessagesCollectionViewFlowLayout.sizeForItem(at:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingAvatarSize(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingAvatarSize(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingAvatarPosition(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingAvatarPosition(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingMessagePadding(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingMessagePadding(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingCellTopLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingCellTopLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingMessageTopLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingMessageTopLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingMessageBottomLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingMessageBottomLabelAlignment(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingAccessoryViewSize(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingAccessoryViewSize(_:)
    func MessagesCollectionViewFlowLayout.setMessageIncomingAccessoryViewPadding(_:)
    func MessagesCollectionViewFlowLayout.setMessageOutgoingAccessoryViewPadding(_:)
    func MessagesCollectionViewFlowLayout.messageSizeCalculators()
}
