//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MessageContentCell: Apollo.MessageCollectionViewCell {
  /* fields */
    var isInverted: Swift.Bool
    var avatarView: Apollo.AvatarView
    var messageContainerView: Apollo.MessageContainerView
    var cellTopLabel: Apollo.InsetLabel
    var messageTopLabel: Apollo.InsetLabel
    var messageBottomLabel: Apollo.InsetLabel
    var accessoryView: UIView
    var delegate: Apollo.MessageCellDelegate ?
  /* methods */
    func MessageContentCell.isInverted.getter
    func MessageContentCell.isInverted.setter
    func MessageContentCell.isInverted.modify
    func MessageContentCell.avatarView.getter
    func MessageContentCell.avatarView.setter
    func MessageContentCell.avatarView.modify
    func MessageContentCell.messageContainerView.getter
    func MessageContentCell.messageContainerView.setter
    func MessageContentCell.messageContainerView.modify
    func MessageContentCell.cellTopLabel.getter
    func MessageContentCell.cellTopLabel.setter
    func MessageContentCell.cellTopLabel.modify
    func MessageContentCell.messageTopLabel.getter
    func MessageContentCell.messageTopLabel.setter
    func MessageContentCell.messageTopLabel.modify
    func MessageContentCell.messageBottomLabel.getter
    func MessageContentCell.messageBottomLabel.setter
    func MessageContentCell.messageBottomLabel.modify
    func MessageContentCell.accessoryView.getter
    func MessageContentCell.accessoryView.setter
    func MessageContentCell.accessoryView.modify
    func MessageContentCell.delegate.getter
    func MessageContentCell.delegate.setter
    func MessageContentCell.delegate.modify
    func MessageContentCell.setupSubviews()
    func MessageContentCell.configure(with:at:and:)
    func MessageContentCell.handleTapGesture(_:)
    func MessageContentCell.handleLongPressGesture(_:)
    func MessageContentCell.cellContentView(canHandle:gesture:)
    func MessageContentCell.layoutAvatarView(with:)
    func MessageContentCell.layoutMessageContainerView(with:)
    func MessageContentCell.layoutCellTopLabel(with:)
    func MessageContentCell.layoutMessageTopLabel(with:)
    func MessageContentCell.layoutBottomLabel(with:)
    func MessageContentCell.layoutAccessoryView(with:)
}
