//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MessageInputBar: UIView {
  /* fields */
    var delegate: Apollo.MessageInputBarDelegate ?
    var backgroundView: UIView
    var contentView: UIView
    var blurView: UIVisualEffectView
    var isTranslucent: Swift.Bool
    let separatorLine: Apollo.SeparatorLine
    let topStackView: Apollo.InputStackView
    let leftStackView: Apollo.InputStackView
    let rightStackView: Apollo.InputStackView
    let bottomStackView: Apollo.InputStackView
    var lazy inputTextView: Apollo.InputTextView ?
    var sendButton: Apollo.InputBarButtonItem
    var padding: __C.UIEdgeInsets
    var topStackViewPadding: __C.UIEdgeInsets
    var textViewPadding: __C.UIEdgeInsets
    var previousIntrinsicContentSize: __C.CGSize ?
    var lazy cachedIntrinsicContentSize: __C.CGSize ?
    var isOverMaxTextViewHeight: Swift.Bool
    var shouldForceTextViewMaxHeight: Swift.Bool
    var shouldAutoUpdateMaxTextViewHeight: Swift.Bool
    var maxTextViewHeight: nominal type descriptor for CGFloat
    var shouldManageSendButtonEnabledState: Swift.Bool
    var leftStackViewWidthConstant: nominal type descriptor for CGFloat
    var rightStackViewWidthConstant: nominal type descriptor for CGFloat
    var plugins: Array -> Apollo.InputPlugin
    var leftStackViewItems: Array -> Apollo.InputItem
    var rightStackViewItems: Array -> Apollo.InputItem
    var bottomStackViewItems: Array -> Apollo.InputItem
    var topStackViewItems: Array -> Apollo.InputItem
    var nonStackViewItems: Array -> Apollo.InputItem
    var textViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var textViewHeightAnchor: NSLayoutConstraint?
    var topStackViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var leftStackViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var rightStackViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var bottomStackViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var contentViewLayoutSet: Apollo.NSLayoutConstraintSet ?
    var windowAnchor: NSLayoutConstraint?
    var backgroundViewBottomAnchor: NSLayoutConstraint?
  /* methods */
    func MessageInputBar.delegate.getter
    func MessageInputBar.delegate.setter
    func MessageInputBar.delegate.modify
    func MessageInputBar.backgroundView.getter
    func MessageInputBar.backgroundView.setter
    func MessageInputBar.backgroundView.modify
    func MessageInputBar.contentView.getter
    func MessageInputBar.contentView.setter
    func MessageInputBar.contentView.modify
    func MessageInputBar.blurView.getter
    func MessageInputBar.blurView.setter
    func MessageInputBar.blurView.modify
    func MessageInputBar.isTranslucent.getter
    func MessageInputBar.isTranslucent.setter
    func MessageInputBar.isTranslucent.modify
    func MessageInputBar.inputTextView.getter
    func MessageInputBar.inputTextView.setter
    func MessageInputBar.inputTextView.modify
    func MessageInputBar.sendButton.getter
    func MessageInputBar.sendButton.setter
    func MessageInputBar.sendButton.modify
    func MessageInputBar.padding.getter
    func MessageInputBar.padding.setter
    func MessageInputBar.padding.modify
    func MessageInputBar.topStackViewPadding.getter
    func MessageInputBar.topStackViewPadding.setter
    func MessageInputBar.topStackViewPadding.modify
    func MessageInputBar.textViewPadding.getter
    func MessageInputBar.textViewPadding.setter
    func MessageInputBar.textViewPadding.modify
    func MessageInputBar.previousIntrinsicContentSize.getter
    // <stripped> func previousIntrinsicContentSize.setter 
    // <stripped> func previousIntrinsicContentSize.modify 
    func MessageInputBar.cachedIntrinsicContentSize.getter
    // <stripped> func cachedIntrinsicContentSize.setter 
    // <stripped> func cachedIntrinsicContentSize.modify 
    func MessageInputBar.isOverMaxTextViewHeight.getter
    // <stripped> func isOverMaxTextViewHeight.setter 
    // <stripped> func isOverMaxTextViewHeight.modify 
    func MessageInputBar.shouldForceTextViewMaxHeight.getter
    // <stripped> func shouldForceTextViewMaxHeight.setter 
    // <stripped> func shouldForceTextViewMaxHeight.modify 
    func MessageInputBar.shouldAutoUpdateMaxTextViewHeight.getter
    func MessageInputBar.shouldAutoUpdateMaxTextViewHeight.setter
    func MessageInputBar.shouldAutoUpdateMaxTextViewHeight.modify
    func MessageInputBar.maxTextViewHeight.getter
    func MessageInputBar.maxTextViewHeight.setter
    func MessageInputBar.maxTextViewHeight.modify
    func MessageInputBar.shouldManageSendButtonEnabledState.getter
    func MessageInputBar.shouldManageSendButtonEnabledState.setter
    func MessageInputBar.shouldManageSendButtonEnabledState.modify
    func MessageInputBar.requiredInputTextViewHeight.getter
    func MessageInputBar.leftStackViewWidthConstant.getter
    func MessageInputBar.leftStackViewWidthConstant.setter
    // <stripped> func leftStackViewWidthConstant.modify 
    func MessageInputBar.rightStackViewWidthConstant.getter
    func MessageInputBar.rightStackViewWidthConstant.setter
    // <stripped> func rightStackViewWidthConstant.modify 
    func MessageInputBar.plugins.getter
    func MessageInputBar.plugins.setter
    func MessageInputBar.plugins.modify
    func MessageInputBar.leftStackViewItems.getter
    // <stripped> func leftStackViewItems.setter 
    // <stripped> func leftStackViewItems.modify 
    func MessageInputBar.rightStackViewItems.getter
    // <stripped> func rightStackViewItems.setter 
    // <stripped> func rightStackViewItems.modify 
    func MessageInputBar.bottomStackViewItems.getter
    // <stripped> func bottomStackViewItems.setter 
    // <stripped> func bottomStackViewItems.modify 
    func MessageInputBar.topStackViewItems.getter
    // <stripped> func topStackViewItems.setter 
    // <stripped> func topStackViewItems.modify 
    func MessageInputBar.nonStackViewItems.getter
    func MessageInputBar.nonStackViewItems.setter
    func MessageInputBar.nonStackViewItems.modify
    func MessageInputBar.items.getter
    // <stripped> func textViewLayoutSet.getter 
    // <stripped> func textViewLayoutSet.setter 
    // <stripped> func textViewLayoutSet.modify 
    // <stripped> func textViewHeightAnchor.getter 
    // <stripped> func textViewHeightAnchor.setter 
    // <stripped> func textViewHeightAnchor.modify 
    // <stripped> func topStackViewLayoutSet.getter 
    // <stripped> func topStackViewLayoutSet.setter 
    // <stripped> func topStackViewLayoutSet.modify 
    // <stripped> func leftStackViewLayoutSet.getter 
    // <stripped> func leftStackViewLayoutSet.setter 
    // <stripped> func leftStackViewLayoutSet.modify 
    // <stripped> func rightStackViewLayoutSet.getter 
    // <stripped> func rightStackViewLayoutSet.setter 
    // <stripped> func rightStackViewLayoutSet.modify 
    // <stripped> func bottomStackViewLayoutSet.getter 
    // <stripped> func bottomStackViewLayoutSet.setter 
    // <stripped> func bottomStackViewLayoutSet.modify 
    // <stripped> func contentViewLayoutSet.getter 
    // <stripped> func contentViewLayoutSet.setter 
    // <stripped> func contentViewLayoutSet.modify 
    // <stripped> func windowAnchor.getter 
    // <stripped> func windowAnchor.setter 
    // <stripped> func windowAnchor.modify 
    // <stripped> func backgroundViewBottomAnchor.getter 
    // <stripped> func backgroundViewBottomAnchor.setter 
    // <stripped> func backgroundViewBottomAnchor.modify 
    func MessageInputBar.setup()
    func MessageInputBar.setupObservers()
    func MessageInputBar.setupSubviews()
    func MessageInputBar.setupConstraints()
    func MessageInputBar.setupConstraints(to:)
    func MessageInputBar.updatePadding()
    func MessageInputBar.updateTextViewPadding()
    func MessageInputBar.updateTopStackViewPadding()
    func MessageInputBar.calculateIntrinsicContentSize()
    func MessageInputBar.calculateMaxTextViewHeight()
    func MessageInputBar.layoutStackViews(_:)
    func MessageInputBar.performLayout(_:_:)
    func MessageInputBar.activateConstraints()
    func MessageInputBar.deactivateConstraints()
    func MessageInputBar.setStackViewItems(_:forStack:animated:)
    func MessageInputBar.setLeftStackViewWidthConstant(to:animated:)
    func MessageInputBar.setRightStackViewWidthConstant(to:animated:)
    func MessageInputBar.setShouldForceMaxTextViewHeight(to:animated:)
    func MessageInputBar.orientationDidChange()
    func MessageInputBar.inputTextViewDidChange()
    func MessageInputBar.inputTextViewDidBeginEditing()
    func MessageInputBar.inputTextViewDidEndEditing()
    func MessageInputBar.reloadPlugins()
    func MessageInputBar.invalidatePlugins()
    func MessageInputBar.didSelectSendButton()
}
