//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.MixpanelPersistence {
  /* fields */
    let instanceName: String
    let mpdb: Mixpanel.MPDB
  /* methods */
    // <stripped> static func init
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100925140 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1009254d4 // method (instance)
    func sub_1009256fc // method (instance)
    func sub_100925bf4 // method (instance)
    func sub_100925e8c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10092660c // method (instance)
    func sub_10092661c // method (instance)
    func sub_1009266e0 // method (instance)
    // <stripped> func method (instance)
    func sub_1009266f0 // method (instance)
    func sub_100926f88 // method (instance)
    func sub_100927360 // method (instance)
    // <stripped> func method (instance)
}
