//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.MixpanelInstance {
  /* fields */
    var apiToken: String
    var delegate: Mixpanel.MixpanelDelegate ?
    var distinctId: String
    var anonymousId: String?
    var userId: String?
    var hadPersistedDistinctId: Bool?
    var alias: String?
    var people: Mixpanel.People ?
    let mixpanelPersistence: Mixpanel.MixpanelPersistence
    var groups: Dictionary empty-list String Mixpanel.Group
    var showNetworkActivityIndicator: Swift.Bool
    var trackAutomaticEventsEnabled: Swift.Bool
    var serverURL: String
    var loggingEnabled: Swift.Bool
    let name: String
    var superProperties: [String : Any]
    var trackingQueue: DispatchQueue
    var networkQueue: DispatchQueue
    var optOutStatus: Bool?
    var useUniqueDistinctId: Swift.Bool
    var timedEvents: [String : Any]
    let readWriteLock: Mixpanel.ReadWriteLock
    var taskId: __C.UIBackgroundTaskIdentifier
    let sessionMetadata: Mixpanel.SessionMetadata
    let flushInstance: Mixpanel.Flush
    let trackInstance: Mixpanel.Track
    let automaticEvents: Mixpanel.AutomaticEvents
  /* methods */
    func MixpanelInstance.apiToken.getter
    func MixpanelInstance.apiToken.setter
    func MixpanelInstance.apiToken.modify
    func MixpanelInstance.delegate.getter
    func MixpanelInstance.delegate.setter
    func MixpanelInstance.delegate.modify
    func MixpanelInstance.distinctId.getter
    func MixpanelInstance.distinctId.setter
    func MixpanelInstance.distinctId.modify
    func MixpanelInstance.anonymousId.getter
    func MixpanelInstance.anonymousId.setter
    func MixpanelInstance.anonymousId.modify
    func MixpanelInstance.userId.getter
    func MixpanelInstance.userId.setter
    func MixpanelInstance.userId.modify
    func MixpanelInstance.hadPersistedDistinctId.getter
    func MixpanelInstance.hadPersistedDistinctId.setter
    func MixpanelInstance.hadPersistedDistinctId.modify
    func MixpanelInstance.alias.getter
    func MixpanelInstance.alias.setter
    func MixpanelInstance.alias.modify
    func MixpanelInstance.people.getter
    func MixpanelInstance.people.setter
    func MixpanelInstance.people.modify
    // <stripped> func groups.getter 
    // <stripped> func groups.setter 
    // <stripped> func groups.modify 
    func MixpanelInstance.showNetworkActivityIndicator.getter
    func MixpanelInstance.showNetworkActivityIndicator.setter
    func MixpanelInstance.showNetworkActivityIndicator.modify
    func MixpanelInstance.trackAutomaticEventsEnabled.getter
    func MixpanelInstance.trackAutomaticEventsEnabled.setter
    func MixpanelInstance.trackAutomaticEventsEnabled.modify
    func MixpanelInstance.flushInterval.getter
    func MixpanelInstance.flushInterval.setter
    func MixpanelInstance.flushInterval.modify
    func MixpanelInstance.flushOnBackground.getter
    func MixpanelInstance.flushOnBackground.setter
    func MixpanelInstance.flushOnBackground.modify
    func MixpanelInstance.useIPAddressForGeoLocation.getter
    func MixpanelInstance.useIPAddressForGeoLocation.setter
    func MixpanelInstance.useIPAddressForGeoLocation.modify
    func MixpanelInstance.serverURL.getter
    func MixpanelInstance.serverURL.setter
    func MixpanelInstance.serverURL.modify
    func MixpanelInstance.debugDescription.getter
    func MixpanelInstance.loggingEnabled.getter
    func MixpanelInstance.loggingEnabled.setter
    func MixpanelInstance.loggingEnabled.modify
    func MixpanelInstance.minimumSessionDuration.getter
    func MixpanelInstance.minimumSessionDuration.setter
    func MixpanelInstance.minimumSessionDuration.modify
    func MixpanelInstance.maximumSessionDuration.getter
    func MixpanelInstance.maximumSessionDuration.setter
    func MixpanelInstance.maximumSessionDuration.modify
    // <stripped> func timedEvents.getter 
    // <stripped> func timedEvents.setter 
    // <stripped> func timedEvents.modify 
    // <stripped> func taskId.getter 
    // <stripped> func taskId.setter 
    // <stripped> func taskId.modify 
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> static func init
    func MixpanelInstance.setupListeners()
    // <stripped> func method (instance)
    func MixpanelInstance.applicationWillResignActive(_:)
    func MixpanelInstance.applicationDidEnterBackground(_:)
    func MixpanelInstance.applicationWillEnterForeground(_:)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func MixpanelInstance.updateNetworkActivityIndicator(_:)
    func MixpanelInstance.setCurrentRadio()
    // <stripped> static func method
    // <stripped> static func method
}
