//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.ModeratorReportsController: Apollo.ActionController {
  /* fields */
    let userReports: [[Any]]
    let moderatorReports: [[Any]]
    let numberReports: Int
    let ignoringReports: Swift.Bool
    let state: Apollo.ModeratorReportableState ?
    let dataSource: Apollo.ModeratorReportsControllerDataSource
    let headerTableView: Apollo.HeightResizingTableView
    var approveTappedHandler: ((_:))?
    var removeTappedHandler: (())?
    var markSpamTappedHandler: (())?
    var ignoreReportsTappedHandler: ((_:))?
  /* methods */
    // <stripped> func approveTappedHandler.getter 
    // <stripped> func approveTappedHandler.setter 
    // <stripped> func approveTappedHandler.modify 
    // <stripped> func removeTappedHandler.getter 
    // <stripped> func removeTappedHandler.setter 
    // <stripped> func removeTappedHandler.modify 
    // <stripped> func markSpamTappedHandler.getter 
    // <stripped> func markSpamTappedHandler.setter 
    // <stripped> func markSpamTappedHandler.modify 
    // <stripped> func ignoreReportsTappedHandler.getter 
    // <stripped> func ignoreReportsTappedHandler.setter 
    // <stripped> func ignoreReportsTappedHandler.modify 
    // <stripped> static func init
}
