//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.ModeratorMutedUsersViewController: ASDKViewController<ASDisplayNode> {
  /* fields */
    let subreddit: String
    let tableNode: ASTableNode
    var mutedUsers: [[String : Any]]?
    var after: Int?
    var posts: [String : [String : Any]]?
    var comments: [String : [String : Any]]?
    let userButton: UIButton
    let addButton: UIButton
    let spinner: UIActivityIndicatorView
    let emptyLabel: UILabel
  /* methods */
    // <stripped> func mutedUsers.getter 
    // <stripped> func mutedUsers.setter 
    // <stripped> func mutedUsers.modify 
    // <stripped> func after.getter 
    // <stripped> func after.setter 
    // <stripped> func after.modify 
    // <stripped> func posts.getter 
    // <stripped> func posts.setter 
    // <stripped> func posts.modify 
    // <stripped> func comments.getter 
    // <stripped> func comments.setter 
    // <stripped> func comments.modify 
    // <stripped> static func init
    func sub_1003dcfa0 // method (instance)
    func sub_1003dd45c // method (instance)
    func sub_1003dd80c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003de278 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003df5b8 // method (instance)
    func sub_1003dfad4 // method (instance)
    func sub_1003e1880 // method (instance)
}
