//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.ModeratorBannedUsersViewController: ASDKViewController<ASDisplayNode> {
  /* fields */
    let subreddit: String
    let tableNode: ASTableNode
    var bannedUsers: [[String : Any]]?
    var after: Int?
    var posts: [String : [String : Any]]?
    var comments: [String : [String : Any]]?
    let userButton: UIButton
    let addButton: UIButton
    let spinner: UIActivityIndicatorView
    let emptyLabel: UILabel
  /* methods */
    // <stripped> func bannedUsers.getter 
    // <stripped> func bannedUsers.setter 
    // <stripped> func bannedUsers.modify 
    // <stripped> func after.getter 
    // <stripped> func after.setter 
    // <stripped> func after.modify 
    // <stripped> func posts.getter 
    // <stripped> func posts.setter 
    // <stripped> func posts.modify 
    // <stripped> func comments.getter 
    // <stripped> func comments.setter 
    // <stripped> func comments.modify 
    // <stripped> static func init
    func sub_1003d40c8 // method (instance)
    func sub_1003d4584 // method (instance)
    func sub_1003d4934 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003d558c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003d5800 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
