//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MoreCommentsSectionController: Apollo.SectionController {
  /* fields */
    var moreComments: RDKMoreComments
    var delegate: Apollo.MoreCommentsSectionControllerDelegate ?
    let postID: String
    let isLast: Swift.Bool
    var numberOfRepliesDeleted: Int?
  /* methods */
    // <stripped> func moreComments.getter 
    // <stripped> func moreComments.setter 
    // <stripped> func moreComments.modify 
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func numberOfRepliesDeleted.getter 
    // <stripped> func numberOfRepliesDeleted.setter 
    // <stripped> func numberOfRepliesDeleted.modify 
    // <stripped> static func init
    func sub_1006e3350 // method (instance)
    // <stripped> func method (instance)
}
