//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MultiredditViewController: Apollo.ApolloTableViewController {
  /* fields */
    let multiredditName: String
    let username: String
    var multireddit: RDKMultireddit?
    let addBarButtonItem: UIBarButtonItem
  /* methods */
    // <stripped> func multireddit.getter 
    // <stripped> func multireddit.setter 
    // <stripped> func multireddit.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_100103c74 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10010434c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100104c44 // method (instance)
}
