//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.MuteUnmuteVideoButtonNode: Apollo.ApolloButtonNode {
  /* fields */
    var isMuted: Swift.Bool
    let size: nominal type descriptor for CGFloat
    let icon: ASImageNode
    let audioSimulatingNode: ASDisplayNode
    var audioSimulatorTimer: NSTimer?
  /* methods */
    // <stripped> func isMuted.getter 
    // <stripped> func isMuted.setter 
    // <stripped> func isMuted.modify 
    // <stripped> func audioSimulatorTimer.getter 
    // <stripped> func audioSimulatorTimer.setter 
    // <stripped> func audioSimulatorTimer.modify 
    // <stripped> static func init
}
