//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.NotificationSound {
    case cat
    case dog
    case horse
    case penguin
    case chicken
    case turkey
    case sheep
    case cow
    case moon
    case traloop
    case beeBoBee
    case wow
    case developerSayingBeep
    case dropOfDeliberation
    case clickityClickerson
    case diabolicalDoorbell
    case inspiredIcicle
    case honervasHarp
    case curiousCuttlefish
    case neptuneNods
    case bubblesAndBotany
    case headsUpHenry
    case sonicSnap
    case echoingExpansion
    case digDigDig
    case duDuuuu
    case retro
    case happySighs
    case mechanicalKeyboard
    case apolloComms
    case aluminium
    case frog
}
