//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.Padlock: NSObject {
  /* fields */
    let blurOverlayView: Apollo.PadlockBlurView
    let unlockButton: UIButton
    let descriptionLabel: UILabel
    let padlockImageView: UIImageView
    var mostRecentEnterBackgroundTimeWhileAppUnlocked: Double?
    var sceneDelegate: Apollo.SceneDelegate ?
  /* methods */
    // <stripped> func mostRecentEnterBackgroundTimeWhileAppUnlocked.getter 
    // <stripped> func mostRecentEnterBackgroundTimeWhileAppUnlocked.setter 
    // <stripped> func mostRecentEnterBackgroundTimeWhileAppUnlocked.modify 
    // <stripped> func sceneDelegate.getter 
    // <stripped> func sceneDelegate.setter 
    // <stripped> func sceneDelegate.modify 
    // <stripped> func method (instance)
    func sub_1000febd8 // method (instance)
    // <stripped> func method (instance)
    func sub_1000fef78 // method (instance)
    // <stripped> func method (instance)
    func sub_1000ff800 // method (instance)
    func sub_1000ffa54 // method (instance)
    // <stripped> func method (instance)
    func sub_1000ffea4 // method (instance)
    // <stripped> func method (instance)
    func sub_100100294 // method (instance)
    func sub_1001003dc // method (instance)
}
