//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.PollResultNode: ASDisplayNode {
  /* fields */
    let option: RDKPollOption
    let userDidSelect: Swift.Bool
    let totalVotesInPoll: Int
    let hasMostVotes: Swift.Bool
    let backgroundNode: ASDisplayNode
    let textNode: ASTextNode
    let percentageNode: ASTextNode
    let checkmarkNode: ASImageNode?
    var showPercentages: Swift.Bool
  /* methods */
    // <stripped> func showPercentages.getter 
    // <stripped> func showPercentages.setter 
    // <stripped> func showPercentages.modify 
    // <stripped> static func init
    func sub_100637a3c // method (instance)
}
