//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.PostCellActionTaker: NSObject {
  /* fields */
    var sectionController: Apollo.SectionController ?
    var playerLayerSuperlayer: weak CALayer?
    var playerLayerFrame: __C.CGRect ?
    var didSuccessfullyPresentFromContextMenu: Swift.Bool
    var link: RDKLink
  /* methods */
    // <stripped> func sectionController.getter 
    // <stripped> func sectionController.setter 
    // <stripped> func sectionController.modify 
    // <stripped> func playerLayerSuperlayer.getter 
    // <stripped> func playerLayerSuperlayer.setter 
    // <stripped> func playerLayerSuperlayer.modify 
    // <stripped> func playerLayerFrame.getter 
    // <stripped> func playerLayerFrame.setter 
    // <stripped> func playerLayerFrame.modify 
    // <stripped> func didSuccessfullyPresentFromContextMenu.getter 
    // <stripped> func didSuccessfullyPresentFromContextMenu.setter 
    // <stripped> func didSuccessfullyPresentFromContextMenu.modify 
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    // <stripped> static func init
    func sub_1003171a8 // method (instance)
    func sub_100317a7c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003180d4 // method (instance)
    func sub_10031820c // method (instance)
    func sub_100318338 // method (instance)
    func sub_1003189f0 // method (instance)
    func sub_1003190ac // method (instance)
    func sub_100319ae4 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10031a524 // method (instance)
    func sub_10031a6ec // method (instance)
    func sub_10031a894 // method (instance)
    func sub_10031aa0c // method (instance)
    func sub_10031b86c // method (instance)
    func sub_10031d084 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10031ef64 // method (instance)
    func sub_100320bb4 // method (instance)
    func sub_100321eac // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003224ec // method (instance)
    func sub_1003235c0 // method (instance)
    func sub_1003244d0 // method (instance)
    func sub_100324a84 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100325690 // method (instance)
    // <stripped> func method (instance)
    func sub_100325860 // method (instance)
    func sub_100325c9c // method (instance)
    func sub_100325e84 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1003290f0 // method (instance)
    func sub_10032a2ac // method (instance)
    func sub_10032aa74 // method (instance)
    func sub_10032ae4c // method (instance)
    func sub_10032b45c // method (instance)
    func sub_10032b6f8 // method (instance)
    func sub_10032bda4 // method (instance)
    func sub_10032c458 // method (instance)
    func sub_10032c99c // method (instance)
    func sub_10032d068 // method (instance)
    func sub_10032d5f8 // method (instance)
    func sub_10032de78 // method (instance)
}
