//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.PostTitleNode: ASDisplayNode {
  /* fields */
    var link: RDKLink
    let isCompact: Swift.Bool
    let url: nominal type descriptor for URL ?
    let isBolder: Swift.Bool
    let disableFlairTap: Swift.Bool
    let titleNode: ASTextNode
    let flairNode: Apollo.FlairNode ?
    let nsfwNode: Apollo.PostContentAdvisoryNode ?
    let spoilerNode: Apollo.PostContentAdvisoryNode ?
    let urlNode: Apollo.PostTitleURLNode ?
    let horizontalSpacing: Double
    let verticalSpacing: Double
    var delegate: Apollo.PostTitleNodeDelegate ?
    var isRead: Swift.Bool
  /* methods */
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func isRead.getter 
    // <stripped> func isRead.setter 
    // <stripped> func isRead.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_100461734 // method (instance)
    // <stripped> func method (instance)
}
