//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.PostsViewController: Apollo.ASTableViewController {
  /* fields */
    var initialPostsType: Apollo.PostsType
    var currentPostsType: Apollo.PostsType
    var links: [RDKLink]
    var lazy pagination: RDKPagination??
    var initialPostsToLoad: UInt
    let refreshControl: Apollo.ApolloRefreshControl
    let listAdapter: Apollo.ListAdapter
    let jumpBar: Apollo.JumpBar ?
    let dropDownTableView: UITableView?
    let dropDownDataSource: Apollo.DropDownDataSource ?
    let partialDarkOverlayViewMain: UIView?
    var currentSubreddit: RDKSubreddit?
    var randomSubredditName: String?
    var currentMultireddit: RDKMultireddit?
    var currentSort: __C.RDKSubredditCategory ?
    var currentTimeSort: __C.RDKTimeSortingMethod ?
    var currentUserSort: __C.RDKUserContentSortingMethod ?
    let sortButton: UIButton
    let moderatorButton: UIButton
    let moreOptionsButton: UIButton
    let sectionHeaderToken: String
    let searchAllToken: String
    let loadNextPageTokenPrefix: String
    let reachedEndToken: String
    var lazy filterOutSubscriptions: Bool?
    var currentPage: Int
    let hideReadPostsButton: Apollo.FloatingActionButton
    var batchFetchContext: weak ASBatchContext?
    var currentSubredditIssue: Apollo.PostsViewController.CurrentSubredditIssue ?
    var restoredVisibleLink: RDKLink?
    var restoredContentOffsetY: nominal type descriptor for CGFloat ?
    var restoredViewWidth: nominal type descriptor for CGFloat ?
  /* methods */
    // <stripped> static func init
}
