//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.PostInfoNode: ASDisplayNode {
  /* fields */
    var link: RDKLink
    let showMoreOptions: Swift.Bool
    let subredditAuthorDisplayOptions: Apollo.PostInfoNode.SubredditAuthorDisplayOptions
    let showAuthorFlair: Swift.Bool
    let showPercentageLiked: Swift.Bool
    let showAwards: Swift.Bool
    let isCompact: Swift.Bool
    let showSubredditIcon: Swift.Bool
    let isInsideComments: Swift.Bool
    let censorUsername: Swift.Bool
    let censorSubreddit: Swift.Bool
    let modControlsDisplayOption: Apollo.PostInfoNode.CompactModControlsDisplayOption
    var isRead: Swift.Bool
    let subredditIconNode: Apollo.TouchHintNetworkImageNode ?
    let subredditButtonNode: Apollo.ApolloButtonNode ?
    let authorButtonNode: Apollo.ApolloButtonNode ?
    let flairNode: Apollo.FlairNode ?
    let pointsButtonNode: Apollo.ApolloButtonNode
    let percentageLikedButtonNode: Apollo.ApolloButtonNode ?
    var commentsInfoNode: Apollo.CommentsInfoNode ?
    let ageButtonNode: Apollo.ApolloButtonNode
    let editedButtonNode: Apollo.ApolloButtonNode ?
    var awardsNode: Apollo.AwardsNode ?
    let cakedayNode: ASImageNode?
    let moreOptionsButtonNode: Apollo.ApolloButtonNode ?
    let modOptionsNode: Apollo.CompactModOptionsNode ?
    let modButtonNode: Apollo.ApolloButtonNode ?
    let approvedButton: Apollo.ApolloButtonNode
    let announcementIndicatorNode: ASImageNode
    var isUsingPlaceholderSubredditIcon: Swift.Bool
  /* methods */
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    // <stripped> func isRead.getter 
    // <stripped> func isRead.setter 
    // <stripped> func isRead.modify 
    // <stripped> func commentsInfoNode.getter 
    // <stripped> func commentsInfoNode.setter 
    // <stripped> func commentsInfoNode.modify 
    // <stripped> func awardsNode.getter 
    // <stripped> func awardsNode.setter 
    // <stripped> func awardsNode.modify 
    // <stripped> static func init
    func sub_100398de8 // method (instance)
    func sub_10039938c // method (instance)
    // <stripped> func isUsingPlaceholderSubredditIcon.getter 
    // <stripped> func isUsingPlaceholderSubredditIcon.setter 
    // <stripped> func isUsingPlaceholderSubredditIcon.modify 
    func sub_10039ad04 // method (instance)
    func sub_10039b758 // method (instance)
    func sub_10039bc00 // method (instance)
    // <stripped> func method (instance)
    func sub_10039c5f8 // method (instance)
    func sub_10039cfa0 // method (instance)
}
