//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class SwiftyStoreKit.ProductsInfoController: NSObject {
  /* fields */
    let inAppProductRequestBuilder: SwiftyStoreKit.InAppProductRequestBuilder
    var inflightRequests: Dictionary empty-list Set<String> SwiftyStoreKit.ProductsInfoController.InAppProductQuery
  /* methods */
    // <stripped> static func init
    // <stripped> func inflightRequests.getter 
    // <stripped> func inflightRequests.setter 
    // <stripped> func inflightRequests.modify 
    func sub_1008e4ee8 // method (instance)
}
