//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum Apollo.ProFeature {
    case submitPosts
    case multipleAccounts
    case autoDarkMode
    case customAppIcon
    case touchIDPasscode
    case customizeGestures
    case contentFilters
    case commentColorThemes
    case homepage
    case gifScrubbing
    case indieSupport
    case betterMediaData
    case autoCollapse
    case autoHide
    case markReadOnScroll
    case localSubredditFilters
    case importingRESSubredditFilters
    case searchSaved
    case smartRotationLock
    case uploadVideo
    case settings
    case about
}
