//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.RedditListViewController: Apollo.ApolloTableViewController {
  /* fields */
    var refreshControl: UIRefreshControl?
    var editBarButtonItem: UIBarButtonItem?
    var addBarButtonItem: UIBarButtonItem?
    var doneBarButtonItem: UIBarButtonItem?
    var multireddits: [RDKMultireddit]?
    var subredditToLoad: String?
    var sectionIndexTitlesView: weak UIView?
    var preventSectionIndexTitlesFromWorking: Swift.Bool
    var panGestureCalled: Swift.Bool
    var subredditFetchProgress: (fetchedSubscriptions: Bool, fetchedMultireddits: Bool, fetchedModeratedSubreddits: Bool)?
    var subscribedSubreddits: [String]?
    var subredditNamesToFullnames: [String : String]
    var sectionedSubreddits: [[String]]?
    let subredditIconDiameter: nominal type descriptor for CGFloat
    var registeredFor3DTouch: Swift.Bool
    var viewHasBeenSeen: Swift.Bool
    var addSubredditAction: weak UIAlertAction?
  /* methods */
    // <stripped> func refreshControl.getter 
    // <stripped> func refreshControl.setter 
    // <stripped> func refreshControl.modify 
    // <stripped> func editBarButtonItem.getter 
    // <stripped> func editBarButtonItem.setter 
    // <stripped> func editBarButtonItem.modify 
    // <stripped> func addBarButtonItem.getter 
    // <stripped> func addBarButtonItem.setter 
    // <stripped> func addBarButtonItem.modify 
    // <stripped> func doneBarButtonItem.getter 
    // <stripped> func doneBarButtonItem.setter 
    // <stripped> func doneBarButtonItem.modify 
    // <stripped> func multireddits.getter 
    // <stripped> func multireddits.setter 
    // <stripped> func multireddits.modify 
    // <stripped> func subredditToLoad.getter 
    // <stripped> func subredditToLoad.setter 
    // <stripped> func subredditToLoad.modify 
    // <stripped> func sectionIndexTitlesView.getter 
    // <stripped> func sectionIndexTitlesView.setter 
    // <stripped> func sectionIndexTitlesView.modify 
    // <stripped> func preventSectionIndexTitlesFromWorking.getter 
    // <stripped> func preventSectionIndexTitlesFromWorking.setter 
    // <stripped> func preventSectionIndexTitlesFromWorking.modify 
    // <stripped> func panGestureCalled.getter 
    // <stripped> func panGestureCalled.setter 
    // <stripped> func panGestureCalled.modify 
    // <stripped> func subredditFetchProgress.getter 
    // <stripped> func subredditFetchProgress.setter 
    func subredditFetchProgress.modify.sub_1006390f8
    // <stripped> func subscribedSubreddits.getter 
    // <stripped> func subscribedSubreddits.setter 
    // <stripped> func subscribedSubreddits.modify 
    // <stripped> func subredditNamesToFullnames.getter 
    // <stripped> func subredditNamesToFullnames.setter 
    // <stripped> func subredditNamesToFullnames.modify 
    // <stripped> func sectionedSubreddits.getter 
    // <stripped> func sectionedSubreddits.setter 
    // <stripped> func sectionedSubreddits.modify 
    // <stripped> static func init
    // <stripped> func registeredFor3DTouch.getter 
    // <stripped> func registeredFor3DTouch.setter 
    // <stripped> func registeredFor3DTouch.modify 
    // <stripped> func viewHasBeenSeen.getter 
    // <stripped> func viewHasBeenSeen.setter 
    // <stripped> func viewHasBeenSeen.modify 
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10063a0e4 // method (instance)
    func sub_10063a290 // method (instance)
    func sub_10063a6b4 // method (instance)
    func sub_10063c6e0 // method (instance)
    func sub_10063d42c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10063dbb4 // method (instance)
    func sub_1006402dc // method (instance)
    func sub_10064093c // method (instance)
    func sub_1006415b0 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100644304 // method (instance)
    // <stripped> func method (instance)
    func sub_10064463c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100645540 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func addSubredditAction.getter 
    // <stripped> func addSubredditAction.setter 
    // <stripped> func addSubredditAction.modify 
    // <stripped> func method (instance)
    func sub_100648fd8 // method (instance)
    func sub_1006498dc // method (instance)
    // <stripped> func method (instance)
    func sub_10064a528 // method (instance)
    func sub_10064ad04 // method (instance)
    // <stripped> func method (instance)
    func sub_10064afc8 // method (instance)
    func sub_10064b954 // method (instance)
    // <stripped> func method (instance)
}
