//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.RichMediaNode: ASDisplayNode {
  /* fields */
    var link: RDKLink
    var isRead: Swift.Bool
    let isShowingCrosspostParent: Swift.Bool
    let forceShowThumbnail: Swift.Bool
    let obscuredType: Apollo.ObscuredType ?
    let isShownInCommentsHeader: Swift.Bool
    var videoSize: __C.CGSize ?
    var videoNodeStatus: Apollo.VideoNodeStatus
    var shouldCreateVideoGIFProgressViewIfDurationSufficient: Swift.Bool
    var contentType: Apollo.ContentIdentifier.ContentType ?
    let intermediaryNode: Apollo.ApolloButtonNode
    var obscuredContentInfoOverlayNode: Apollo.ObscuredContentInfoOverlayNode ?
    var thumbnailNode: Apollo.TouchHintNetworkImageNode ?
    var videoNode: Apollo.TouchHintVideoNode ?
    var videoGIFProgressView: Apollo.VideoGIFProgressView ?
    var selfPostPreviewNode: ASTextNode?
    var playheadIconNode: ASImageNode?
    var linkButtonNode: Apollo.LinkButtonNode ?
    var albumThumbnailsNode: Apollo.AlbumThumbnailsNode ?
    var contentTypeOverlayNode: Apollo.SmallInfoOverlayNode ?
    var muteUnmuteButtonNode: Apollo.MuteUnmuteVideoButtonNode ?
    var errorLoadingNode: Apollo.RichMediaErrorLoadingNode ?
    var actionDelegate: Apollo.PostCellActionDelegate ?
    var loader: Apollo.VideoResourceLoader ?
    var _imageAnalysisInteraction: Any?
    let assetOptions: [String : Any]
  /* methods */
    // <stripped> func link.getter 
    // <stripped> func link.setter 
    // <stripped> func link.modify 
    // <stripped> func isRead.getter 
    // <stripped> func isRead.setter 
    // <stripped> func isRead.modify 
    // <stripped> func videoSize.getter 
    // <stripped> func videoSize.setter 
    // <stripped> func videoSize.modify 
    // <stripped> func videoNodeStatus.getter 
    // <stripped> func videoNodeStatus.setter 
    // <stripped> func videoNodeStatus.modify 
    // <stripped> func shouldCreateVideoGIFProgressViewIfDurationSufficient.getter 
    // <stripped> func shouldCreateVideoGIFProgressViewIfDurationSufficient.setter 
    // <stripped> func shouldCreateVideoGIFProgressViewIfDurationSufficient.modify 
    // <stripped> func contentType.getter 
    // <stripped> func contentType.setter 
    // <stripped> func contentType.modify 
    // <stripped> func obscuredContentInfoOverlayNode.getter 
    // <stripped> func obscuredContentInfoOverlayNode.setter 
    // <stripped> func obscuredContentInfoOverlayNode.modify 
    // <stripped> func thumbnailNode.getter 
    // <stripped> func thumbnailNode.setter 
    // <stripped> func thumbnailNode.modify 
    // <stripped> func videoNode.getter 
    // <stripped> func videoNode.setter 
    // <stripped> func videoNode.modify 
    // <stripped> func videoGIFProgressView.getter 
    // <stripped> func videoGIFProgressView.setter 
    // <stripped> func videoGIFProgressView.modify 
    // <stripped> func selfPostPreviewNode.getter 
    // <stripped> func selfPostPreviewNode.setter 
    // <stripped> func selfPostPreviewNode.modify 
    // <stripped> func playheadIconNode.getter 
    // <stripped> func playheadIconNode.setter 
    // <stripped> func playheadIconNode.modify 
    // <stripped> func linkButtonNode.getter 
    // <stripped> func linkButtonNode.setter 
    // <stripped> func linkButtonNode.modify 
    // <stripped> func albumThumbnailsNode.getter 
    // <stripped> func albumThumbnailsNode.setter 
    // <stripped> func albumThumbnailsNode.modify 
    // <stripped> func contentTypeOverlayNode.getter 
    // <stripped> func contentTypeOverlayNode.setter 
    // <stripped> func contentTypeOverlayNode.modify 
    // <stripped> func muteUnmuteButtonNode.getter 
    // <stripped> func muteUnmuteButtonNode.setter 
    // <stripped> func muteUnmuteButtonNode.modify 
    // <stripped> func errorLoadingNode.getter 
    // <stripped> func errorLoadingNode.setter 
    // <stripped> func errorLoadingNode.modify 
    // <stripped> func getter (instance)
    // <stripped> func actionDelegate.getter 
    // <stripped> func actionDelegate.setter 
    // <stripped> func actionDelegate.modify 
    // <stripped> func loader.getter 
    // <stripped> func loader.setter 
    // <stripped> func loader.modify 
    // <stripped> func _imageAnalysisInteraction.getter 
    // <stripped> func _imageAnalysisInteraction.setter 
    // <stripped> func _imageAnalysisInteraction.modify 
    // <stripped> func getter (instance)
    // <stripped> static func init
    func sub_10057ab44 // method (instance)
    func sub_10057ad54 // method (instance)
    func sub_10057b104 // method (instance)
    func sub_10057b3a0 // method (instance)
    func sub_10057bae8 // method (instance)
    // <stripped> func method (instance)
    func sub_10057c93c // method (instance)
    func sub_10057d30c // method (instance)
    func sub_10057d42c // method (instance)
    func sub_100581f5c // method (instance)
    func sub_1005823dc // method (instance)
    func sub_10058249c // method (instance)
    func sub_10058264c // method (instance)
    func sub_100582a0c // method (instance)
    func sub_100587518 // method (instance)
    func sub_100587790 // method (instance)
    func sub_100587d10 // method (instance)
    func sub_100587e30 // method (instance)
    func sub_100587f78 // method (instance)
    func sub_1005880f8 // method (instance)
    func sub_100588318 // method (instance)
}
