//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SAConfettiView: UIView {
  /* fields */
    var emitter: CAEmitterLayer?
    var colors: [UIColor]?
    var intensity: Float?
    var type: Apollo.SAConfettiView.ConfettiType ?
    var active: Bool?
  /* methods */
    // <stripped> func emitter.getter 
    // <stripped> func emitter.setter 
    // <stripped> func emitter.modify 
    func SAConfettiView.colors.getter
    func SAConfettiView.colors.setter
    func SAConfettiView.colors.modify
    func SAConfettiView.intensity.getter
    func SAConfettiView.intensity.setter
    func SAConfettiView.intensity.modify
    func SAConfettiView.type.getter
    func SAConfettiView.type.setter
    func SAConfettiView.type.modify
    // <stripped> func active.getter 
    // <stripped> func active.setter 
    // <stripped> func active.modify 
    func sub_10008a5f8 // method (instance)
    func SAConfettiView.startConfetti()
    func SAConfettiView.stopConfetti()
    // <stripped> func method (instance)
    func sub_10008ba40 // method (instance)
    func SAConfettiView.isActive()
}
