//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SaveAsImagePreviewNode: ASDisplayNode {
  /* fields */
    let comment: RDKComment?
    let link: RDKLink
    let parentComments: [RDKComment]
    let includeWatermark: Swift.Bool
    let includePostDetails: Swift.Bool
    let includePostTextPollOrImage: Swift.Bool
    let imageForImagePost: UIImage?
    let hideUsernames: Swift.Bool
    let hideSubreddit: Swift.Bool
    let imageNode: ASImageNode?
    let postTitleNode: Apollo.PostTitleNode ?
    let postInfoNode: Apollo.PostInfoNode ?
    let postDetailsSeparator: ASDisplayNode?
    let bodyNode: Apollo.MarkdownNode ?
    let pollNode: Apollo.PollNode ?
    let linkButtonNode: Apollo.LinkButtonNode ?
    let baseCommentNode: Apollo.CommentCellNode ?
    let parentCommentNodes: Array -> Apollo.CommentCellNode
    let watermarkIconNode: ASImageNode?
    let watermarkTextNode: ASTextNode?
    let commentSeparators: [ASDisplayNode]
  /* methods */
    // <stripped> static func init
    func sub_100459644 // method (instance)
}
