//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SearchViewController: Apollo.ApolloTableViewController {
  /* fields */
    var searchBar: UISearchBar?
    var tapGestureRecognizer: UITapGestureRecognizer?
    var trendingSubreddits: [String]?
    var searching: Swift.Bool
    var localSubredditSuggestions: [String]
    var remoteSubredditSuggestions: [String]?
    var narrowedRemoteSubredditSuggestions: [String]?
    var searchQuery: String?
    var previousSearchQuery: String?
    let goalResultsAmount: Int
    var immediatelyStartSearching: Swift.Bool
  /* methods */
    // <stripped> func searchBar.getter 
    // <stripped> func searchBar.setter 
    // <stripped> func searchBar.modify 
    // <stripped> func tapGestureRecognizer.getter 
    // <stripped> func tapGestureRecognizer.setter 
    // <stripped> func tapGestureRecognizer.modify 
    // <stripped> func trendingSubreddits.getter 
    // <stripped> func trendingSubreddits.setter 
    // <stripped> func trendingSubreddits.modify 
    // <stripped> func searching.getter 
    // <stripped> func searching.setter 
    // <stripped> func searching.modify 
    // <stripped> func localSubredditSuggestions.getter 
    // <stripped> func localSubredditSuggestions.setter 
    // <stripped> func localSubredditSuggestions.modify 
    // <stripped> func remoteSubredditSuggestions.getter 
    // <stripped> func remoteSubredditSuggestions.setter 
    // <stripped> func remoteSubredditSuggestions.modify 
    // <stripped> func narrowedRemoteSubredditSuggestions.getter 
    // <stripped> func narrowedRemoteSubredditSuggestions.setter 
    // <stripped> func narrowedRemoteSubredditSuggestions.modify 
    // <stripped> func searchQuery.getter 
    // <stripped> func searchQuery.setter 
    // <stripped> func searchQuery.modify 
    // <stripped> func previousSearchQuery.getter 
    // <stripped> func previousSearchQuery.setter 
    // <stripped> func previousSearchQuery.modify 
    // <stripped> func immediatelyStartSearching.getter 
    // <stripped> func immediatelyStartSearching.setter 
    // <stripped> func immediatelyStartSearching.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1002b4488 // method (instance)
    func sub_1002b46ec // method (instance)
    func sub_1002b5efc // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1002b6894 // method (instance)
    func sub_1002b9670 // method (instance)
    func sub_1002b97c0 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
