//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Mixpanel.SessionMetadata {
  /* fields */
    var eventsCounter: nominal type descriptor for UInt64
    var peopleCounter: nominal type descriptor for UInt64
    var sessionID: String
    var sessionStartEpoch: nominal type descriptor for UInt64
    var trackingQueue: DispatchQueue
  /* methods */
    // <stripped> func eventsCounter.getter 
    // <stripped> func eventsCounter.setter 
    // <stripped> func eventsCounter.modify 
    // <stripped> func peopleCounter.getter 
    // <stripped> func peopleCounter.setter 
    // <stripped> func peopleCounter.modify 
    // <stripped> func sessionID.getter 
    // <stripped> func sessionID.setter 
    // <stripped> func sessionID.modify 
    // <stripped> func sessionStartEpoch.getter 
    // <stripped> func sessionStartEpoch.setter 
    // <stripped> func sessionStartEpoch.modify 
    // <stripped> func trackingQueue.getter 
    // <stripped> func trackingQueue.setter 
    // <stripped> func trackingQueue.modify 
    // <stripped> static func init
    func sub_100932a00 // method (instance)
    func sub_100932d84 // method (instance)
}
