//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SetSavedCategoryButton: UIControl {
  /* fields */
    var visibilityDelegate: Apollo.SetSavedCategoryButtonVisibilityDelegate ?
    let imageView: UIImageView
    let titleLabel: UILabel
    let horizontalSpacing: Double
    let verticalSpacing: Double
    let intraItemSpacing: Double
  /* methods */
    // <stripped> func visibilityDelegate.getter 
    // <stripped> func visibilityDelegate.setter 
    // <stripped> func visibilityDelegate.modify 
    // <stripped> func method (instance)
}
