//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SharePlaySettingsHeaderView: UIView {
  /* fields */
    let label: UILabel
    let internalWrapperView: UIView
    let toggle: UISwitch
  /* methods */
    func sub_1006dd578 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
