//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SlideGestureBuilder: NSObject {
  /* fields */
    let area: Apollo.SlideGestureArea
    var slidingView: weak UIView?
    let panGestureRecognizer: UIPanGestureRecognizer
    var gestureDisplayView: UIView?
    var gestureDisplayIcon: UIImageView?
    var delegate: Apollo.SlideGestureDelegate ?
    var scaleAnimationPossible: Swift.Bool
    var activatedSlideGesturePoint: Apollo.SlideGesturePoint ?
    let selectionGenerator: UISelectionFeedbackGenerator
    let scrollFriction: nominal type descriptor for CGFloat
    let iconDistanceFromCellEdge: nominal type descriptor for CGFloat
    let firstThreshold: nominal type descriptor for CGFloat
    var animatingIcon: Swift.Bool
  /* methods */
    // <stripped> func slidingView.getter 
    // <stripped> func slidingView.setter 
    // <stripped> func slidingView.modify 
    // <stripped> func gestureDisplayView.getter 
    // <stripped> func gestureDisplayView.setter 
    // <stripped> func gestureDisplayView.modify 
    // <stripped> func gestureDisplayIcon.getter 
    // <stripped> func gestureDisplayIcon.setter 
    // <stripped> func gestureDisplayIcon.modify 
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> func scaleAnimationPossible.getter 
    // <stripped> func scaleAnimationPossible.setter 
    // <stripped> func scaleAnimationPossible.modify 
    // <stripped> func activatedSlideGesturePoint.getter 
    // <stripped> func activatedSlideGesturePoint.setter 
    // <stripped> func activatedSlideGesturePoint.modify 
    // <stripped> func getter (instance)
    // <stripped> static func init
    func sub_10040ace8 // method (instance)
    func sub_10040ae30 // method (instance)
    // <stripped> func animatingIcon.getter 
    // <stripped> func animatingIcon.setter 
    // <stripped> func animatingIcon.modify 
    func sub_10040b4a8 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> static func method
    // <stripped> static func method
}
