//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SourdoughViewController: UIViewController {
  /* fields */
    let scrollView: UIScrollView
    let rootView: UIVisualEffectView
    let closeButton: UIButton
    let bottomSpacing: nominal type descriptor for CGFloat
    let closeButtonDiameter: nominal type descriptor for CGFloat
    var isHeightRestricted: Swift.Bool
  /* methods */
    // <stripped> func isHeightRestricted.getter 
    // <stripped> func isHeightRestricted.setter 
    // <stripped> func isHeightRestricted.modify 
    func sub_10045e414 // method (instance)
    func sub_10045ed04 // method (instance)
    func sub_10045e500 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10045e614 // method (instance)
}
