//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SpookyAlertView: UIView {
  /* fields */
    let heroImageView: UIImageView
    let titleLabel: UILabel
    let subtitleLabel: UILabel
    let button1: UIButton
    let button2: UIButton?
    let buttonGroupWrapper: UIView?
    var delegate: Apollo.SpookyAlertViewDelegate ?
    let button1Text: String
    let button2Text: String?
  /* methods */
    // <stripped> func delegate.getter 
    // <stripped> func delegate.setter 
    // <stripped> func delegate.modify 
    // <stripped> static func init
    func sub_1004fcaac // method (instance)
    func sub_1004fd52c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
}
