//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Statsig.StatsigClient {
  /* fields */
    var logger: Statsig.EventLogger
    var sdkKey: String
    var currentUser: Statsig.StatsigUser
    var statsigOptions: Statsig.StatsigOptions
    var store: Statsig.InternalStore
    var networkService: Statsig.NetworkService
    var syncTimer: NSTimer?
    var loggedExposures: [String : Double]
    var listeners: [()]
    var hasInitialized: Swift.Bool
    var lastInitializeError: String?
    let exposureDedupeQueue: DispatchQueue
    let maxEventNameLength: Int
  /* methods */
    // <stripped> func logger.getter 
    // <stripped> func logger.setter 
    // <stripped> func logger.modify 
    // <stripped> func sdkKey.getter 
    // <stripped> func sdkKey.setter 
    // <stripped> func sdkKey.modify 
    // <stripped> func currentUser.getter 
    // <stripped> func currentUser.setter 
    // <stripped> func currentUser.modify 
    // <stripped> func statsigOptions.getter 
    // <stripped> func statsigOptions.setter 
    // <stripped> func statsigOptions.modify 
    // <stripped> func store.getter 
    // <stripped> func store.setter 
    // <stripped> func store.modify 
    // <stripped> func networkService.getter 
    // <stripped> func networkService.setter 
    // <stripped> func networkService.modify 
    // <stripped> func syncTimer.getter 
    // <stripped> func syncTimer.setter 
    // <stripped> func syncTimer.modify 
    // <stripped> func loggedExposures.getter 
    // <stripped> func loggedExposures.setter 
    // <stripped> func loggedExposures.modify 
    // <stripped> func listeners.getter 
    // <stripped> func listeners.setter 
    // <stripped> func listeners.modify 
    // <stripped> func hasInitialized.getter 
    // <stripped> func hasInitialized.setter 
    // <stripped> func hasInitialized.modify 
    // <stripped> func lastInitializeError.getter 
    // <stripped> func lastInitializeError.setter 
    // <stripped> func lastInitializeError.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_1008c99c4 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008c9b70 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008c9ea4 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008ca18c // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008ca450 // method (instance)
    func sub_1008ca8c4 // method (instance)
    func sub_1008cac98 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008cadf0 // method (instance)
    func sub_1008cb314 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_1008cbe7c // method (instance)
    func sub_1008cc22c // method (instance)
    func sub_1008cc238 // method (instance)
}
