//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.SubredditModeratorListViewController: Apollo.ApolloTableViewController {
  /* fields */
    let subreddit: String
    let isViewedByMod: Swift.Bool
    var subredditModerators: [[String : Any]]?
    var invitedModerators: [[String : Any]]?
    let titleViewButton: UIButton
    let spinner: UIActivityIndicatorView
    var cancelBarButtonItem: UIBarButtonItem?
    let addBarButtonItem: UIBarButtonItem?
  /* methods */
    // <stripped> func subredditModerators.getter 
    // <stripped> func subredditModerators.setter 
    // <stripped> func subredditModerators.modify 
    // <stripped> func invitedModerators.getter 
    // <stripped> func invitedModerators.setter 
    // <stripped> func invitedModerators.modify 
    // <stripped> func cancelBarButtonItem.getter 
    // <stripped> func cancelBarButtonItem.setter 
    // <stripped> func cancelBarButtonItem.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100219810 // method (instance)
    func sub_10021a7c0 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10021bd48 // method (instance)
    func sub_10021c868 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10021d090 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_10021ea94 // method (instance)
}
