//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.TextSliderCell: nominal type descriptor for Cell Int {
  /* fields */
    var slider: Apollo.ApolloDiscreteSlider ?
    var smallALabel: UILabel?
    var largeALabel: UILabel?
    var inactive: Swift.Bool
  /* methods */
    // <stripped> func slider.getter 
    // <stripped> func slider.setter 
    // <stripped> func slider.modify 
    // <stripped> func smallALabel.getter 
    // <stripped> func smallALabel.setter 
    // <stripped> func smallALabel.modify 
    // <stripped> func largeALabel.getter 
    // <stripped> func largeALabel.setter 
    // <stripped> func largeALabel.modify 
    // <stripped> func inactive.getter 
    func inactive.setter.sub_1006e8800
    // <stripped> func inactive.modify 
    func sub_1006e91fc // method (instance)
}
