//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.TextEntryView: UIView {
  /* fields */
    let firstFieldInfo: Apollo.TextEntryViewFieldInfo
    let secondFieldInfo: Apollo.TextEntryViewFieldInfo ?
    let textField1: Apollo.InsetTextField
    let textField2: Apollo.InsetTextField ?
    let borderView: UIView
    let separatorView: UIView?
    let pasteButton1: UIButton?
    let pasteButton2: UIButton?
    let edgeInset: nominal type descriptor for CGFloat
    let innerViewCornerRadius: nominal type descriptor for CGFloat
    var textField1TextChangedHandler: ((_:))?
    var textField2TextChangedHandler: ((_:))?
  /* methods */
    // <stripped> func textField1TextChangedHandler.getter 
    // <stripped> func textField1TextChangedHandler.setter 
    // <stripped> func textField1TextChangedHandler.modify 
    // <stripped> func textField2TextChangedHandler.getter 
    // <stripped> func textField2TextChangedHandler.setter 
    // <stripped> func textField2TextChangedHandler.modify 
    // <stripped> static func init
    func sub_100563138 // method (instance)
    func sub_100563c78 // method (instance)
    // <stripped> func method (instance)
    // <stripped> func method (instance)
    func sub_100563e68 // method (instance)
    func sub_100563ecc // method (instance)
}
