//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

enum SwiftyStoreKit.TransactionResult {
    case purchased: SwiftyStoreKit.PurchaseDetails purchase_t
    case restored: SwiftyStoreKit.Purchase purchase_t
    case deferred: SwiftyStoreKit.PurchaseDetails purchase_t
    case failed: __C_Synthesized.SKError error_t
}
