//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.WallpapersActionControllerPreviewView: UIVisualEffectView {
  /* fields */
    let wallpaper1ImageView: UIImageView
    let wallpaper2ImageView: UIImageView
    let wallpaper1TitleLabel: UILabel
    let wallpaper2TitleLabel: UILabel
    let imageTopSpacing: nominal type descriptor for CGFloat
    let imageBottomSpacing: nominal type descriptor for CGFloat
    let titleBottomSpacing: nominal type descriptor for CGFloat
    let thumbnailHorizontalSpacing: nominal type descriptor for CGFloat
  /* methods */
    func sub_10053ff50 // method (instance)
}
