//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.WallpaperMessenger {
  /* fields */
    var _transactionInProgress: nominal type descriptor for Published Swift.Bool
    var _unlocked: nominal type descriptor for Published Swift.Bool
  /* methods */
    func _transactionInProgress.getter.sub_1000e2b14
    // <stripped> func _transactionInProgress.setter 
    // <stripped> func _transactionInProgress.modify 
    // <stripped> func _unlocked.getter 
    // <stripped> func _unlocked.setter 
    // <stripped> func _unlocked.modify 
    func sub_1000e2b28 // getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> func getter (instance)
    // <stripped> func setter (instance)
    // <stripped> func modify (instance)
    // <stripped> static func init
}
