//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.683, BuildCommit: 69c8858f7c5f9109ff2a1fe7b27d67bdd0cf5342)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15, SDK: 16.2, Tool: ld (820.1)
//    - LC_SOURCE_VERSION: 0.0.0.0.0
//
import Foundation

class Apollo.WeatherManager {
  /* fields */
    var isWeatherFetchingPossible: Swift.Bool
    let dispatchQueue: DispatchQueue
    var lazy cache: Dictionary empty-list StringArray -> nominal type descriptor for HourWeather _$sGGSg
  /* methods */
    // <stripped> func isWeatherFetchingPossible.getter 
    // <stripped> func isWeatherFetchingPossible.setter 
    // <stripped> func isWeatherFetchingPossible.modify 
    func cache.getter.sub_1003e4c18
    // <stripped> func cache.setter 
    // <stripped> func cache.modify 
    // <stripped> static func init
    // <stripped> func method (instance)
    func sub_1003e5500 // method (instance|async)
    // <stripped> func method (instance)
}
